#include "card.h"

// MAZO DE Cantuna
const CardData CARTAS_CANTUNA[] = {
    {0, "Ladrillazo", FX_ATTACK, 3, 0, 0, 0, "Arroja un ladrillo", "Dano: 3", ""},
    {1, "Ladrillazo", FX_ATTACK, 3, 0, 0, 0, "Arroja un ladrillo", "Dano: 3", ""},
    {2, "Ladrillazo", FX_ATTACK, 3, 0, 0, 0, "Arroja un ladrillo", "Dano: 3", ""},
    {3, "Golpe de Piedra", FX_ATTACK, 2, 0, 0, 0, "Piedra tallada", "Dano: 2", ""},
    {4, "Golpe de Piedra", FX_ATTACK, 2, 0, 0, 0, "Piedra tallada", "Dano: 2", ""},
    {5, "Golpe de Piedra", FX_ATTACK, 2, 0, 0, 0, "Piedra tallada", "Dano: 2", ""},
    {6, "Avalancha", FX_ATTACK, 5, 0, 0, 0, "Poder del Pichincha", "Dano: 5", ""},
    {7, "Avalancha", FX_ATTACK, 5, 0, 0, 0, "Poder del Pichincha", "Dano: 5", ""},
    {8, "Muro de Piedra", FX_SHIELD, 0, 2, 0, 0, "Muro de iglesia", "Escudo: 2", ""},
    {9, "Muro de Piedra", FX_SHIELD, 0, 2, 0, 0, "Muro de iglesia", "Escudo: 2", ""},
    {10, "Muro de Piedra", FX_SHIELD, 0, 2, 0, 0, "Muro de iglesia", "Escudo: 2", ""},
    {11, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Ni el diablo pasa", "Escudo: 3", ""},
    {12, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Ni el diablo pasa", "Escudo: 3", ""},
    {13, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Ni el diablo pasa", "Escudo: 3", ""},
    {14, "Descanso", FX_HEAL, 0, 0, 2, 0, "Descansa un rato", "Cura: 2 HP", ""},
    {15, "Descanso", FX_HEAL, 0, 0, 2, 0, "Descansa un rato", "Cura: 2 HP", ""},
    {16, "Pacto Diabolico", FX_HEAL, 0, 0, 4, 0, "El diablo ayuda", "Cura: 4 HP", ""},
    {17, "Pacto Diabolico", FX_HEAL, 0, 0, 4, 0, "El diablo ayuda", "Cura: 4 HP", ""},
    {18, "Planos Secretos", FX_DRAW, 0, 0, 0, 2, "Nuevas ideas", "Roba: 2", ""},
    {19, "Planos Secretos", FX_DRAW, 0, 0, 0, 2, "Nuevas ideas", "Roba: 2", ""},
    {20, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Ideas geniales", "Roba: 1 + Juega otra", ""},
    {21, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Ideas geniales", "Roba: 1 + Juega otra", ""},
    {22, "Contraataque", FX_ATTACK | FX_SHIELD, 2, 1, 0, 0, "Golpea y cubre", "Dano:2 Escudo:1", ""},
    {23, "Contraataque", FX_ATTACK | FX_SHIELD, 2, 1, 0, 0, "Golpea y cubre", "Dano:2 Escudo:1", ""},
    {24, "Furia Constructor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Construye rapido", "Dano:2 + Juega otra", ""},
    {25, "Furia Constructor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Construye rapido", "Dano:2 + Juega otra", ""},
    {26, "Bendicion Oscura", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Trato oscuro", "Cura:2 Roba:1", ""},
    {27, "Bendicion Oscura", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Trato oscuro", "Cura:2 Roba:1", ""},
};
const int CANTUNA_DECK_SIZE = 28;

// MAZO DE El Tin Tin
const CardData CARTAS_TINTIN[] = {
    {0, "Travesura", FX_ATTACK, 2, 0, 0, 0, "Esconde tus cosas", "Dano: 2", ""},
    {1, "Travesura", FX_ATTACK, 2, 0, 0, 0, "Esconde tus cosas", "Dano: 2", ""},
    {2, "Travesura", FX_ATTACK, 2, 0, 0, 0, "Esconde tus cosas", "Dano: 2", ""},
    {3, "Travesura", FX_ATTACK, 2, 0, 0, 0, "Esconde tus cosas", "Dano: 2", ""},
    {4, "Sombrerazo", FX_ATTACK, 3, 0, 0, 0, "Sombrero gigante", "Dano: 3", ""},
    {5, "Sombrerazo", FX_ATTACK, 3, 0, 0, 0, "Sombrero gigante", "Dano: 3", ""},
    {6, "Sombrerazo", FX_ATTACK, 3, 0, 0, 0, "Sombrero gigante", "Dano: 3", ""},
    {7, "Emboscada", FX_ATTACK, 4, 0, 0, 0, "Sale de la nada", "Dano: 4", ""},
    {8, "Emboscada", FX_ATTACK, 4, 0, 0, 0, "Sale de la nada", "Dano: 4", ""},
    {9, "Emboscada", FX_ATTACK, 4, 0, 0, 0, "Sale de la nada", "Dano: 4", ""},
    {10, "Escondite", FX_SHIELD, 0, 1, 0, 0, "Se esconde", "Escudo: 1", ""},
    {11, "Escondite", FX_SHIELD, 0, 1, 0, 0, "Se esconde", "Escudo: 1", ""},
    {12, "Escondite", FX_SHIELD, 0, 1, 0, 0, "Se esconde", "Escudo: 1", ""},
    {13, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Planear la proxima", "Cura: 2 HP", ""},
    {14, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Planear la proxima", "Cura: 2 HP", ""},
    {15, "Robo de Bolsillos", FX_DRAW, 0, 0, 0, 2, "Manos rapidas", "Roba: 2", ""},
    {16, "Robo de Bolsillos", FX_DRAW, 0, 0, 0, 2, "Manos rapidas", "Roba: 2", ""},
    {17, "Robo de Bolsillos", FX_DRAW, 0, 0, 0, 2, "Manos rapidas", "Roba: 2", ""},
    {18, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Rapido!", "Roba:1 + Juega otra", ""},
    {19, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Rapido!", "Roba:1 + Juega otra", ""},
    {20, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Rapido!", "Roba:1 + Juega otra", ""},
    {21, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Rapido!", "Roba:1 + Juega otra", ""},
    {22, "Golpe Fugaz", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Golpea y se va", "Dano:2 + Juega otra", ""},
    {23, "Golpe Fugaz", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Golpea y se va", "Dano:2 + Juega otra", ""},
    {24, "Golpe Fugaz", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Golpea y se va", "Dano:2 + Juega otra", ""},
    {25, "Ataque Sorpresa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1, "Por la espalda", "Dano:3 Roba:1", ""},
    {26, "Ataque Sorpresa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1, "Por la espalda", "Dano:3 Roba:1", ""},
    {27, "Ataque Sorpresa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1, "Por la espalda", "Dano:3 Roba:1", ""},
};
const int TINTIN_DECK_SIZE = 28;

// MAZO DE La Tunda
const CardData CARTAS_TUNDA[] = {
    {0, "Zarpazo", FX_ATTACK, 3, 0, 0, 0, "Mano de garra", "Dano: 3", ""},
    {1, "Zarpazo", FX_ATTACK, 3, 0, 0, 0, "Mano de garra", "Dano: 3", ""},
    {2, "Zarpazo", FX_ATTACK, 3, 0, 0, 0, "Mano de garra", "Dano: 3", ""},
    {3, "Molinillazo", FX_ATTACK, 4, 0, 0, 0, "Golpe de pata", "Dano: 4", ""},
    {4, "Molinillazo", FX_ATTACK, 4, 0, 0, 0, "Golpe de pata", "Dano: 4", ""},
    {5, "Molinillazo", FX_ATTACK, 4, 0, 0, 0, "Golpe de pata", "Dano: 4", ""},
    {6, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0, "Niebla protectora", "Escudo: 2", ""},
    {7, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0, "Niebla protectora", "Escudo: 2", ""},
    {8, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0, "Niebla protectora", "Escudo: 2", ""},
    {9, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0, "Niebla protectora", "Escudo: 2", ""},
    {10, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Camarones frescos", "Cura: 2 HP", ""},
    {11, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Camarones frescos", "Cura: 2 HP", ""},
    {12, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Camarones frescos", "Cura: 2 HP", ""},
    {13, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Camarones frescos", "Cura: 2 HP", ""},
    {14, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0, "Cantos ancestrales", "Cura: 4 HP", ""},
    {15, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0, "Cantos ancestrales", "Cura: 4 HP", ""},
    {16, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0, "Cantos ancestrales", "Cura: 4 HP", ""},
    {17, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0, "Cantos ancestrales", "Cura: 4 HP", ""},
    {18, "Susurros", FX_DRAW, 0, 0, 0, 2, "Misterios", "Roba: 2", ""},
    {19, "Susurros", FX_DRAW, 0, 0, 0, 2, "Misterios", "Roba: 2", ""},
    {20, "Encantamiento", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Hipnosis", "Roba:1 + Juega otra", ""},
    {21, "Encantamiento", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Hipnosis", "Roba:1 + Juega otra", ""},
    {22, "Drenar Vida", FX_ATTACK | FX_HEAL, 2, 0, 2, 0, "Absorbe energia", "Dano:2 Cura:2", ""},
    {23, "Drenar Vida", FX_ATTACK | FX_HEAL, 2, 0, 2, 0, "Absorbe energia", "Dano:2 Cura:2", ""},
    {24, "Drenar Vida", FX_ATTACK | FX_HEAL, 2, 0, 2, 0, "Absorbe energia", "Dano:2 Cura:2", ""},
    {25, "Maldicion", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0, "Mal de ojo", "Dano:3 Escudo:1", ""},
    {26, "Maldicion", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0, "Mal de ojo", "Dano:3 Escudo:1", ""},
    {27, "Maldicion", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0, "Mal de ojo", "Dano:3 Escudo:1", ""},
};
const int TUNDA_DECK_SIZE = 28;

// MAZO DE Padre Almeida
const CardData CARTAS_ALMEIDA[] = {
    {0, "Guitarrazo", FX_ATTACK, 2, 0, 0, 0, "Golpe musical", "Dano: 2", ""},
    {1, "Guitarrazo", FX_ATTACK, 2, 0, 0, 0, "Golpe musical", "Dano: 2", ""},
    {2, "Guitarrazo", FX_ATTACK, 2, 0, 0, 0, "Golpe musical", "Dano: 2", ""},
    {3, "Guitarrazo", FX_ATTACK, 2, 0, 0, 0, "Golpe musical", "Dano: 2", ""},
    {4, "Hasta la vuelta", FX_ATTACK, 4, 0, 0, 0, "Senor, hasta la vuelta", "Dano: 4", ""},
    {5, "Hasta la vuelta", FX_ATTACK, 4, 0, 0, 0, "Senor, hasta la vuelta", "Dano: 4", ""},
    {6, "Hasta la vuelta", FX_ATTACK, 4, 0, 0, 0, "Senor, hasta la vuelta", "Dano: 4", ""},
    {7, "Salto del Muro", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Se escapa", "Dano:2 + Juega otra", ""},
    {8, "Salto del Muro", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Se escapa", "Dano:2 + Juega otra", ""},
    {9, "Salto del Muro", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Se escapa", "Dano:2 + Juega otra", ""},
    {10, "Salto del Muro", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Se escapa", "Dano:2 + Juega otra", ""},
    {11, "Habito Protector", FX_SHIELD, 0, 2, 0, 0, "Proteccion sagrada", "Escudo: 2", ""},
    {12, "Habito Protector", FX_SHIELD, 0, 2, 0, 0, "Proteccion sagrada", "Escudo: 2", ""},
    {13, "Habito Protector", FX_SHIELD, 0, 2, 0, 0, "Proteccion sagrada", "Escudo: 2", ""},
    {14, "Habito Protector", FX_SHIELD, 0, 2, 0, 0, "Proteccion sagrada", "Escudo: 2", ""},
    {15, "Arrepentimiento", FX_HEAL, 0, 0, 3, 0, "Reza por perdon", "Cura: 3 HP", ""},
    {16, "Arrepentimiento", FX_HEAL, 0, 0, 3, 0, "Reza por perdon", "Cura: 3 HP", ""},
    {17, "Arrepentimiento", FX_HEAL, 0, 0, 3, 0, "Reza por perdon", "Cura: 3 HP", ""},
    {18, "Farra Nocturna", FX_DRAW, 0, 0, 0, 2, "Mas diversion", "Roba: 2", ""},
    {19, "Farra Nocturna", FX_DRAW, 0, 0, 0, 2, "Mas diversion", "Roba: 2", ""},
    {20, "Farra Nocturna", FX_DRAW, 0, 0, 0, 2, "Mas diversion", "Roba: 2", ""},
    {21, "Farra Nocturna", FX_DRAW, 0, 0, 0, 2, "Mas diversion", "Roba: 2", ""},
    {22, "Brindis", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Salud!", "Cura:2 Roba:1", ""},
    {23, "Brindis", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Salud!", "Cura:2 Roba:1", ""},
    {24, "Brindis", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Salud!", "Cura:2 Roba:1", ""},
    {25, "Pecado y Culpa", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0, "Doble moral", "Dano:3 Escudo:1", ""},
    {26, "Pecado y Culpa", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0, "Doble moral", "Dano:3 Escudo:1", ""},
    {27, "Pecado y Culpa", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0, "Doble moral", "Dano:3 Escudo:1", ""},
};
const int ALMEIDA_DECK_SIZE = 28;

// MAZO DE Dama Tapada
const CardData CARTAS_DAMATAPADA[] = {
    {0, "Susto Mortal", FX_ATTACK, 4, 0, 0, 0, "Muestra el rostro", "Dano: 4", ""},
    {1, "Susto Mortal", FX_ATTACK, 4, 0, 0, 0, "Muestra el rostro", "Dano: 4", ""},
    {2, "Susto Mortal", FX_ATTACK, 4, 0, 0, 0, "Muestra el rostro", "Dano: 4", ""},
    {3, "Susto Mortal", FX_ATTACK, 4, 0, 0, 0, "Muestra el rostro", "Dano: 4", ""},
    {4, "Perfume Barato", FX_ATTACK, 2, 0, 0, 0, "Aroma mareador", "Dano: 2", ""},
    {5, "Perfume Barato", FX_ATTACK, 2, 0, 0, 0, "Aroma mareador", "Dano: 2", ""},
    {6, "Perfume Barato", FX_ATTACK, 2, 0, 0, 0, "Aroma mareador", "Dano: 2", ""},
    {7, "Perfume Barato", FX_ATTACK, 2, 0, 0, 0, "Aroma mareador", "Dano: 2", ""},
    {8, "Velo de Viuda", FX_SHIELD, 0, 3, 0, 0, "Oculta su ser", "Escudo: 3", ""},
    {9, "Velo de Viuda", FX_SHIELD, 0, 3, 0, 0, "Oculta su ser", "Escudo: 3", ""},
    {10, "Velo de Viuda", FX_SHIELD, 0, 3, 0, 0, "Oculta su ser", "Escudo: 3", ""},
    {11, "Velo de Viuda", FX_SHIELD, 0, 3, 0, 0, "Oculta su ser", "Escudo: 3", ""},
    {12, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae victimas", "Roba:1 + Juega otra", ""},
    {13, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae victimas", "Roba:1 + Juega otra", ""},
    {14, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae victimas", "Roba:1 + Juega otra", ""},
    {15, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae victimas", "Roba:1 + Juega otra", ""},
    {16, "Beso Frío", FX_ATTACK | FX_HEAL, 3, 0, 2, 0, "Drena la vida", "Dano:3 Cura:2", ""},
    {17, "Beso Frío", FX_ATTACK | FX_HEAL, 3, 0, 2, 0, "Drena la vida", "Dano:3 Cura:2", ""},
    {18, "Beso Frío", FX_ATTACK | FX_HEAL, 3, 0, 2, 0, "Drena la vida", "Dano:3 Cura:2", ""},
    {19, "Beso Frío", FX_ATTACK | FX_HEAL, 3, 0, 2, 0, "Drena la vida", "Dano:3 Cura:2", ""},
    {20, "Ilusion", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aparece y desaparece", "Escudo:1 + Juega", ""},
    {21, "Ilusion", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aparece y desaparece", "Escudo:1 + Juega", ""},
    {22, "Ilusion", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aparece y desaparece", "Escudo:1 + Juega", ""},
    {23, "Ilusion", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aparece y desaparece", "Escudo:1 + Juega", ""},
    {24, "Rostro Calavera", FX_ATTACK | FX_DRAW, 5, 0, 0, 1, "Terror absoluto", "Dano:5 Roba:1", ""},
    {25, "Rostro Calavera", FX_ATTACK | FX_DRAW, 5, 0, 0, 1, "Terror absoluto", "Dano:5 Roba:1", ""},
    {26, "Rostro Calavera", FX_ATTACK | FX_DRAW, 5, 0, 0, 1, "Terror absoluto", "Dano:5 Roba:1", ""},
    {27, "Rostro Calavera", FX_ATTACK | FX_DRAW, 5, 0, 0, 1, "Terror absoluto", "Dano:5 Roba:1", ""},
};
const int DAMATAPADA_DECK_SIZE = 28;

// MAZO DE Maria Angula
const CardData CARTAS_MARIANGULA[] = {
    {0, "Robo de Tripas", FX_ATTACK, 5, 0, 0, 0, "Profana la tumba", "Dano: 5", ""},
    {1, "Robo de Tripas", FX_ATTACK, 5, 0, 0, 0, "Profana la tumba", "Dano: 5", ""},
    {2, "Robo de Tripas", FX_ATTACK, 5, 0, 0, 0, "Profana la tumba", "Dano: 5", ""},
    {3, "Robo de Tripas", FX_ATTACK, 5, 0, 0, 0, "Profana la tumba", "Dano: 5", ""},
    {4, "Panza Llena", FX_HEAL, 0, 0, 3, 0, "Come demasiado", "Cura: 3 HP", ""},
    {5, "Panza Llena", FX_HEAL, 0, 0, 3, 0, "Come demasiado", "Cura: 3 HP", ""},
    {6, "Panza Llena", FX_HEAL, 0, 0, 3, 0, "Come demasiado", "Cura: 3 HP", ""},
    {7, "Panza Llena", FX_HEAL, 0, 0, 3, 0, "Come demasiado", "Cura: 3 HP", ""},
    {8, "Sopa de Menudencias", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Cocina el mal", "Dano:2 + Juega otra", ""},
    {9, "Sopa de Menudencias", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Cocina el mal", "Dano:2 + Juega otra", ""},
    {10, "Sopa de Menudencias", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Cocina el mal", "Dano:2 + Juega otra", ""},
    {11, "Sopa de Menudencias", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Cocina el mal", "Dano:2 + Juega otra", ""},
    {12, "Sopa de Menudencias", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Cocina el mal", "Dano:2 + Juega otra", ""},
    {13, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 0, "Se esconde aterrorizada", "Escudo: 2", ""},
    {14, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 0, "Se esconde aterrorizada", "Escudo: 2", ""},
    {15, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 0, "Se esconde aterrorizada", "Escudo: 2", ""},
    {16, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 0, "Se esconde aterrorizada", "Escudo: 2", ""},
    {17, "Devuelveme mis tripas!", FX_ATTACK | FX_DRAW, 4, 0, 0, 1, "El muerto reclama", "Dano:4 Roba:1", ""},
    {18, "Devuelveme mis tripas!", FX_ATTACK | FX_DRAW, 4, 0, 0, 1, "El muerto reclama", "Dano:4 Roba:1", ""},
    {19, "Devuelveme mis tripas!", FX_ATTACK | FX_DRAW, 4, 0, 0, 1, "El muerto reclama", "Dano:4 Roba:1", ""},
    {20, "Devuelveme mis tripas!", FX_ATTACK | FX_DRAW, 4, 0, 0, 1, "El muerto reclama", "Dano:4 Roba:1", ""},
    {21, "Hambre Insaciable", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Quiere mas", "Roba:1 + Juega otra", ""},
    {22, "Hambre Insaciable", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Quiere mas", "Roba:1 + Juega otra", ""},
    {23, "Hambre Insaciable", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Quiere mas", "Roba:1 + Juega otra", ""},
    {24, "Hambre Insaciable", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Quiere mas", "Roba:1 + Juega otra", ""},
    {25, "Pesadilla", FX_ATTACK | FX_SHIELD, 3, 2, 0, 0, "El terror no la deja", "Dano:3 Escudo:2", ""},
    {26, "Pesadilla", FX_ATTACK | FX_SHIELD, 3, 2, 0, 0, "El terror no la deja", "Dano:3 Escudo:2", ""},
    {27, "Pesadilla", FX_ATTACK | FX_SHIELD, 3, 2, 0, 0, "El terror no la deja", "Dano:3 Escudo:2", ""},
};
const int MARIANGULA_DECK_SIZE = 28;

// MAZO DE Gallo Catedral
const CardData CARTAS_GALLO[] = {
    {0, "Picotazo", FX_ATTACK, 3, 0, 0, 0, "Pico de oro", "Dano: 3", ""},
    {1, "Picotazo", FX_ATTACK, 3, 0, 0, 0, "Pico de oro", "Dano: 3", ""},
    {2, "Picotazo", FX_ATTACK, 3, 0, 0, 0, "Pico de oro", "Dano: 3", ""},
    {3, "Picotazo", FX_ATTACK, 3, 0, 0, 0, "Pico de oro", "Dano: 3", ""},
    {4, "Picotazo", FX_ATTACK, 3, 0, 0, 0, "Pico de oro", "Dano: 3", ""},
    {5, "Canto Matutino", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Amanecer", "Cura:2 Roba:1", ""},
    {6, "Canto Matutino", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Amanecer", "Cura:2 Roba:1", ""},
    {7, "Canto Matutino", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Amanecer", "Cura:2 Roba:1", ""},
    {8, "Canto Matutino", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Amanecer", "Cura:2 Roba:1", ""},
    {9, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Escudo metalico", "Escudo: 3", ""},
    {10, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Escudo metalico", "Escudo: 3", ""},
    {11, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Escudo metalico", "Escudo: 3", ""},
    {12, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Escudo metalico", "Escudo: 3", ""},
    {13, "Vuelo Corto", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Esquiva todo", "Roba:1 + Juega otra", ""},
    {14, "Vuelo Corto", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Esquiva todo", "Roba:1 + Juega otra", ""},
    {15, "Vuelo Corto", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Esquiva todo", "Roba:1 + Juega otra", ""},
    {16, "Vuelo Corto", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Esquiva todo", "Roba:1 + Juega otra", ""},
    {17, "Grito Ensordecedor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Despierta a todos", "Dano:2 + Juega otra", ""},
    {18, "Grito Ensordecedor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Despierta a todos", "Dano:2 + Juega otra", ""},
    {19, "Grito Ensordecedor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Despierta a todos", "Dano:2 + Juega otra", ""},
    {20, "Grito Ensordecedor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Despierta a todos", "Dano:2 + Juega otra", ""},
    {21, "Estatua Posesa", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "Toma vida", "Dano:4 Escudo:2", ""},
    {22, "Estatua Posesa", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "Toma vida", "Dano:4 Escudo:2", ""},
    {23, "Estatua Posesa", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "Toma vida", "Dano:4 Escudo:2", ""},
    {24, "Estatua Posesa", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "Toma vida", "Dano:4 Escudo:2", ""},
    {25, "Pluma Dorada", FX_HEAL, 0, 0, 4, 0, "Brillo sanador", "Cura: 4 HP", ""},
    {26, "Pluma Dorada", FX_HEAL, 0, 0, 4, 0, "Brillo sanador", "Cura: 4 HP", ""},
    {27, "Pluma Dorada", FX_HEAL, 0, 0, 4, 0, "Brillo sanador", "Cura: 4 HP", ""},
};
const int GALLO_DECK_SIZE = 28;

// MAZO DE Cura sin Cabeza
const CardData CARTAS_CURA[] = {
    {0, "Llama Negra", FX_ATTACK, 6, 0, 0, 0, "Fuego del purgatorio", "Dano: 6", ""},
    {1, "Llama Negra", FX_ATTACK, 6, 0, 0, 0, "Fuego del purgatorio", "Dano: 6", ""},
    {2, "Llama Negra", FX_ATTACK, 6, 0, 0, 0, "Fuego del purgatorio", "Dano: 6", ""},
    {3, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Habla sin voz", "Dano:2 + Juega", ""},
    {4, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Habla sin voz", "Dano:2 + Juega", ""},
    {5, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Habla sin voz", "Dano:2 + Juega", ""},
    {6, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Habla sin voz", "Dano:2 + Juega", ""},
    {7, "Aparicion", FX_SHIELD, 0, 4, 0, 0, "No lo puedes tocar", "Escudo: 4", ""},
    {8, "Aparicion", FX_SHIELD, 0, 4, 0, 0, "No lo puedes tocar", "Escudo: 4", ""},
    {9, "Aparicion", FX_SHIELD, 0, 4, 0, 0, "No lo puedes tocar", "Escudo: 4", ""},
    {10, "Misa de Medianoche", FX_HEAL, 0, 0, 5, 0, "Ritual oscuro", "Cura: 5 HP", ""},
    {11, "Misa de Medianoche", FX_HEAL, 0, 0, 5, 0, "Ritual oscuro", "Cura: 5 HP", ""},
    {12, "Misa de Medianoche", FX_HEAL, 0, 0, 5, 0, "Ritual oscuro", "Cura: 5 HP", ""},
    {13, "Busqueda de Cabeza", FX_DRAW, 0, 0, 0, 3, "Roba muchas cartas", "Roba: 3 cartas", ""},
    {14, "Busqueda de Cabeza", FX_DRAW, 0, 0, 0, 3, "Roba muchas cartas", "Roba: 3 cartas", ""},
    {15, "Busqueda de Cabeza", FX_DRAW, 0, 0, 0, 3, "Roba muchas cartas", "Roba: 3 cartas", ""},
    {16, "Condena", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "El juicio final", "Dano:4 Escudo:2", ""},
    {17, "Condena", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "El juicio final", "Dano:4 Escudo:2", ""},
    {18, "Condena", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "El juicio final", "Dano:4 Escudo:2", ""},
    {19, "Condena", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "El juicio final", "Dano:4 Escudo:2", ""},
    {20, "Aura Espectral", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Espiritu inquieto", "Cura:2 Roba:1", ""},
    {21, "Aura Espectral", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Espiritu inquieto", "Cura:2 Roba:1", ""},
    {22, "Aura Espectral", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Espiritu inquieto", "Cura:2 Roba:1", ""},
    {23, "Aura Espectral", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Espiritu inquieto", "Cura:2 Roba:1", ""},
    {24, "Levitacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Flota", "Roba:1 + Juega otra", ""},
    {25, "Levitacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Flota", "Roba:1 + Juega otra", ""},
    {26, "Levitacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Flota", "Roba:1 + Juega otra", ""},
    {27, "Levitacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Flota", "Roba:1 + Juega otra", ""},
};
const int CURA_DECK_SIZE = 28;

// MAZO DE El Chuzalongo
const CardData CARTAS_CHUZALONGO[] = {
    {0, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde fuerte", "Dano: 5", ""},
    {1, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde fuerte", "Dano: 5", ""},
    {2, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde fuerte", "Dano: 5", ""},
    {3, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde fuerte", "Dano: 5", ""},
    {4, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde fuerte", "Dano: 5", ""},
    {5, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde fuerte", "Dano: 5", ""},
    {6, "Garras Paramo", FX_ATTACK, 4, 0, 0, 0, "Arana feo", "Dano: 4", ""},
    {7, "Garras Paramo", FX_ATTACK, 4, 0, 0, 0, "Arana feo", "Dano: 4", ""},
    {8, "Garras Paramo", FX_ATTACK, 4, 0, 0, 0, "Arana feo", "Dano: 4", ""},
    {9, "Garras Paramo", FX_ATTACK, 4, 0, 0, 0, "Arana feo", "Dano: 4", ""},
    {10, "Garras Paramo", FX_ATTACK, 4, 0, 0, 0, "Arana feo", "Dano: 4", ""},
    {11, "Piel Gruesa", FX_SHIELD, 0, 1, 0, 0, "Poco escudo", "Escudo: 1", ""},
    {12, "Piel Gruesa", FX_SHIELD, 0, 1, 0, 0, "Poco escudo", "Escudo: 1", ""},
    {13, "Piel Gruesa", FX_SHIELD, 0, 1, 0, 0, "Poco escudo", "Escudo: 1", ""},
    {14, "Instinto Animal", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Actua rapido", "Roba:1 + Juega otra", ""},
    {15, "Instinto Animal", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Actua rapido", "Roba:1 + Juega otra", ""},
    {16, "Instinto Animal", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Actua rapido", "Roba:1 + Juega otra", ""},
    {17, "Instinto Animal", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Actua rapido", "Roba:1 + Juega otra", ""},
    {18, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Golpea sin ver", "Dano:3 + Juega", ""},
    {19, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Golpea sin ver", "Dano:3 + Juega", ""},
    {20, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Golpea sin ver", "Dano:3 + Juega", ""},
    {21, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Golpea sin ver", "Dano:3 + Juega", ""},
    {22, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta", "Cura: 2 HP", ""},
    {23, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta", "Cura: 2 HP", ""},
    {24, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta", "Cura: 2 HP", ""},
    {25, "Aullido", FX_ATTACK | FX_DRAW, 4, 0, 0, 1, "Llama a la manada", "Dano:4 Roba:1", ""},
    {26, "Aullido", FX_ATTACK | FX_DRAW, 4, 0, 0, 1, "Llama a la manada", "Dano:4 Roba:1", ""},
    {27, "Aullido", FX_ATTACK | FX_DRAW, 4, 0, 0, 1, "Llama a la manada", "Dano:4 Roba:1", ""},
};
const int CHUZALONGO_DECK_SIZE = 28;

// MAZO DE La Llorona
const CardData CARTAS_LLORONA[] = {
    {0, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Grito agudo", "Dano: 3", ""},
    {1, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Grito agudo", "Dano: 3", ""},
    {2, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Grito agudo", "Dano: 3", ""},
    {3, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Grito agudo", "Dano: 3", ""},
    {4, "Llanto Incesante", FX_HEAL, 0, 0, 4, 0, "Llora y sana", "Cura: 4 HP", ""},
    {5, "Llanto Incesante", FX_HEAL, 0, 0, 4, 0, "Llora y sana", "Cura: 4 HP", ""},
    {6, "Llanto Incesante", FX_HEAL, 0, 0, 4, 0, "Llora y sana", "Cura: 4 HP", ""},
    {7, "Llanto Incesante", FX_HEAL, 0, 0, 4, 0, "Llora y sana", "Cura: 4 HP", ""},
    {8, "Llanto Incesante", FX_HEAL, 0, 0, 4, 0, "Llora y sana", "Cura: 4 HP", ""},
    {9, "Rio Desbordado", FX_ATTACK | FX_SHIELD, 3, 2, 0, 0, "Agua violenta", "Dano:3 Escudo:2", ""},
    {10, "Rio Desbordado", FX_ATTACK | FX_SHIELD, 3, 2, 0, 0, "Agua violenta", "Dano:3 Escudo:2", ""},
    {11, "Rio Desbordado", FX_ATTACK | FX_SHIELD, 3, 2, 0, 0, "Agua violenta", "Dano:3 Escudo:2", ""},
    {12, "Rio Desbordado", FX_ATTACK | FX_SHIELD, 3, 2, 0, 0, "Agua violenta", "Dano:3 Escudo:2", ""},
    {13, "Manto Blanco", FX_SHIELD, 0, 3, 0, 0, "Vestido espectral", "Escudo: 3", ""},
    {14, "Manto Blanco", FX_SHIELD, 0, 3, 0, 0, "Vestido espectral", "Escudo: 3", ""},
    {15, "Manto Blanco", FX_SHIELD, 0, 3, 0, 0, "Vestido espectral", "Escudo: 3", ""},
    {16, "Manto Blanco", FX_SHIELD, 0, 3, 0, 0, "Vestido espectral", "Escudo: 3", ""},
    {17, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Actua sin pensar", "Roba:1 + Juega", ""},
    {18, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Actua sin pensar", "Roba:1 + Juega", ""},
    {19, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Actua sin pensar", "Roba:1 + Juega", ""},
    {20, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Actua sin pensar", "Roba:1 + Juega", ""},
    {21, "Ahogo", FX_ATTACK | FX_HEAL, 4, 0, 2, 0, "Drena el oxigeno", "Dano:4 Cura:2", ""},
    {22, "Ahogo", FX_ATTACK | FX_HEAL, 4, 0, 2, 0, "Drena el oxigeno", "Dano:4 Cura:2", ""},
    {23, "Ahogo", FX_ATTACK | FX_HEAL, 4, 0, 2, 0, "Drena el oxigeno", "Dano:4 Cura:2", ""},
    {24, "Ahogo", FX_ATTACK | FX_HEAL, 4, 0, 2, 0, "Drena el oxigeno", "Dano:4 Cura:2", ""},
    {25, "Lágrimas", FX_DRAW, 0, 0, 0, 2, "Penas pasadas", "Roba: 2", ""},
    {26, "Lágrimas", FX_DRAW, 0, 0, 0, 2, "Penas pasadas", "Roba: 2", ""},
    {27, "Lágrimas", FX_DRAW, 0, 0, 0, 2, "Penas pasadas", "Roba: 2", ""},
};
const int LLORONA_DECK_SIZE = 28;

// MAZO DE Guagua Auca
const CardData CARTAS_GUAGUAAUCA[] = {
    {0, "Lloriqueo", FX_ATTACK, 2, 0, 0, 0, "Llora para enganar", "Dano: 2", ""},
    {1, "Lloriqueo", FX_ATTACK, 2, 0, 0, 0, "Llora para enganar", "Dano: 2", ""},
    {2, "Lloriqueo", FX_ATTACK, 2, 0, 0, 0, "Llora para enganar", "Dano: 2", ""},
    {3, "Lloriqueo", FX_ATTACK, 2, 0, 0, 0, "Llora para enganar", "Dano: 2", ""},
    {4, "Lloriqueo", FX_ATTACK, 2, 0, 0, 0, "Llora para enganar", "Dano: 2", ""},
    {5, "Dientes de Diablo", FX_ATTACK, 5, 0, 0, 0, "Muerde cuando lo abrazan", "Dano: 5", ""},
    {6, "Dientes de Diablo", FX_ATTACK, 5, 0, 0, 0, "Muerde cuando lo abrazan", "Dano: 5", ""},
    {7, "Dientes de Diablo", FX_ATTACK, 5, 0, 0, 0, "Muerde cuando lo abrazan", "Dano: 5", ""},
    {8, "Dientes de Diablo", FX_ATTACK, 5, 0, 0, 0, "Muerde cuando lo abrazan", "Dano: 5", ""},
    {9, "Panales", FX_SHIELD, 0, 2, 0, 0, "Parece inofensivo", "Escudo: 2", ""},
    {10, "Panales", FX_SHIELD, 0, 2, 0, 0, "Parece inofensivo", "Escudo: 2", ""},
    {11, "Panales", FX_SHIELD, 0, 2, 0, 0, "Parece inofensivo", "Escudo: 2", ""},
    {12, "Panales", FX_SHIELD, 0, 2, 0, 0, "Parece inofensivo", "Escudo: 2", ""},
    {13, "Sorpresa Maligna", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Susto", "Dano:3 + Juega", ""},
    {14, "Sorpresa Maligna", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Susto", "Dano:3 + Juega", ""},
    {15, "Sorpresa Maligna", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Susto", "Dano:3 + Juega", ""},
    {16, "Sorpresa Maligna", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Susto", "Dano:3 + Juega", ""},
    {17, "Sorpresa Maligna", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Susto", "Dano:3 + Juega", ""},
    {18, "Risa Macabra", FX_DRAW, 0, 0, 0, 2, "Se burla", "Roba: 2", ""},
    {19, "Risa Macabra", FX_DRAW, 0, 0, 0, 2, "Se burla", "Roba: 2", ""},
    {20, "Risa Macabra", FX_DRAW, 0, 0, 0, 2, "Se burla", "Roba: 2", ""},
    {21, "Risa Macabra", FX_DRAW, 0, 0, 0, 2, "Se burla", "Roba: 2", ""},
    {22, "Inocencia Fingida", FX_HEAL | FX_DRAW, 0, 0, 3, 1, "Te da pena", "Cura:3 Roba:1", ""},
    {23, "Inocencia Fingida", FX_HEAL | FX_DRAW, 0, 0, 3, 1, "Te da pena", "Cura:3 Roba:1", ""},
    {24, "Inocencia Fingida", FX_HEAL | FX_DRAW, 0, 0, 3, 1, "Te da pena", "Cura:3 Roba:1", ""},
    {25, "Inocencia Fingida", FX_HEAL | FX_DRAW, 0, 0, 3, 1, "Te da pena", "Cura:3 Roba:1", ""},
    {26, "Mordisco", FX_ATTACK | FX_SHIELD, 2, 2, 0, 0, "Golpea de cerca", "Dano:2 Escudo:2", ""},
    {27, "Mordisco", FX_ATTACK | FX_SHIELD, 2, 2, 0, 0, "Golpea de cerca", "Dano:2 Escudo:2", ""},
};
const int GUAGUAAUCA_DECK_SIZE = 28;

// MAZO DE Viuda Tamarindo
const CardData CARTAS_VIUDA[] = {
    {0, "Seduccion Oscura", FX_ATTACK | FX_HEAL, 4, 0, 3, 0, "Te enamora y te mata", "Dano:4 Cura:3", ""},
    {1, "Seduccion Oscura", FX_ATTACK | FX_HEAL, 4, 0, 3, 0, "Te enamora y te mata", "Dano:4 Cura:3", ""},
    {2, "Seduccion Oscura", FX_ATTACK | FX_HEAL, 4, 0, 3, 0, "Te enamora y te mata", "Dano:4 Cura:3", ""},
    {3, "Seduccion Oscura", FX_ATTACK | FX_HEAL, 4, 0, 3, 0, "Te enamora y te mata", "Dano:4 Cura:3", ""},
    {4, "Abrazo de Muerte", FX_ATTACK, 5, 0, 0, 0, "Te asfixia", "Dano: 5", ""},
    {5, "Abrazo de Muerte", FX_ATTACK, 5, 0, 0, 0, "Te asfixia", "Dano: 5", ""},
    {6, "Abrazo de Muerte", FX_ATTACK, 5, 0, 0, 0, "Te asfixia", "Dano: 5", ""},
    {7, "Abrazo de Muerte", FX_ATTACK, 5, 0, 0, 0, "Te asfixia", "Dano: 5", ""},
    {8, "Sombra del Arbol", FX_SHIELD, 0, 4, 0, 0, "El tamarindo la protege", "Escudo: 4", ""},
    {9, "Sombra del Arbol", FX_SHIELD, 0, 4, 0, 0, "El tamarindo la protege", "Escudo: 4", ""},
    {10, "Sombra del Arbol", FX_SHIELD, 0, 4, 0, 0, "El tamarindo la protege", "Escudo: 4", ""},
    {11, "Sombra del Arbol", FX_SHIELD, 0, 4, 0, 0, "El tamarindo la protege", "Escudo: 4", ""},
    {12, "Velo Negro", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Magia negra", "Roba:1 + Juega", ""},
    {13, "Velo Negro", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Magia negra", "Roba:1 + Juega", ""},
    {14, "Velo Negro", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Magia negra", "Roba:1 + Juega", ""},
    {15, "Velo Negro", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Magia negra", "Roba:1 + Juega", ""},
    {16, "Borracho Perdido", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Engana a sus victimas", "Dano:2 + Juega", ""},
    {17, "Borracho Perdido", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Engana a sus victimas", "Dano:2 + Juega", ""},
    {18, "Borracho Perdido", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Engana a sus victimas", "Dano:2 + Juega", ""},
    {19, "Borracho Perdido", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Engana a sus victimas", "Dano:2 + Juega", ""},
    {20, "Pasion Falsa", FX_HEAL, 0, 0, 5, 0, "Beso curativo", "Cura: 5", ""},
    {21, "Pasion Falsa", FX_HEAL, 0, 0, 5, 0, "Beso curativo", "Cura: 5", ""},
    {22, "Pasion Falsa", FX_HEAL, 0, 0, 5, 0, "Beso curativo", "Cura: 5", ""},
    {23, "Pasion Falsa", FX_HEAL, 0, 0, 5, 0, "Beso curativo", "Cura: 5", ""},
    {24, "Aroma Dulce", FX_DRAW, 0, 0, 0, 2, "Atrae a incautos", "Roba: 2", ""},
    {25, "Aroma Dulce", FX_DRAW, 0, 0, 0, 2, "Atrae a incautos", "Roba: 2", ""},
    {26, "Aroma Dulce", FX_DRAW, 0, 0, 0, 2, "Atrae a incautos", "Roba: 2", ""},
    {27, "Aroma Dulce", FX_DRAW, 0, 0, 0, 2, "Atrae a incautos", "Roba: 2", ""},
};
const int VIUDA_DECK_SIZE = 28;

