#include "card.h"

// MAZO DE Cantuna
const CardData CARTAS_CANTUNA[] = {
    {0, "Ladrillazo", FX_ATTACK, 3, 0, 0, 0, "Arroja un ladrillo frio", "de la iglesia matriz.", "[Dano: 3]"},
    {1, "Ladrillazo", FX_ATTACK, 3, 0, 0, 0, "Arroja un ladrillo frio", "de la iglesia matriz.", "[Dano: 3]"},
    {2, "Ladrillazo", FX_ATTACK, 3, 0, 0, 0, "Arroja un ladrillo frio", "de la iglesia matriz.", "[Dano: 3]"},
    {3, "Golpe de Piedra", FX_ATTACK, 2, 0, 0, 0, "Un bloque tallado a mano,", "pesado como sus pecados.", "[Dano: 2]"},
    {4, "Golpe de Piedra", FX_ATTACK, 2, 0, 0, 0, "Un bloque tallado a mano,", "pesado como sus pecados.", "[Dano: 2]"},
    {5, "Golpe de Piedra", FX_ATTACK, 2, 0, 0, 0, "Un bloque tallado a mano,", "pesado como sus pecados.", "[Dano: 2]"},
    {6, "Avalancha", FX_ATTACK, 5, 0, 0, 0, "Invoca la ira del Pichincha", "sobre sus enemigos.", "[Dano: 5]"},
    {7, "Avalancha", FX_ATTACK, 5, 0, 0, 0, "Invoca la ira del Pichincha", "sobre sus enemigos.", "[Dano: 5]"},
    {8, "Muro de Piedra", FX_SHIELD, 0, 2, 0, 0, "Alza una pared divina", "que resiste los golpes.", "[Escudo: 2]"},
    {9, "Muro de Piedra", FX_SHIELD, 0, 2, 0, 0, "Alza una pared divina", "que resiste los golpes.", "[Escudo: 2]"},
    {10, "Muro de Piedra", FX_SHIELD, 0, 2, 0, 0, "Alza una pared divina", "que resiste los golpes.", "[Escudo: 2]"},
    {11, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Un pilar indestructible;", "ni el diablo puede pasar.", "[Escudo: 3]"},
    {12, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Un pilar indestructible;", "ni el diablo puede pasar.", "[Escudo: 3]"},
    {13, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Un pilar indestructible;", "ni el diablo puede pasar.", "[Escudo: 3]"},
    {14, "Descanso", FX_HEAL, 0, 0, 2, 0, "Cierra los ojos un momento", "antes del amanecer.", "[Cura: 2 HP]"},
    {15, "Descanso", FX_HEAL, 0, 0, 2, 0, "Cierra los ojos un momento", "antes del amanecer.", "[Cura: 2 HP]"},
    {16, "Pacto Diabolico", FX_HEAL, 0, 0, 4, 0, "Firma con sangre para", "recuperar su vitalidad.", "[Cura: 4 HP]"},
    {17, "Pacto Diabolico", FX_HEAL, 0, 0, 4, 0, "Firma con sangre para", "recuperar su vitalidad.", "[Cura: 4 HP]"},
    {18, "Planos Secretos", FX_DRAW, 0, 0, 0, 2, "Saca un pergamino antiguo", "con nuevas estrategias.", "[Roba: 2]"},
    {19, "Planos Secretos", FX_DRAW, 0, 0, 0, 2, "Saca un pergamino antiguo", "con nuevas estrategias.", "[Roba: 2]"},
    {20, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Una chispa de ingenio", "le permite actuar rapido.", "[Roba: 1] [+ Juega otra]"},
    {21, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Una chispa de ingenio", "le permite actuar rapido.", "[Roba: 1] [+ Juega otra]"},
    {22, "Contraataque", FX_ATTACK | FX_SHIELD, 2, 1, 0, 0, "Se cubre con su mazo", "y devuelve el golpe.", "[Dano: 2] [Escudo: 1]"},
    {23, "Contraataque", FX_ATTACK | FX_SHIELD, 2, 1, 0, 0, "Se cubre con su mazo", "y devuelve el golpe.", "[Dano: 2] [Escudo: 1]"},
    {24, "Furia Constructor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Trabaja sin descanso,", "atacando repetidas veces.", "[Dano: 2] [+ Juega otra]"},
    {25, "Furia Constructor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Trabaja sin descanso,", "atacando repetidas veces.", "[Dano: 2] [+ Juega otra]"},
    {26, "Bendicion Oscura", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "El trato trae beneficios", "ocultos en la penumbra.", "[Cura: 2] [Roba: 1]"},
    {27, "Bendicion Oscura", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "El trato trae beneficios", "ocultos en la penumbra.", "[Cura: 2] [Roba: 1]"},
};
const int CANTUNA_DECK_SIZE = 28;

// MAZO DE El Tin Tin
const CardData CARTAS_TINTIN[] = {
    {0, "Travesura", FX_ATTACK, 2, 0, 0, 0, "Tira de tu cabello", "cuando no estas viendo.", "[Dano: 2]"},
    {1, "Travesura", FX_ATTACK, 2, 0, 0, 0, "Tira de tu cabello", "cuando no estas viendo.", "[Dano: 2]"},
    {2, "Travesura", FX_ATTACK, 2, 0, 0, 0, "Tira de tu cabello", "cuando no estas viendo.", "[Dano: 2]"},
    {3, "Travesura", FX_ATTACK, 2, 0, 0, 0, "Tira de tu cabello", "cuando no estas viendo.", "[Dano: 2]"},
    {4, "Sombrerazo", FX_ATTACK, 3, 0, 0, 0, "Usa su enorme sombrero", "para golpear con fuerza.", "[Dano: 3]"},
    {5, "Sombrerazo", FX_ATTACK, 3, 0, 0, 0, "Usa su enorme sombrero", "para golpear con fuerza.", "[Dano: 3]"},
    {6, "Sombrerazo", FX_ATTACK, 3, 0, 0, 0, "Usa su enorme sombrero", "para golpear con fuerza.", "[Dano: 3]"},
    {7, "Emboscada", FX_ATTACK, 4, 0, 0, 0, "Cae desde las ramas", "directo sobre su presa.", "[Dano: 4]"},
    {8, "Emboscada", FX_ATTACK, 4, 0, 0, 0, "Cae desde las ramas", "directo sobre su presa.", "[Dano: 4]"},
    {9, "Emboscada", FX_ATTACK, 4, 0, 0, 0, "Cae desde las ramas", "directo sobre su presa.", "[Dano: 4]"},
    {10, "Escondite", FX_SHIELD, 0, 1, 0, 0, "Se oculta rapidamente", "en la maleza.", "[Escudo: 1]"},
    {11, "Escondite", FX_SHIELD, 0, 1, 0, 0, "Se oculta rapidamente", "en la maleza.", "[Escudo: 1]"},
    {12, "Escondite", FX_SHIELD, 0, 1, 0, 0, "Se oculta rapidamente", "en la maleza.", "[Escudo: 1]"},
    {13, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Descansa un rato para", "planear otra diablura.", "[Cura: 2 HP]"},
    {14, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Descansa un rato para", "planear otra diablura.", "[Cura: 2 HP]"},
    {15, "Robo de Bolsillos", FX_DRAW, 0, 0, 0, 2, "Manos tan rapidas que", "ni sientes que te roba.", "[Roba: 2]"},
    {16, "Robo de Bolsillos", FX_DRAW, 0, 0, 0, 2, "Manos tan rapidas que", "ni sientes que te roba.", "[Roba: 2]"},
    {17, "Robo de Bolsillos", FX_DRAW, 0, 0, 0, 2, "Manos tan rapidas que", "ni sientes que te roba.", "[Roba: 2]"},
    {18, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los aires", "burlando toda defensa.", "[Roba: 1] [+ Juega otra]"},
    {19, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los aires", "burlando toda defensa.", "[Roba: 1] [+ Juega otra]"},
    {20, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los aires", "burlando toda defensa.", "[Roba: 1] [+ Juega otra]"},
    {21, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los aires", "burlando toda defensa.", "[Roba: 1] [+ Juega otra]"},
    {22, "Golpe Fugaz", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Pega y desaparece en", "un parpadeo.", "[Dano: 2] [+ Juega otra]"},
    {23, "Golpe Fugaz", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Pega y desaparece en", "un parpadeo.", "[Dano: 2] [+ Juega otra]"},
    {24, "Golpe Fugaz", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Pega y desaparece en", "un parpadeo.", "[Dano: 2] [+ Juega otra]"},
    {25, "Ataque Sorpresa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1, "Un golpe por la espalda", "que te deja aturdido.", "[Dano: 3] [Roba: 1]"},
    {26, "Ataque Sorpresa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1, "Un golpe por la espalda", "que te deja aturdido.", "[Dano: 3] [Roba: 1]"},
    {27, "Ataque Sorpresa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1, "Un golpe por la espalda", "que te deja aturdido.", "[Dano: 3] [Roba: 1]"},
};
const int TINTIN_DECK_SIZE = 28;

// MAZO DE La Tunda
const CardData CARTAS_TUNDA[] = {
    {0, "Zarpazo", FX_ATTACK, 3, 0, 0, 0, "Su mano retorcida", "desgarra la piel.", "[Dano: 3]"},
    {1, "Zarpazo", FX_ATTACK, 3, 0, 0, 0, "Su mano retorcida", "desgarra la piel.", "[Dano: 3]"},
    {2, "Zarpazo", FX_ATTACK, 3, 0, 0, 0, "Su mano retorcida", "desgarra la piel.", "[Dano: 3]"},
    {3, "Molinillazo", FX_ATTACK, 4, 0, 0, 0, "Patea con su pesada", "pierna de madera.", "[Dano: 4]"},
    {4, "Molinillazo", FX_ATTACK, 4, 0, 0, 0, "Patea con su pesada", "pierna de madera.", "[Dano: 4]"},
    {5, "Molinillazo", FX_ATTACK, 4, 0, 0, 0, "Patea con su pesada", "pierna de madera.", "[Dano: 4]"},
    {6, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0, "El manglar se cierra,", "ocultandola por completo.", "[Escudo: 2]"},
    {7, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0, "El manglar se cierra,", "ocultandola por completo.", "[Escudo: 2]"},
    {8, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0, "El manglar se cierra,", "ocultandola por completo.", "[Escudo: 2]"},
    {9, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0, "El manglar se cierra,", "ocultandola por completo.", "[Escudo: 2]"},
    {10, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado embrujado", "que restaura su vigor.", "[Cura: 2 HP]"},
    {11, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado embrujado", "que restaura su vigor.", "[Cura: 2 HP]"},
    {12, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado embrujado", "que restaura su vigor.", "[Cura: 2 HP]"},
    {13, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado embrujado", "que restaura su vigor.", "[Cura: 2 HP]"},
    {14, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0, "Cantos antiguos curan", "sus viejas heridas.", "[Cura: 4 HP]"},
    {15, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0, "Cantos antiguos curan", "sus viejas heridas.", "[Cura: 4 HP]"},
    {16, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0, "Cantos antiguos curan", "sus viejas heridas.", "[Cura: 4 HP]"},
    {17, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0, "Cantos antiguos curan", "sus viejas heridas.", "[Cura: 4 HP]"},
    {18, "Susurros", FX_DRAW, 0, 0, 0, 2, "Voces en la niebla que", "revelan secretos oscuros.", "[Roba: 2]"},
    {19, "Susurros", FX_DRAW, 0, 0, 0, 2, "Voces en la niebla que", "revelan secretos oscuros.", "[Roba: 2]"},
    {20, "Encantamiento", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Hipnotiza al rival para", "ganar mas tiempo.", "[Roba: 1] [+ Juega otra]"},
    {21, "Encantamiento", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Hipnotiza al rival para", "ganar mas tiempo.", "[Roba: 1] [+ Juega otra]"},
    {22, "Drenar Vida", FX_ATTACK | FX_HEAL, 2, 0, 2, 0, "Absorbe tu esencia", "para fortalecerse ella.", "[Dano: 2] [Cura: 2]"},
    {23, "Drenar Vida", FX_ATTACK | FX_HEAL, 2, 0, 2, 0, "Absorbe tu esencia", "para fortalecerse ella.", "[Dano: 2] [Cura: 2]"},
    {24, "Drenar Vida", FX_ATTACK | FX_HEAL, 2, 0, 2, 0, "Absorbe tu esencia", "para fortalecerse ella.", "[Dano: 2] [Cura: 2]"},
    {25, "Maldicion", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0, "Un maleficio que lastima", "y a la vez protege.", "[Dano: 3] [Escudo: 1]"},
    {26, "Maldicion", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0, "Un maleficio que lastima", "y a la vez protege.", "[Dano: 3] [Escudo: 1]"},
    {27, "Maldicion", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0, "Un maleficio que lastima", "y a la vez protege.", "[Dano: 3] [Escudo: 1]"},
};
const int TUNDA_DECK_SIZE = 28;

// MAZO DE Padre Almeida
const CardData CARTAS_ALMEIDA[] = {
    {0, "Guitarrazo", FX_ATTACK, 3, 0, 0, 0, "Un golpe sonoro con", "su vieja guitarra.", "[Dano: 3]"},
    {1, "Guitarrazo", FX_ATTACK, 3, 0, 0, 0, "Un golpe sonoro con", "su vieja guitarra.", "[Dano: 3]"},
    {2, "Guitarrazo", FX_ATTACK, 3, 0, 0, 0, "Un golpe sonoro con", "su vieja guitarra.", "[Dano: 3]"},
    {3, "Guitarrazo", FX_ATTACK, 3, 0, 0, 0, "Un golpe sonoro con", "su vieja guitarra.", "[Dano: 3]"},
    {4, "Botellazo", FX_ATTACK, 4, 0, 0, 0, "Vuela una botella vacia", "directo a la cabeza.", "[Dano: 4]"},
    {5, "Botellazo", FX_ATTACK, 4, 0, 0, 0, "Vuela una botella vacia", "directo a la cabeza.", "[Dano: 4]"},
    {6, "Botellazo", FX_ATTACK, 4, 0, 0, 0, "Vuela una botella vacia", "directo a la cabeza.", "[Dano: 4]"},
    {7, "Sotana", FX_SHIELD, 0, 2, 0, 0, "La tela sagrada lo", "protege de los danos.", "[Escudo: 2]"},
    {8, "Sotana", FX_SHIELD, 0, 2, 0, 0, "La tela sagrada lo", "protege de los danos.", "[Escudo: 2]"},
    {9, "Sotana", FX_SHIELD, 0, 2, 0, 0, "La tela sagrada lo", "protege de los danos.", "[Escudo: 2]"},
    {10, "Trago Bendito", FX_HEAL, 0, 0, 3, 0, "Un buen sorbo para", "olvidar las penas.", "[Cura: 3 HP]"},
    {11, "Trago Bendito", FX_HEAL, 0, 0, 3, 0, "Un buen sorbo para", "olvidar las penas.", "[Cura: 3 HP]"},
    {12, "Trago Bendito", FX_HEAL, 0, 0, 3, 0, "Un buen sorbo para", "olvidar las penas.", "[Cura: 3 HP]"},
    {13, "Salida Secreta", FX_DRAW, 0, 0, 0, 3, "Conoce todos los atajos", "para escapar del convento.", "[Roba: 3]"},
    {14, "Salida Secreta", FX_DRAW, 0, 0, 0, 3, "Conoce todos los atajos", "para escapar del convento.", "[Roba: 3]"},
    {15, "Salida Secreta", FX_DRAW, 0, 0, 0, 3, "Conoce todos los atajos", "para escapar del convento.", "[Roba: 3]"},
    {16, "Escape", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Pisa el Cristo y sale", "corriendo a la calle.", "[Roba: 1] [+ Juega otra]"},
    {17, "Escape", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Pisa el Cristo y sale", "corriendo a la calle.", "[Roba: 1] [+ Juega otra]"},
    {18, "Escape", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Pisa el Cristo y sale", "corriendo a la calle.", "[Roba: 1] [+ Juega otra]"},
    {19, "Escape", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Pisa el Cristo y sale", "corriendo a la calle.", "[Roba: 1] [+ Juega otra]"},
    {20, "Escape", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Pisa el Cristo y sale", "corriendo a la calle.", "[Roba: 1] [+ Juega otra]"},
    {21, "Farra", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Sigue la fiesta con", "golpes impredecibles.", "[Dano: 2] [+ Juega otra]"},
    {22, "Farra", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Sigue la fiesta con", "golpes impredecibles.", "[Dano: 2] [+ Juega otra]"},
    {23, "Farra", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Sigue la fiesta con", "golpes impredecibles.", "[Dano: 2] [+ Juega otra]"},
    {24, "Farra", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Sigue la fiesta con", "golpes impredecibles.", "[Dano: 2] [+ Juega otra]"},
    {25, "Resaca", FX_HEAL | FX_DRAW, 0, 0, 1, 1, "Bebe agua y planea", "su proxima escapada.", "[Cura: 1] [Roba: 1]"},
    {26, "Resaca", FX_HEAL | FX_DRAW, 0, 0, 1, 1, "Bebe agua y planea", "su proxima escapada.", "[Cura: 1] [Roba: 1]"},
    {27, "Resaca", FX_HEAL | FX_DRAW, 0, 0, 1, 1, "Bebe agua y planea", "su proxima escapada.", "[Cura: 1] [Roba: 1]"},
};
const int ALMEIDA_DECK_SIZE = 28;

// MAZO DE Dama Tapada
const CardData CARTAS_DAMATAPADA[] = {
    {0, "Aroma Seductor", FX_DRAW, 0, 0, 0, 2, "Un perfume floral que", "atrae a sus victimas.", "[Roba: 2]"},
    {1, "Aroma Seductor", FX_DRAW, 0, 0, 0, 2, "Un perfume floral que", "atrae a sus victimas.", "[Roba: 2]"},
    {2, "Aroma Seductor", FX_DRAW, 0, 0, 0, 2, "Un perfume floral que", "atrae a sus victimas.", "[Roba: 2]"},
    {3, "Aroma Seductor", FX_DRAW, 0, 0, 0, 2, "Un perfume floral que", "atrae a sus victimas.", "[Roba: 2]"},
    {4, "Mirada Paralizante", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Los ojos del abismo", "te dejan de piedra.", "[Dano: 2] [+ Juega otra]"},
    {5, "Mirada Paralizante", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Los ojos del abismo", "te dejan de piedra.", "[Dano: 2] [+ Juega otra]"},
    {6, "Mirada Paralizante", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Los ojos del abismo", "te dejan de piedra.", "[Dano: 2] [+ Juega otra]"},
    {7, "Mirada Paralizante", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Los ojos del abismo", "te dejan de piedra.", "[Dano: 2] [+ Juega otra]"},
    {8, "Mirada Paralizante", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Los ojos del abismo", "te dejan de piedra.", "[Dano: 2] [+ Juega otra]"},
    {9, "Rostro Esqueletico", FX_ATTACK, 5, 0, 0, 0, "Se quita el velo;", "el horror es total.", "[Dano: 5]"},
    {10, "Rostro Esqueletico", FX_ATTACK, 5, 0, 0, 0, "Se quita el velo;", "el horror es total.", "[Dano: 5]"},
    {11, "Rostro Esqueletico", FX_ATTACK, 5, 0, 0, 0, "Se quita el velo;", "el horror es total.", "[Dano: 5]"},
    {12, "Rostro Esqueletico", FX_ATTACK, 5, 0, 0, 0, "Se quita el velo;", "el horror es total.", "[Dano: 5]"},
    {13, "Grito Aterrador", FX_ATTACK, 3, 0, 0, 0, "Un chillido agudo que", "hiela la sangre.", "[Dano: 3]"},
    {14, "Grito Aterrador", FX_ATTACK, 3, 0, 0, 0, "Un chillido agudo que", "hiela la sangre.", "[Dano: 3]"},
    {15, "Grito Aterrador", FX_ATTACK, 3, 0, 0, 0, "Un chillido agudo que", "hiela la sangre.", "[Dano: 3]"},
    {16, "Grito Aterrador", FX_ATTACK, 3, 0, 0, 0, "Un chillido agudo que", "hiela la sangre.", "[Dano: 3]"},
    {17, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil golpearla.", "[Escudo: 3]"},
    {18, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil golpearla.", "[Escudo: 3]"},
    {19, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil golpearla.", "[Escudo: 3]"},
    {20, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil golpearla.", "[Escudo: 3]"},
    {21, "Bruma Fria", FX_SHIELD, 0, 2, 0, 0, "Una niebla oscura", "amortigua los golpes.", "[Escudo: 2]"},
    {22, "Bruma Fria", FX_SHIELD, 0, 2, 0, 0, "Una niebla oscura", "amortigua los golpes.", "[Escudo: 2]"},
    {23, "Bruma Fria", FX_SHIELD, 0, 2, 0, 0, "Una niebla oscura", "amortigua los golpes.", "[Escudo: 2]"},
    {24, "Bruma Fria", FX_SHIELD, 0, 2, 0, 0, "Una niebla oscura", "amortigua los golpes.", "[Escudo: 2]"},
    {25, "Miedo Profundo", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "El panico crece", "mientras se acerca.", "[Roba: 1] [+ Juega otra]"},
    {26, "Miedo Profundo", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "El panico crece", "mientras se acerca.", "[Roba: 1] [+ Juega otra]"},
    {27, "Miedo Profundo", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "El panico crece", "mientras se acerca.", "[Roba: 1] [+ Juega otra]"},
};
const int DAMATAPADA_DECK_SIZE = 28;

// MAZO DE Maria Angula
const CardData CARTAS_MARIANGULA[] = {
    {0, "Olla Caliente", FX_ATTACK, 4, 0, 0, 0, "Lanza caldo hirviendo", "sin pensarlo dos veces.", "[Dano: 4]"},
    {1, "Olla Caliente", FX_ATTACK, 4, 0, 0, 0, "Lanza caldo hirviendo", "sin pensarlo dos veces.", "[Dano: 4]"},
    {2, "Olla Caliente", FX_ATTACK, 4, 0, 0, 0, "Lanza caldo hirviendo", "sin pensarlo dos veces.", "[Dano: 4]"},
    {3, "Olla Caliente", FX_ATTACK, 4, 0, 0, 0, "Lanza caldo hirviendo", "sin pensarlo dos veces.", "[Dano: 4]"},
    {4, "Cuchillazo", FX_ATTACK, 3, 0, 0, 0, "Un corte rapido y", "desesperado.", "[Dano: 3]"},
    {5, "Cuchillazo", FX_ATTACK, 3, 0, 0, 0, "Un corte rapido y", "desesperado.", "[Dano: 3]"},
    {6, "Cuchillazo", FX_ATTACK, 3, 0, 0, 0, "Un corte rapido y", "desesperado.", "[Dano: 3]"},
    {7, "Cuchillazo", FX_ATTACK, 3, 0, 0, 0, "Un corte rapido y", "desesperado.", "[Dano: 3]"},
    {8, "Cuchillazo", FX_ATTACK, 3, 0, 0, 0, "Un corte rapido y", "desesperado.", "[Dano: 3]"},
    {9, "Panico", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Corre despavorida", "al escuchar los pasos.", "[Roba: 1] [+ Juega otra]"},
    {10, "Panico", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Corre despavorida", "al escuchar los pasos.", "[Roba: 1] [+ Juega otra]"},
    {11, "Panico", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Corre despavorida", "al escuchar los pasos.", "[Roba: 1] [+ Juega otra]"},
    {12, "Panico", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Corre despavorida", "al escuchar los pasos.", "[Roba: 1] [+ Juega otra]"},
    {13, "Panico", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Corre despavorida", "al escuchar los pasos.", "[Roba: 1] [+ Juega otra]"},
    {14, "Tijeras", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Corta todo lo que", "se le cruza en frente.", "[Dano: 2] [+ Juega otra]"},
    {15, "Tijeras", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Corta todo lo que", "se le cruza en frente.", "[Dano: 2] [+ Juega otra]"},
    {16, "Tijeras", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Corta todo lo que", "se le cruza en frente.", "[Dano: 2] [+ Juega otra]"},
    {17, "Tijeras", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Corta todo lo que", "se le cruza en frente.", "[Dano: 2] [+ Juega otra]"},
    {18, "Sopa de Tripas", FX_HEAL, 0, 0, 3, 0, "Un banquete macabro", "que restaura energia.", "[Cura: 3 HP]"},
    {19, "Sopa de Tripas", FX_HEAL, 0, 0, 3, 0, "Un banquete macabro", "que restaura energia.", "[Cura: 3 HP]"},
    {20, "Sopa de Tripas", FX_HEAL, 0, 0, 3, 0, "Un banquete macabro", "que restaura energia.", "[Cura: 3 HP]"},
    {21, "Grito de Culpa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1, "Su llanto aterra y", "le da nuevas ideas.", "[Dano: 3] [Roba: 1]"},
    {22, "Grito de Culpa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1, "Su llanto aterra y", "le da nuevas ideas.", "[Dano: 3] [Roba: 1]"},
    {23, "Grito de Culpa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1, "Su llanto aterra y", "le da nuevas ideas.", "[Dano: 3] [Roba: 1]"},
    {24, "Grito de Culpa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1, "Su llanto aterra y", "le da nuevas ideas.", "[Dano: 3] [Roba: 1]"},
    {25, "Escondite", FX_SHIELD, 0, 2, 0, 0, "Se esconde bajo", "las mantas temblando.", "[Escudo: 2]"},
    {26, "Escondite", FX_SHIELD, 0, 2, 0, 0, "Se esconde bajo", "las mantas temblando.", "[Escudo: 2]"},
    {27, "Escondite", FX_SHIELD, 0, 2, 0, 0, "Se esconde bajo", "las mantas temblando.", "[Escudo: 2]"},
};
const int MARIANGULA_DECK_SIZE = 28;

// MAZO DE Gallo Catedral
const CardData CARTAS_GALLO[] = {
    {0, "Picotazo", FX_ATTACK, 3, 0, 0, 0, "El pico de bronce", "penetra la armadura.", "[Dano: 3]"},
    {1, "Picotazo", FX_ATTACK, 3, 0, 0, 0, "El pico de bronce", "penetra la armadura.", "[Dano: 3]"},
    {2, "Picotazo", FX_ATTACK, 3, 0, 0, 0, "El pico de bronce", "penetra la armadura.", "[Dano: 3]"},
    {3, "Picotazo", FX_ATTACK, 3, 0, 0, 0, "El pico de bronce", "penetra la armadura.", "[Dano: 3]"},
    {4, "Picotazo", FX_ATTACK, 3, 0, 0, 0, "El pico de bronce", "penetra la armadura.", "[Dano: 3]"},
    {5, "Espolon", FX_ATTACK, 4, 0, 0, 0, "Un corte profundo", "con sus garras afiladas.", "[Dano: 4]"},
    {6, "Espolon", FX_ATTACK, 4, 0, 0, 0, "Un corte profundo", "con sus garras afiladas.", "[Dano: 4]"},
    {7, "Espolon", FX_ATTACK, 4, 0, 0, 0, "Un corte profundo", "con sus garras afiladas.", "[Dano: 4]"},
    {8, "Canto Matutino", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Anuncia el amanecer,", "renovando su fuerza.", "[Cura: 2] [Roba: 1]"},
    {9, "Canto Matutino", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Anuncia el amanecer,", "renovando su fuerza.", "[Cura: 2] [Roba: 1]"},
    {10, "Canto Matutino", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Anuncia el amanecer,", "renovando su fuerza.", "[Cura: 2] [Roba: 1]"},
    {11, "Canto Matutino", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Anuncia el amanecer,", "renovando su fuerza.", "[Cura: 2] [Roba: 1]"},
    {12, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de metal", "rechaza los impactos.", "[Escudo: 3]"},
    {13, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de metal", "rechaza los impactos.", "[Escudo: 3]"},
    {14, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de metal", "rechaza los impactos.", "[Escudo: 3]"},
    {15, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de metal", "rechaza los impactos.", "[Escudo: 3]"},
    {16, "Vuelo Corto", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Aletea rapidamente", "para tomar ventaja.", "[Roba: 1] [+ Juega otra]"},
    {17, "Vuelo Corto", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Aletea rapidamente", "para tomar ventaja.", "[Roba: 1] [+ Juega otra]"},
    {18, "Vuelo Corto", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Aletea rapidamente", "para tomar ventaja.", "[Roba: 1] [+ Juega otra]"},
    {19, "Vuelo Corto", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Aletea rapidamente", "para tomar ventaja.", "[Roba: 1] [+ Juega otra]"},
    {20, "Grito Ensordecedor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Su canto te aturde", "y te deja vulnerable.", "[Dano: 2] [+ Juega otra]"},
    {21, "Grito Ensordecedor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Su canto te aturde", "y te deja vulnerable.", "[Dano: 2] [+ Juega otra]"},
    {22, "Grito Ensordecedor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Su canto te aturde", "y te deja vulnerable.", "[Dano: 2] [+ Juega otra]"},
    {23, "Grito Ensordecedor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Su canto te aturde", "y te deja vulnerable.", "[Dano: 2] [+ Juega otra]"},
    {24, "Estatua Posesa", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "La figura cobra vida,", "pesada y destructiva.", "[Dano: 4] [Escudo: 2]"},
    {25, "Estatua Posesa", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "La figura cobra vida,", "pesada y destructiva.", "[Dano: 4] [Escudo: 2]"},
    {26, "Estatua Posesa", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "La figura cobra vida,", "pesada y destructiva.", "[Dano: 4] [Escudo: 2]"},
    {27, "Estatua Posesa", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "La figura cobra vida,", "pesada y destructiva.", "[Dano: 4] [Escudo: 2]"},
};
const int GALLO_DECK_SIZE = 28;

// MAZO DE Cura sin Cabeza
const CardData CARTAS_CURA[] = {
    {0, "Llama Negra", FX_ATTACK, 6, 0, 0, 0, "Fuego del purgatorio", "que quema el alma.", "[Dano: 6]"},
    {1, "Llama Negra", FX_ATTACK, 6, 0, 0, 0, "Fuego del purgatorio", "que quema el alma.", "[Dano: 6]"},
    {2, "Llama Negra", FX_ATTACK, 6, 0, 0, 0, "Fuego del purgatorio", "que quema el alma.", "[Dano: 6]"},
    {3, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Palabras sin voz", "que destruyen la mente.", "[Dano: 2] [+ Juega otra]"},
    {4, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Palabras sin voz", "que destruyen la mente.", "[Dano: 2] [+ Juega otra]"},
    {5, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Palabras sin voz", "que destruyen la mente.", "[Dano: 2] [+ Juega otra]"},
    {6, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Palabras sin voz", "que destruyen la mente.", "[Dano: 2] [+ Juega otra]"},
    {7, "Aparicion", FX_SHIELD, 0, 4, 0, 0, "Se vuelve incorporeo,", "imposible de tocar.", "[Escudo: 4]"},
    {8, "Aparicion", FX_SHIELD, 0, 4, 0, 0, "Se vuelve incorporeo,", "imposible de tocar.", "[Escudo: 4]"},
    {9, "Aparicion", FX_SHIELD, 0, 4, 0, 0, "Se vuelve incorporeo,", "imposible de tocar.", "[Escudo: 4]"},
    {10, "Misa de Medianoche", FX_HEAL, 0, 0, 5, 0, "Un ritual profano", "que sana sus heridas.", "[Cura: 5 HP]"},
    {11, "Misa de Medianoche", FX_HEAL, 0, 0, 5, 0, "Un ritual profano", "que sana sus heridas.", "[Cura: 5 HP]"},
    {12, "Misa de Medianoche", FX_HEAL, 0, 0, 5, 0, "Un ritual profano", "que sana sus heridas.", "[Cura: 5 HP]"},
    {13, "Busqueda de Cabeza", FX_DRAW, 0, 0, 0, 3, "Vaga buscando partes", "de su cuerpo perdido.", "[Roba: 3]"},
    {14, "Busqueda de Cabeza", FX_DRAW, 0, 0, 0, 3, "Vaga buscando partes", "de su cuerpo perdido.", "[Roba: 3]"},
    {15, "Busqueda de Cabeza", FX_DRAW, 0, 0, 0, 3, "Vaga buscando partes", "de su cuerpo perdido.", "[Roba: 3]"},
    {16, "Condena", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "El juicio final", "cae sobre ti.", "[Dano: 4] [Escudo: 2]"},
    {17, "Condena", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "El juicio final", "cae sobre ti.", "[Dano: 4] [Escudo: 2]"},
    {18, "Condena", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "El juicio final", "cae sobre ti.", "[Dano: 4] [Escudo: 2]"},
    {19, "Condena", FX_ATTACK | FX_SHIELD, 4, 2, 0, 0, "El juicio final", "cae sobre ti.", "[Dano: 4] [Escudo: 2]"},
    {20, "Aura Espectral", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Un frio de ultratumba", "lo rodea por completo.", "[Cura: 2] [Roba: 1]"},
    {21, "Aura Espectral", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Un frio de ultratumba", "lo rodea por completo.", "[Cura: 2] [Roba: 1]"},
    {22, "Aura Espectral", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Un frio de ultratumba", "lo rodea por completo.", "[Cura: 2] [Roba: 1]"},
    {23, "Aura Espectral", FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Un frio de ultratumba", "lo rodea por completo.", "[Cura: 2] [Roba: 1]"},
    {24, "Levitacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Flota amenazante", "sobre el empedrado.", "[Roba: 1] [+ Juega otra]"},
    {25, "Levitacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Flota amenazante", "sobre el empedrado.", "[Roba: 1] [+ Juega otra]"},
    {26, "Levitacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Flota amenazante", "sobre el empedrado.", "[Roba: 1] [+ Juega otra]"},
    {27, "Levitacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Flota amenazante", "sobre el empedrado.", "[Roba: 1] [+ Juega otra]"},
};
const int CURA_DECK_SIZE = 28;

// MAZO DE El Chuzalongo
const CardData CARTAS_CHUZALONGO[] = {
    {0, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde la yugular", "con furia animal.", "[Dano: 5]"},
    {1, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde la yugular", "con furia animal.", "[Dano: 5]"},
    {2, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde la yugular", "con furia animal.", "[Dano: 5]"},
    {3, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde la yugular", "con furia animal.", "[Dano: 5]"},
    {4, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde la yugular", "con furia animal.", "[Dano: 5]"},
    {5, "Mordida Salvaje", FX_ATTACK, 5, 0, 0, 0, "Muerde la yugular", "con furia animal.", "[Dano: 5]"},
    {6, "Garras Paramo", FX_ATTACK, 4, 0, 0, 0, "Zarpazos sangrientos", "tejidos de rencor.", "[Dano: 4]"},
    {7, "Garras Paramo", FX_ATTACK, 4, 0, 0, 0, "Zarpazos sangrientos", "tejidos de rencor.", "[Dano: 4]"},
    {8, "Garras Paramo", FX_ATTACK, 4, 0, 0, 0, "Zarpazos sangrientos", "tejidos de rencor.", "[Dano: 4]"},
    {9, "Garras Paramo", FX_ATTACK, 4, 0, 0, 0, "Zarpazos sangrientos", "tejidos de rencor.", "[Dano: 4]"},
    {10, "Garras Paramo", FX_ATTACK, 4, 0, 0, 0, "Zarpazos sangrientos", "tejidos de rencor.", "[Dano: 4]"},
    {11, "Piel Gruesa", FX_SHIELD, 0, 1, 0, 0, "El lodo y musgo", "amortiguan un poco.", "[Escudo: 1]"},
    {12, "Piel Gruesa", FX_SHIELD, 0, 1, 0, 0, "El lodo y musgo", "amortiguan un poco.", "[Escudo: 1]"},
    {13, "Piel Gruesa", FX_SHIELD, 0, 1, 0, 0, "El lodo y musgo", "amortiguan un poco.", "[Escudo: 1]"},
    {14, "Instinto Animal", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Olfatea la sangre", "y actua sin dudar.", "[Roba: 1] [+ Juega otra]"},
    {15, "Instinto Animal", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Olfatea la sangre", "y actua sin dudar.", "[Roba: 1] [+ Juega otra]"},
    {16, "Instinto Animal", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Olfatea la sangre", "y actua sin dudar.", "[Roba: 1] [+ Juega otra]"},
    {17, "Instinto Animal", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Olfatea la sangre", "y actua sin dudar.", "[Roba: 1] [+ Juega otra]"},
    {18, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Ataca a todos lados", "sin mirar a quien.", "[Dano: 3] [+ Juega otra]"},
    {19, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Ataca a todos lados", "sin mirar a quien.", "[Dano: 3] [+ Juega otra]"},
    {20, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Ataca a todos lados", "sin mirar a quien.", "[Dano: 3] [+ Juega otra]"},
    {21, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Ataca a todos lados", "sin mirar a quien.", "[Dano: 3] [+ Juega otra]"},
    {22, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta de lo que", "encuentra en la montana.", "[Cura: 2 HP]"},
    {23, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta de lo que", "encuentra en la montana.", "[Cura: 2 HP]"},
    {24, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta de lo que", "encuentra en la montana.", "[Cura: 2 HP]"},
    {25, "Aullido", FX_ATTACK | FX_DRAW, 4, 0, 0, 1, "Un grito desgarrador", "que paraliza al enemigo.", "[Dano: 4] [Roba: 1]"},
    {26, "Aullido", FX_ATTACK | FX_DRAW, 4, 0, 0, 1, "Un grito desgarrador", "que paraliza al enemigo.", "[Dano: 4] [Roba: 1]"},
    {27, "Aullido", FX_ATTACK | FX_DRAW, 4, 0, 0, 1, "Un grito desgarrador", "que paraliza al enemigo.", "[Dano: 4] [Roba: 1]"},
};
const int CHUZALONGO_DECK_SIZE = 28;

// MAZO DE La Llorona
const CardData CARTAS_LLORONA[] = {
    {0, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Un grito de lamento", "que te rompe los timpanos.", "[Dano: 3]"},
    {1, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Un grito de lamento", "que te rompe los timpanos.", "[Dano: 3]"},
    {2, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Un grito de lamento", "que te rompe los timpanos.", "[Dano: 3]"},
    {3, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Un grito de lamento", "que te rompe los timpanos.", "[Dano: 3]"},
    {4, "Llanto Incesante", FX_HEAL, 0, 0, 4, 0, "Sus lagrimas forman", "lagos de desesperacion.", "[Cura: 4 HP]"},
    {5, "Llanto Incesante", FX_HEAL, 0, 0, 4, 0, "Sus lagrimas forman", "lagos de desesperacion.", "[Cura: 4 HP]"},
    {6, "Llanto Incesante", FX_HEAL, 0, 0, 4, 0, "Sus lagrimas forman", "lagos de desesperacion.", "[Cura: 4 HP]"},
    {7, "Llanto Incesante", FX_HEAL, 0, 0, 4, 0, "Sus lagrimas forman", "lagos de desesperacion.", "[Cura: 4 HP]"},
    {8, "Llanto Incesante", FX_HEAL, 0, 0, 4, 0, "Sus lagrimas forman", "lagos de desesperacion.", "[Cura: 4 HP]"},
    {9, "Rio Desbordado", FX_ATTACK | FX_SHIELD, 3, 2, 0, 0, "Aguas violentas te", "arrastran lejos de ella.", "[Dano: 3] [Escudo: 2]"},
    {10, "Rio Desbordado", FX_ATTACK | FX_SHIELD, 3, 2, 0, 0, "Aguas violentas te", "arrastran lejos de ella.", "[Dano: 3] [Escudo: 2]"},
    {11, "Rio Desbordado", FX_ATTACK | FX_SHIELD, 3, 2, 0, 0, "Aguas violentas te", "arrastran lejos de ella.", "[Dano: 3] [Escudo: 2]"},
    {12, "Rio Desbordado", FX_ATTACK | FX_SHIELD, 3, 2, 0, 0, "Aguas violentas te", "arrastran lejos de ella.", "[Dano: 3] [Escudo: 2]"},
    {13, "Manto Blanco", FX_SHIELD, 0, 3, 0, 0, "Su tunica espectral", "rechaza los ataques.", "[Escudo: 3]"},
    {14, "Manto Blanco", FX_SHIELD, 0, 3, 0, 0, "Su tunica espectral", "rechaza los ataques.", "[Escudo: 3]"},
    {15, "Manto Blanco", FX_SHIELD, 0, 3, 0, 0, "Su tunica espectral", "rechaza los ataques.", "[Escudo: 3]"},
    {16, "Manto Blanco", FX_SHIELD, 0, 3, 0, 0, "Su tunica espectral", "rechaza los ataques.", "[Escudo: 3]"},
    {17, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[Roba: 1] [+ Juega otra]"},
    {18, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[Roba: 1] [+ Juega otra]"},
    {19, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[Roba: 1] [+ Juega otra]"},
    {20, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[Roba: 1] [+ Juega otra]"},
    {21, "Ahogo", FX_ATTACK | FX_HEAL, 4, 0, 2, 0, "Te ahoga en el rio", "para recuperar su fuerza.", "[Dano: 4] [Cura: 2]"},
    {22, "Ahogo", FX_ATTACK | FX_HEAL, 4, 0, 2, 0, "Te ahoga en el rio", "para recuperar su fuerza.", "[Dano: 4] [Cura: 2]"},
    {23, "Ahogo", FX_ATTACK | FX_HEAL, 4, 0, 2, 0, "Te ahoga en el rio", "para recuperar su fuerza.", "[Dano: 4] [Cura: 2]"},
    {24, "Ahogo", FX_ATTACK | FX_HEAL, 4, 0, 2, 0, "Te ahoga en el rio", "para recuperar su fuerza.", "[Dano: 4] [Cura: 2]"},
    {25, "Lagrimas", FX_DRAW, 0, 0, 0, 2, "El dolor le ensena", "nuevas formas de sufrir.", "[Roba: 2]"},
    {26, "Lagrimas", FX_DRAW, 0, 0, 0, 2, "El dolor le ensena", "nuevas formas de sufrir.", "[Roba: 2]"},
    {27, "Lagrimas", FX_DRAW, 0, 0, 0, 2, "El dolor le ensena", "nuevas formas de sufrir.", "[Roba: 2]"},
};
const int LLORONA_DECK_SIZE = 28;

// MAZO DE Guagua Auca
const CardData CARTAS_GUAGUAAUCA[] = {
    {0, "Lloriqueo", FX_ATTACK, 2, 0, 0, 0, "Finge estar indefenso", "para atacarte de pronto.", "[Dano: 2]"},
    {1, "Lloriqueo", FX_ATTACK, 2, 0, 0, 0, "Finge estar indefenso", "para atacarte de pronto.", "[Dano: 2]"},
    {2, "Lloriqueo", FX_ATTACK, 2, 0, 0, 0, "Finge estar indefenso", "para atacarte de pronto.", "[Dano: 2]"},
    {3, "Lloriqueo", FX_ATTACK, 2, 0, 0, 0, "Finge estar indefenso", "para atacarte de pronto.", "[Dano: 2]"},
    {4, "Lloriqueo", FX_ATTACK, 2, 0, 0, 0, "Finge estar indefenso", "para atacarte de pronto.", "[Dano: 2]"},
    {5, "Dientes de Diablo", FX_ATTACK, 5, 0, 0, 0, "Muerde el cuello de", "quien lo carga en brazos.", "[Dano: 5]"},
    {6, "Dientes de Diablo", FX_ATTACK, 5, 0, 0, 0, "Muerde el cuello de", "quien lo carga en brazos.", "[Dano: 5]"},
    {7, "Dientes de Diablo", FX_ATTACK, 5, 0, 0, 0, "Muerde el cuello de", "quien lo carga en brazos.", "[Dano: 5]"},
    {8, "Dientes de Diablo", FX_ATTACK, 5, 0, 0, 0, "Muerde el cuello de", "quien lo carga en brazos.", "[Dano: 5]"},
    {9, "Panales", FX_SHIELD, 0, 2, 0, 0, "Usa su apariencia", "inocente como defensa.", "[Escudo: 2]"},
    {10, "Panales", FX_SHIELD, 0, 2, 0, 0, "Usa su apariencia", "inocente como defensa.", "[Escudo: 2]"},
    {11, "Panales", FX_SHIELD, 0, 2, 0, 0, "Usa su apariencia", "inocente como defensa.", "[Escudo: 2]"},
    {12, "Panales", FX_SHIELD, 0, 2, 0, 0, "Usa su apariencia", "inocente como defensa.", "[Escudo: 2]"},
    {13, "Sorpresa Maligna", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Revela su verdadera", "forma aterradora.", "[Dano: 3] [+ Juega otra]"},
    {14, "Sorpresa Maligna", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Revela su verdadera", "forma aterradora.", "[Dano: 3] [+ Juega otra]"},
    {15, "Sorpresa Maligna", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Revela su verdadera", "forma aterradora.", "[Dano: 3] [+ Juega otra]"},
    {16, "Sorpresa Maligna", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Revela su verdadera", "forma aterradora.", "[Dano: 3] [+ Juega otra]"},
    {17, "Sorpresa Maligna", FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Revela su verdadera", "forma aterradora.", "[Dano: 3] [+ Juega otra]"},
    {18, "Risa Macabra", FX_DRAW, 0, 0, 0, 2, "Se burla de ti", "mientras toma ventaja.", "[Roba: 2]"},
    {19, "Risa Macabra", FX_DRAW, 0, 0, 0, 2, "Se burla de ti", "mientras toma ventaja.", "[Roba: 2]"},
    {20, "Risa Macabra", FX_DRAW, 0, 0, 0, 2, "Se burla de ti", "mientras toma ventaja.", "[Roba: 2]"},
    {21, "Risa Macabra", FX_DRAW, 0, 0, 0, 2, "Se burla de ti", "mientras toma ventaja.", "[Roba: 2]"},
    {22, "Inocencia Fingida", FX_HEAL | FX_DRAW, 0, 0, 3, 1, "Te da compasion y", "el aprovecha el momento.", "[Cura: 3] [Roba: 1]"},
    {23, "Inocencia Fingida", FX_HEAL | FX_DRAW, 0, 0, 3, 1, "Te da compasion y", "el aprovecha el momento.", "[Cura: 3] [Roba: 1]"},
    {24, "Inocencia Fingida", FX_HEAL | FX_DRAW, 0, 0, 3, 1, "Te da compasion y", "el aprovecha el momento.", "[Cura: 3] [Roba: 1]"},
    {25, "Inocencia Fingida", FX_HEAL | FX_DRAW, 0, 0, 3, 1, "Te da compasion y", "el aprovecha el momento.", "[Cura: 3] [Roba: 1]"},
    {26, "Mordisco", FX_ATTACK | FX_SHIELD, 2, 2, 0, 0, "Muerde y se aleja", "rapidamente.", "[Dano: 2] [Escudo: 2]"},
    {27, "Mordisco", FX_ATTACK | FX_SHIELD, 2, 2, 0, 0, "Muerde y se aleja", "rapidamente.", "[Dano: 2] [Escudo: 2]"},
};
const int GUAGUAAUCA_DECK_SIZE = 28;

// MAZO DE Viuda Tamarindo
const CardData CARTAS_VIUDA[] = {
    {0, "Seduccion Oscura", FX_ATTACK | FX_HEAL, 4, 0, 3, 0, "Te atrae y luego te", "arranca la vitalidad.", "[Dano: 4] [Cura: 3]"},
    {1, "Seduccion Oscura", FX_ATTACK | FX_HEAL, 4, 0, 3, 0, "Te atrae y luego te", "arranca la vitalidad.", "[Dano: 4] [Cura: 3]"},
    {2, "Seduccion Oscura", FX_ATTACK | FX_HEAL, 4, 0, 3, 0, "Te atrae y luego te", "arranca la vitalidad.", "[Dano: 4] [Cura: 3]"},
    {3, "Seduccion Oscura", FX_ATTACK | FX_HEAL, 4, 0, 3, 0, "Te atrae y luego te", "arranca la vitalidad.", "[Dano: 4] [Cura: 3]"},
    {4, "Abrazo de Muerte", FX_ATTACK, 5, 0, 0, 0, "Te abraza fuerte", "hasta asfixiarte.", "[Dano: 5]"},
    {5, "Abrazo de Muerte", FX_ATTACK, 5, 0, 0, 0, "Te abraza fuerte", "hasta asfixiarte.", "[Dano: 5]"},
    {6, "Abrazo de Muerte", FX_ATTACK, 5, 0, 0, 0, "Te abraza fuerte", "hasta asfixiarte.", "[Dano: 5]"},
    {7, "Abrazo de Muerte", FX_ATTACK, 5, 0, 0, 0, "Te abraza fuerte", "hasta asfixiarte.", "[Dano: 5]"},
    {8, "Sombra del Arbol", FX_SHIELD, 0, 4, 0, 0, "Las ramas del viejo", "tamarindo la protegen.", "[Escudo: 4]"},
    {9, "Sombra del Arbol", FX_SHIELD, 0, 4, 0, 0, "Las ramas del viejo", "tamarindo la protegen.", "[Escudo: 4]"},
    {10, "Sombra del Arbol", FX_SHIELD, 0, 4, 0, 0, "Las ramas del viejo", "tamarindo la protegen.", "[Escudo: 4]"},
    {11, "Sombra del Arbol", FX_SHIELD, 0, 4, 0, 0, "Las ramas del viejo", "tamarindo la protegen.", "[Escudo: 4]"},
    {12, "Velo Negro", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "El misterio de su", "rostro oculto.", "[Roba: 1] [+ Juega otra]"},
    {13, "Velo Negro", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "El misterio de su", "rostro oculto.", "[Roba: 1] [+ Juega otra]"},
    {14, "Velo Negro", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "El misterio de su", "rostro oculto.", "[Roba: 1] [+ Juega otra]"},
    {15, "Velo Negro", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "El misterio de su", "rostro oculto.", "[Roba: 1] [+ Juega otra]"},
    {16, "Ilusion", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Crees ver a alguien mas", "y bajas la guardia.", "[Dano: 2] [+ Juega otra]"},
    {17, "Ilusion", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Crees ver a alguien mas", "y bajas la guardia.", "[Dano: 2] [+ Juega otra]"},
    {18, "Ilusion", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Crees ver a alguien mas", "y bajas la guardia.", "[Dano: 2] [+ Juega otra]"},
    {19, "Ilusion", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Crees ver a alguien mas", "y bajas la guardia.", "[Dano: 2] [+ Juega otra]"},
    {20, "Pasion Falsa", FX_HEAL, 0, 0, 5, 0, "Un beso embrujado", "que sana a la viuda.", "[Cura: 5 HP]"},
    {21, "Pasion Falsa", FX_HEAL, 0, 0, 5, 0, "Un beso embrujado", "que sana a la viuda.", "[Cura: 5 HP]"},
    {22, "Pasion Falsa", FX_HEAL, 0, 0, 5, 0, "Un beso embrujado", "que sana a la viuda.", "[Cura: 5 HP]"},
    {23, "Pasion Falsa", FX_HEAL, 0, 0, 5, 0, "Un beso embrujado", "que sana a la viuda.", "[Cura: 5 HP]"},
    {24, "Aroma Dulce", FX_DRAW, 0, 0, 0, 2, "Atrae a incautos", "hacia su trampa mortal.", "[Roba: 2]"},
    {25, "Aroma Dulce", FX_DRAW, 0, 0, 0, 2, "Atrae a incautos", "hacia su trampa mortal.", "[Roba: 2]"},
    {26, "Aroma Dulce", FX_DRAW, 0, 0, 0, 2, "Atrae a incautos", "hacia su trampa mortal.", "[Roba: 2]"},
    {27, "Aroma Dulce", FX_DRAW, 0, 0, 0, 2, "Atrae a incautos", "hacia su trampa mortal.", "[Roba: 2]"},
};
const int VIUDA_DECK_SIZE = 28;

