# BlocksDS standard Makefile
# -------------------------

# The name of the output ROM
NAME		:= EcuaTrials

# Title and author for the Nintendo DS menu
GAME_TITLE	:= EcuaTrials
GAME_AUTHOR	:= JulianDev
GAME_ICON	:= $(BLOCKSDS)/sys/icon.bmp

# Source code paths
SOURCEDIRS	:= source
INCLUDEDIRS	:= include
GFXDIRS		:= gfx

# Include standard BlocksDS rules
include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
