characters = \
[{'id': 'CANTUNA',
  'name': 'Cantuna',
  'role': 'TANQUE',
  'desc': ['Constructor legendario', 'Pacto con el diablo', 'Escudos fuertes'],
  'cards': [('Ladrillo Rapido',
             'FX_ATTACK | FX_PLAY_AGAIN',
             1,
             0,
             0,
             0,
             ['Arroja un ladrillo', 'con gran velocidad.', '[D:1] [+Juega]'],
             4),
            ('Golpe de Mazo',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Un bloque tallado a mano,', 'pesado como sus pecados.', '[D:3]'],
             4),
            ('Muro Base',
             'FX_SHIELD | FX_DRAW',
             0,
             1,
             0,
             1,
             ['Alza una pared', 'mientras planea.', '[E:1] [R:1]'],
             5),
            ('Fortaleza',
             'FX_SHIELD',
             0,
             3,
             0,
             0,
             ['Un pilar indestructible;', 'ni el diablo puede pasar.', '[E:3]'],
             4),
            ('Descanso',
             'FX_HEAL',
             0,
             0,
             2,
             0,
             ['Cierra los ojos un momento', 'antes del amanecer.', '[C:2 HP]'],
             4),
            ('Inspiracion',
             'FX_DRAW | FX_PLAY_AGAIN',
             0,
             0,
             0,
             1,
             ['Una chispa de ingenio',
              'le permite actuar rapido.',
              '[R:1] [+Juega]'],
             4),
            ('Iglesia Terminada',
             'FX_SHIELD | FX_HEAL | FX_ATTACK',
             2,
             4,
             2,
             0,
             ['Construye todo de golpe.',
              'Su obra maestra.',
              '[E:4] [C:2] [D:2]'],
             1),
            ('Pacto Enganoso',
             'FX_STEAL_HAND | FX_HEAL',
             0,
             0,
             3,
             0,
             ['El diablo cobra',
              'su deuda en el rival.',
              '[C: 3] [Roba de mano]'],
             1),
            ('Cimiento Solido',
             'FX_STEAL_DISCARD | FX_SHIELD',
             0,
             4,
             0,
             0,
             ['Usa los restos para',
              'blindarse por completo.',
              '[E: 4] [Roba descarte]'],
             1)]},
 {'id': 'TINTIN',
  'name': 'El Tin Tin',
  'role': 'AGRESOR',
  'desc': ['Duende travieso', 'Aparece en las sombras', 'Cadenas de combos'],
  'cards': [('Travesura',
             'FX_ATTACK | FX_PLAY_AGAIN',
             1,
             0,
             0,
             0,
             ['Tira de tu cabello', 'y sigue molestando.', '[D:1] [+Juega]'],
             4),
            ('Emboscada',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Cae desde las ramas', 'directo sobre su presa.', '[D:3]'],
             4),
            ('Escondite',
             'FX_SHIELD | FX_PLAY_AGAIN',
             0,
             1,
             0,
             0,
             ['Se oculta rapidamente', 'en la maleza.', '[E:1] [+Juega]'],
             5),
            ('Agilidad',
             'FX_DRAW | FX_PLAY_AGAIN',
             0,
             0,
             0,
             1,
             ['Salta por los aires',
              'burlando toda defensa.',
              '[R:1] [+Juega]'],
             4),
            ('Siesta Maliciosa',
             'FX_HEAL',
             0,
             0,
             2,
             0,
             ['Descansa un rato para', 'planear otra diablura.', '[C:2]'],
             4),
            ('Robo de Bolsillos',
             'FX_STEAL_DECK | FX_ATTACK',
             1,
             0,
             0,
             2,
             ['Manos tan rapidas que',
              'ni sientes que te roba.',
              '[D: 1] [Roba mazo rival]'],
             4),
            ('Seductor Mitico',
             'FX_ATTACK | FX_DRAW | FX_PLAY_AGAIN',
             4,
             0,
             0,
             1,
             ['Te engana y', 'te roba el alma.', '[D:4] [R:1] [+Juega]'],
             1),
            ('Sombrero Magico',
             'FX_STEAL_DECK | FX_DRAW | FX_PLAY_AGAIN',
             0,
             0,
             0,
             2,
             ['Saca sorpresas',
              'interminables.',
              '[R: 2] [Roba mazo] [+Juega]'],
             1),
            ('Asalto Fugaz',
             'FX_STEAL_HAND | FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Te golpea y te deja', 'sin opciones.', '[D: 3] [Roba de mano]'],
             1)]},
 {'id': 'TUNDA',
  'name': 'La Tunda',
  'role': 'CONTROL',
  'desc': ['Bruja del manglar', 'Pierna de molinillo', 'Curacion y drenaje'],
  'cards': [('Zarpazo',
             'FX_ATTACK | FX_HEAL',
             1,
             0,
             1,
             0,
             ['Su mano retorcida', 'desgarra y absorbe.', '[D:1] [C:1]'],
             4),
            ('Molinillazo',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Patea con su pesada', 'pierna de madera.', '[D:3]'],
             4),
            ('Niebla Espesa',
             'FX_SHIELD | FX_PLAY_AGAIN',
             0,
             1,
             0,
             0,
             ['El manglar se cierra,',
              'ocultandola por completo.',
              '[E:1] [+Juega]'],
             5),
            ('Proteccion Lodo',
             'FX_SHIELD',
             0,
             3,
             0,
             0,
             ['Barro del pantano', 'amortigua los golpes.', '[E:3]'],
             4),
            ('Camarones Magicos',
             'FX_HEAL',
             0,
             0,
             2,
             0,
             ['Un bocado embrujado', 'que restaura su vigor.', '[C:2 HP]'],
             4),
            ('Susurros',
             'FX_DRAW | FX_PLAY_AGAIN',
             0,
             0,
             0,
             1,
             ['Voces en la niebla que',
              'revelan secretos oscuros.',
              '[R:1] [+Juega]'],
             4),
            ('Entundamiento',
             'FX_HEAL | FX_ATTACK | FX_DRAW',
             2,
             0,
             4,
             1,
             ['Hipnotiza a su presa',
              'en el fondo del bosque.',
              '[C:4] [D:2] [R:1]'],
             1),
            ('Maldicion del Manglar',
             'FX_STEAL_HAND | FX_STEAL_DISCARD',
             0,
             0,
             0,
             0,
             ['Pierdes todo', 'lo que tenias.', '[Roba mano y descarte]'],
             1),
            ('Ilusion Maternal',
             'FX_STEAL_DECK | FX_HEAL',
             0,
             0,
             3,
             0,
             ['Finge ser tu madre',
              'para robar tu futuro.',
              '[C: 3] [Roba mazo rival]'],
             1)]},
 {'id': 'ALMEIDA',
  'name': 'Padre Almeida',
  'role': 'COMBO',
  'desc': ['Sacerdote rebelde', 'Sale de farra', 'Mucho robo de cartas'],
  'cards': [('Guitarrazo',
             'FX_ATTACK | FX_PLAY_AGAIN',
             1,
             0,
             0,
             0,
             ['Un golpe rapido con', 'su vieja guitarra.', '[D:1] [+Juega]'],
             4),
            ('Botellazo',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Vuela una botella vacia', 'directo a la cabeza.', '[D:3]'],
             4),
            ('Sotana',
             'FX_SHIELD | FX_DRAW',
             0,
             1,
             0,
             1,
             ['La tela sagrada lo', 'cubre mientras huye.', '[E:1] [R:1]'],
             5),
            ('Trago Bendito',
             'FX_HEAL | FX_PLAY_AGAIN',
             0,
             0,
             1,
             0,
             ['Un pequeno sorbo', 'para seguir la fiesta.', '[C:1] [+Juega]'],
             4),
            ('Salida Secreta',
             'FX_STEAL_DECK | FX_DRAW',
             0,
             0,
             0,
             2,
             ['Conoce todos los atajos',
              'y descubre sus planes.',
              '[Roba: 1] [Roba mazo rival]'],
             4),
            ('Farra',
             'FX_ATTACK | FX_DRAW',
             2,
             0,
             0,
             1,
             ['Sigue la fiesta con', 'golpes impredecibles.', '[D:2] [R:1]'],
             4),
            ('Hasta la Vuelta!',
             'FX_DRAW | FX_PLAY_AGAIN | FX_HEAL',
             0,
             0,
             2,
             2,
             ['Pisa al Cristo y',
              'sale corriendo invencible.',
              '[R:2] [C:2] [+Juega]'],
             1),
            ('Escape Milagroso',
             'FX_STEAL_HAND | FX_DRAW',
             0,
             0,
             0,
             2,
             ['Esquiva tu ataque y',
              'huye con ventaja.',
              '[R: 2] [Roba de mano]'],
             1),
            ('Trago Robado',
             'FX_STEAL_DISCARD | FX_HEAL | FX_PLAY_AGAIN',
             0,
             0,
             2,
             0,
             ['Bebe de la botella',
              'que creias vacia.',
              '[C: 2] [Roba descarte] [+J]'],
             1)]},
 {'id': 'DAMATAPADA',
  'name': 'Dama Tapada',
  'role': 'TERROR',
  'desc': ['Mujer misteriosa', 'Rostro calaverico', 'Debuffs y miedo'],
  'cards': [('Perfume Barato',
             'FX_ATTACK | FX_PLAY_AGAIN',
             1,
             0,
             0,
             0,
             ['Aroma embriagador que',
              'desorienta al instante.',
              '[D:1] [+Juega]'],
             4),
            ('Grito Aterrador',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Un chillido agudo que', 'hiela la sangre.', '[D:3]'],
             4),
            ('Bruma Fria',
             'FX_SHIELD | FX_DRAW',
             0,
             1,
             0,
             1,
             ['Una niebla oscura', 'amortigua los golpes.', '[E:1] [R:1]'],
             5),
            ('Paseo Nocturno',
             'FX_SHIELD',
             0,
             3,
             0,
             0,
             ['Camina flotando;', 'es dificil golpearla.', '[E:3]'],
             4),
            ('Beso Frio',
             'FX_HEAL',
             0,
             0,
             2,
             0,
             ['Restaura su energia', 'con magia negra.', '[C:2]'],
             4),
            ('Seduccion',
             'FX_DRAW | FX_PLAY_AGAIN',
             0,
             0,
             0,
             1,
             ['Atrae a incautos', 'hacia su perdicion.', '[R:1] [+Juega]'],
             4),
            ('Rostro Esqueletico',
             'FX_ATTACK | FX_SHIELD',
             4,
             3,
             0,
             0,
             ['Se quita el velo;', 'el horror absoluto.', '[D:4] [E:3]'],
             1),
            ('Perfume Letal',
             'FX_STEAL_DECK | FX_ATTACK',
             4,
             0,
             0,
             0,
             ['El olor a muerte',
              'arruina tu destino.',
              '[D: 4] [Roba mazo rival]'],
             1),
            ('Mirada al Abismo',
             'FX_STEAL_HAND | FX_STEAL_DECK',
             0,
             0,
             0,
             0,
             ['El panico te', 'hace perder la cabeza.', '[Roba mano y mazo]'],
             1)]},
 {'id': 'MARIANGULA',
  'name': 'Maria Angula',
  'role': 'AGRESOR',
  'desc': ['Nina golosa', 'Robo tripas del muerto', 'Ataques freneticos'],
  'cards': [('Tijeras',
             'FX_ATTACK | FX_PLAY_AGAIN',
             1,
             0,
             0,
             0,
             ['Corta sin pensar', 'en las consecuencias.', '[D:1] [+Juega]'],
             4),
            ('Olla Caliente',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Lanza caldo hirviendo', 'sin pensarlo dos veces.', '[D:3]'],
             4),
            ('Escondite',
             'FX_SHIELD | FX_PLAY_AGAIN',
             0,
             1,
             0,
             0,
             ['Se esconde temblando', 'bajo las mantas.', '[E:1] [+Juega]'],
             5),
            ('Miedo a la Noche',
             'FX_SHIELD',
             0,
             2,
             0,
             1,
             ['El terror la obliga', 'a protegerse y pensar.', '[E:2] [R:1]'],
             4),
            ('Robo de Tripas',
             'FX_STEAL_DISCARD | FX_HEAL',
             0,
             0,
             2,
             0,
             ['Saca algo util de',
              'la tumba del oponente.',
              '[C: 2] [Roba descarte]'],
             4),
            ('Grito de Culpa',
             'FX_DRAW | FX_PLAY_AGAIN',
             0,
             0,
             0,
             1,
             ['Su llanto aterra y', 'le da nuevas ideas.', '[R:1] [+Juega]'],
             4),
            ('Sopa Macabra',
             'FX_ATTACK | FX_HEAL | FX_PLAY_AGAIN',
             4,
             0,
             2,
             0,
             ['Cocina el mal y', 'se fortalece.', '[D:4] [C:2] [+Juega]'],
             1),
            ('Sopa de Robos',
             'FX_STEAL_DISCARD | FX_STEAL_HAND',
             0,
             0,
             0,
             0,
             ['Saca ingredientes', 'de donde sea.', '[Roba mano y descarte]'],
             1),
            ('Berrinche Mortal',
             'FX_STEAL_DECK | FX_ATTACK | FX_PLAY_AGAIN',
             2,
             0,
             0,
             0,
             ['Destruye todo', 'a su paso.', '[D: 2] [Roba mazo] [+J]'],
             1)]},
 {'id': 'GALLO',
  'name': 'Gallo Catedral',
  'role': 'EQUILIBRADO',
  'desc': ['Gallo de oro', 'Canta en la iglesia', 'Dano y velocidad'],
  'cards': [('Picotazo Rapido',
             'FX_ATTACK | FX_PLAY_AGAIN',
             1,
             0,
             0,
             0,
             ['Un golpe veloz', 'con su pico de oro.', '[D:1] [+Juega]'],
             4),
            ('Espolon',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Un corte profundo', 'con sus garras afiladas.', '[D:3]'],
             4),
            ('Vuelo Corto',
             'FX_SHIELD | FX_PLAY_AGAIN',
             0,
             1,
             0,
             0,
             ['Aletea rapidamente', 'para tomar ventaja.', '[E:1] [+Juega]'],
             5),
            ('Alas de Bronce',
             'FX_SHIELD',
             0,
             3,
             0,
             0,
             ['Su cuerpo de metal', 'rechaza los impactos.', '[E:3]'],
             4),
            ('Pluma Dorada',
             'FX_HEAL',
             0,
             0,
             2,
             0,
             ['Brillo sanador que', 'restaura su bronce.', '[C:2 HP]'],
             4),
            ('Canto Matutino',
             'FX_DRAW | FX_HEAL',
             0,
             0,
             1,
             2,
             ['Anuncia el amanecer,', 'renovando su fuerza.', '[C:1] [R:2]'],
             4),
            ('Ira de la Catedral',
             'FX_ATTACK | FX_SHIELD | FX_HEAL',
             3,
             3,
             3,
             0,
             ['El monumento despierta',
              'castigando al blasfemo.',
              '[D:3] [E:3] [C:3]'],
             1),
            ('Canto Hipnotico',
             'FX_STEAL_HAND | FX_SHIELD',
             0,
             3,
             0,
             0,
             ['Te aturde mientras', 'se protege.', '[E: 3] [Roba de mano]'],
             1),
            ('Brillo Cegador',
             'FX_STEAL_DISCARD | FX_DRAW | FX_PLAY_AGAIN',
             0,
             0,
             0,
             1,
             ['Resplandece y toma',
              'la iniciativa.',
              '[R: 1] [Roba descarte] [+J]'],
             1)]},
 {'id': 'CURA',
  'name': 'Cura sin Cabeza',
  'role': 'MAGIA',
  'desc': ['Sacerdote maldito', 'No tiene cabeza', 'Magia oscura pura'],
  'cards': [('Sermon Mudo',
             'FX_ATTACK | FX_PLAY_AGAIN',
             1,
             0,
             0,
             0,
             ['Palabras sin voz', 'que destruyen la mente.', '[D:1] [+Juega]'],
             4),
            ('Llama Negra',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Fuego del purgatorio', 'que quema el alma.', '[D:3]'],
             4),
            ('Levitacion',
             'FX_SHIELD | FX_DRAW',
             0,
             1,
             0,
             1,
             ['Flota amenazante', 'sobre el empedrado.', '[E:1] [R:1]'],
             5),
            ('Aparicion',
             'FX_SHIELD',
             0,
             3,
             0,
             0,
             ['Se vuelve incorporeo,', 'imposible de tocar.', '[E:3]'],
             4),
            ('Aura Espectral',
             'FX_HEAL',
             0,
             0,
             2,
             0,
             ['Un frio de ultratumba', 'lo rodea por completo.', '[C:2]'],
             4),
            ('Busqueda de Cabeza',
             'FX_DRAW | FX_PLAY_AGAIN',
             0,
             0,
             0,
             1,
             ['Vaga buscando partes',
              'de su cuerpo perdido.',
              '[R:1] [+Juega]'],
             4),
            ('Misa de Medianoche',
             'FX_ATTACK | FX_DRAW | FX_PLAY_AGAIN',
             4,
             0,
             0,
             2,
             ['Un ritual profano',
              'que condena al enemigo.',
              '[D:4] [R:2] [+Juega]'],
             1),
            ('Fuego del Purgatorio',
             'FX_STEAL_DECK | FX_ATTACK',
             5,
             0,
             0,
             0,
             ['Quema tu esperanza.', '', '[D: 5] [Roba mazo rival]'],
             1),
            ('Exorcismo Inverso',
             'FX_STEAL_HAND | FX_HEAL',
             0,
             0,
             4,
             0,
             ['Te drena el alma.', '', '[C: 4] [Roba de mano]'],
             1)]},
 {'id': 'CHUZALONGO',
  'name': 'El Chuzalongo',
  'role': 'SALVAJE',
  'desc': ['Criatura del Paramo', 'Agresividad pura', 'Nula defensa'],
  'cards': [('Furia Ciega',
             'FX_ATTACK | FX_PLAY_AGAIN',
             1,
             0,
             0,
             0,
             ['Ataca a todos lados', 'sin mirar a quien.', '[D:1] [+Juega]'],
             4),
            ('Garras Paramo',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Zarpazos sangrientos', 'tejidos de rencor.', '[D:3]'],
             4),
            ('Instinto Animal',
             'FX_SHIELD | FX_PLAY_AGAIN',
             0,
             1,
             0,
             0,
             ['Olfatea la sangre', 'y actua sin dudar.', '[E:1] [+Juega]'],
             5),
            ('Piel Gruesa',
             'FX_SHIELD',
             0,
             2,
             0,
             1,
             ['El lodo y musgo', 'amortiguan un poco.', '[E:2] [R:1]'],
             4),
            ('Carne Cruda',
             'FX_HEAL',
             0,
             0,
             2,
             0,
             ['Se alimenta de lo que', 'encuentra en la montana.', '[C:2 HP]'],
             4),
            ('Aullido',
             'FX_DRAW | FX_ATTACK',
             2,
             0,
             0,
             1,
             ['Un grito desgarrador',
              'que paraliza al enemigo.',
              '[D:2] [R:1]'],
             4),
            ('Mordida Salvaje',
             'FX_ATTACK | FX_HEAL | FX_PLAY_AGAIN',
             4,
             0,
             2,
             0,
             ['Muerde la yugular', 'con furia animal.', '[D:4] [C:2] [+Juega]'],
             1),
            ('Ataque Furtivo',
             'FX_STEAL_HAND | FX_ATTACK',
             4,
             0,
             0,
             0,
             ['Muerde y se roba', 'lo que caiga.', '[D: 4] [Roba de mano]'],
             1),
            ('Carrona',
             'FX_STEAL_DISCARD | FX_HEAL | FX_DRAW',
             0,
             0,
             2,
             1,
             ['Se alimenta de tus', 'restos.', '[C: 2] [R: 1] [Roba desc]'],
             1)]},
 {'id': 'LLORONA',
  'name': 'La Llorona',
  'role': 'TRISTEZA',
  'desc': ['Madre en pena', 'Busca a sus hijos', 'Mucha curacion'],
  'cards': [('Lagrimas',
             'FX_ATTACK | FX_PLAY_AGAIN',
             1,
             0,
             0,
             0,
             ['El dolor le ensena',
              'nuevas formas de sufrir.',
              '[D:1] [+Juega]'],
             4),
            ('Mis Hijos!',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Un grito de lamento', 'que te rompe los timpanos.', '[D:3]'],
             4),
            ('Manto Blanco',
             'FX_SHIELD | FX_HEAL',
             0,
             1,
             1,
             0,
             ['Su tunica espectral', 'rechaza los ataques.', '[E:1] [C:1]'],
             5),
            ('Rio Desbordado',
             'FX_SHIELD',
             0,
             3,
             0,
             0,
             ['Aguas violentas te', 'arrastran lejos de ella.', '[E:3]'],
             4),
            ('Consuelo Vano',
             'FX_HEAL',
             0,
             0,
             2,
             0,
             ['Se engana pensando', 'que aun estan vivos.', '[C:2]'],
             4),
            ('Desesperacion',
             'FX_DRAW | FX_PLAY_AGAIN',
             0,
             0,
             0,
             1,
             ['Busca frenetica', 'por las orillas.', '[R:1] [+Juega]'],
             4),
            ('Ahogo Profundo',
             'FX_HEAL | FX_SHIELD | FX_ATTACK',
             2,
             4,
             4,
             0,
             ['Te sumerge en su', 'eterno sufrimiento.', '[C:4] [E:4] [D:2]'],
             1),
            ('Llanto Ahogado',
             'FX_STEAL_DECK | FX_SHIELD',
             0,
             4,
             0,
             0,
             ['Sus lagrimas forman',
              'una barrera.',
              '[E: 4] [Roba mazo rival]'],
             1),
            ('Arrastrar al Fondo',
             'FX_STEAL_DISCARD | FX_ATTACK | FX_HEAL',
             2,
             0,
             2,
             0,
             ['Te hunde con ella.', '', '[D: 2] [C: 2] [Roba desc]'],
             1)]},
 {'id': 'GUAGUAAUCA',
  'name': 'Guagua Auca',
  'role': 'SORPRESA',
  'desc': ['Bebe fantasma', 'Demonio enganoso', 'Robo y dano'],
  'cards': [('Lloriqueo',
             'FX_ATTACK | FX_PLAY_AGAIN',
             1,
             0,
             0,
             0,
             ['Finge estar indefenso',
              'para atacarte de pronto.',
              '[D:1] [+Juega]'],
             4),
            ('Sorpresa Maligna',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Revela su verdadera', 'forma aterradora.', '[D:3]'],
             4),
            ('Panales',
             'FX_SHIELD | FX_PLAY_AGAIN',
             0,
             1,
             0,
             0,
             ['Usa su apariencia', 'inocente como defensa.', '[E:1] [+Juega]'],
             5),
            ('Inocencia Fingida',
             'FX_STEAL_HAND | FX_SHIELD',
             0,
             2,
             0,
             1,
             ['Te da compasion y',
              'te roba lo que tienes.',
              '[E: 2] [Roba de mano]'],
             4),
            ('Biberon de Sangre',
             'FX_HEAL',
             0,
             0,
             2,
             0,
             ['Se alimenta de tu', 'piedad.', '[C:2]'],
             4),
            ('Risa Macabra',
             'FX_DRAW | FX_PLAY_AGAIN',
             0,
             0,
             0,
             1,
             ['Se burla de ti', 'mientras toma ventaja.', '[R:1] [+Juega]'],
             4),
            ('Dientes de Diablo',
             'FX_ATTACK | FX_DRAW | FX_PLAY_AGAIN',
             4,
             0,
             0,
             2,
             ['Muerde el cuello de', 'quien lo carga.', '[D:4] [R:2] [+Juega]'],
             1),
            ('Berrinche Infernal',
             'FX_STEAL_DECK | FX_STEAL_DISCARD',
             0,
             0,
             0,
             0,
             ['Un demonio desatado',
              'robando por doquier.',
              '[Roba mazo y descarte]'],
             1),
            ('Muerde Dedos',
             'FX_STEAL_HAND | FX_ATTACK | FX_PLAY_AGAIN',
             2,
             0,
             0,
             0,
             ['Engana y ataca', 'muy rapido.', '[D: 2] [Roba mano] [+J]'],
             1)]},
 {'id': 'VIUDA',
  'name': 'Viuda Tamarindo',
  'role': 'TRAMPA',
  'desc': ['Aparece en Guayaquil', 'Debajo del tamarindo', 'Control total'],
  'cards': [('Ilusion',
             'FX_ATTACK | FX_PLAY_AGAIN',
             1,
             0,
             0,
             0,
             ['Crees ver a alguien mas',
              'y bajas la guardia.',
              '[D:1] [+Juega]'],
             4),
            ('Borracho Perdido',
             'FX_ATTACK',
             3,
             0,
             0,
             0,
             ['Engana a sus victimas', 'hasta dejarlas vacias.', '[D:3]'],
             4),
            ('Aroma Dulce',
             'FX_SHIELD | FX_PLAY_AGAIN',
             0,
             1,
             0,
             0,
             ['Atrae a incautos', 'hacia su trampa mortal.', '[E:1] [+Juega]'],
             5),
            ('Sombra del Arbol',
             'FX_SHIELD',
             0,
             3,
             0,
             0,
             ['Las ramas del viejo', 'tamarindo la protegen.', '[E:3]'],
             4),
            ('Pasion Falsa',
             'FX_HEAL',
             0,
             0,
             2,
             0,
             ['Un beso embrujado', 'que sana a la viuda.', '[C:2 HP]'],
             4),
            ('Velo Negro',
             'FX_STEAL_HAND | FX_PLAY_AGAIN',
             0,
             0,
             0,
             1,
             ['Te nubla la mente y',
              'pierdes tu mejor carta.',
              '[Roba de mano] [+Juega]'],
             4),
            ('Abrazo de Muerte',
             'FX_ATTACK | FX_HEAL | FX_SHIELD',
             4,
             2,
             3,
             0,
             ['Te abraza fuerte', 'hasta asfixiarte.', '[D:4] [C:3] [E:2]'],
             1),
            ('Seduccion Oscura',
             'FX_STEAL_DECK | FX_STEAL_HAND',
             0,
             0,
             0,
             0,
             ['El engano perfecto.', '', '[Roba mazo y mano]'],
             1),
            ('Asfixia',
             'FX_STEAL_DISCARD | FX_ATTACK | FX_PLAY_AGAIN',
             3,
             0,
             0,
             0,
             ['Te roba el aire y', 'tus recuerdos.', '[D: 3] [Roba desc] [+J]'],
             1)]}]
