#include "card.h"

// MAZO DE Cantuna
const CardData CARTAS_CANTUNA[] = {
    {0, "Ladrillo Rapido", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Arroja un ladrillo", "con gran velocidad.", "[D:1] [+Juega]"},
    {1, "Ladrillo Rapido", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Arroja un ladrillo", "con gran velocidad.", "[D:1] [+Juega]"},
    {2, "Ladrillo Rapido", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Arroja un ladrillo", "con gran velocidad.", "[D:1] [+Juega]"},
    {3, "Ladrillo Rapido", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Arroja un ladrillo", "con gran velocidad.", "[D:1] [+Juega]"},
    {4, "Golpe de Mazo", FX_ATTACK, 3, 0, 0, 0, "Un bloque tallado a mano,", "pesado como sus pecados.", "[D:3]"},
    {5, "Golpe de Mazo", FX_ATTACK, 3, 0, 0, 0, "Un bloque tallado a mano,", "pesado como sus pecados.", "[D:3]"},
    {6, "Golpe de Mazo", FX_ATTACK, 3, 0, 0, 0, "Un bloque tallado a mano,", "pesado como sus pecados.", "[D:3]"},
    {7, "Golpe de Mazo", FX_ATTACK, 3, 0, 0, 0, "Un bloque tallado a mano,", "pesado como sus pecados.", "[D:3]"},
    {8, "Muro Base", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Alza una pared", "mientras planea.", "[E:1] [R:1]"},
    {9, "Muro Base", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Alza una pared", "mientras planea.", "[E:1] [R:1]"},
    {10, "Muro Base", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Alza una pared", "mientras planea.", "[E:1] [R:1]"},
    {11, "Muro Base", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Alza una pared", "mientras planea.", "[E:1] [R:1]"},
    {12, "Muro Base", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Alza una pared", "mientras planea.", "[E:1] [R:1]"},
    {13, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Un pilar indestructible;", "ni el diablo puede pasar.", "[E:3]"},
    {14, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Un pilar indestructible;", "ni el diablo puede pasar.", "[E:3]"},
    {15, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Un pilar indestructible;", "ni el diablo puede pasar.", "[E:3]"},
    {16, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Un pilar indestructible;", "ni el diablo puede pasar.", "[E:3]"},
    {17, "Descanso", FX_HEAL, 0, 0, 2, 0, "Cierra los ojos un momento", "antes del amanecer.", "[C:2 HP]"},
    {18, "Descanso", FX_HEAL, 0, 0, 2, 0, "Cierra los ojos un momento", "antes del amanecer.", "[C:2 HP]"},
    {19, "Descanso", FX_HEAL, 0, 0, 2, 0, "Cierra los ojos un momento", "antes del amanecer.", "[C:2 HP]"},
    {20, "Descanso", FX_HEAL, 0, 0, 2, 0, "Cierra los ojos un momento", "antes del amanecer.", "[C:2 HP]"},
    {21, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Una chispa de ingenio", "le permite actuar rapido.", "[R:1] [+Juega]"},
    {22, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Una chispa de ingenio", "le permite actuar rapido.", "[R:1] [+Juega]"},
    {23, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Una chispa de ingenio", "le permite actuar rapido.", "[R:1] [+Juega]"},
    {24, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Una chispa de ingenio", "le permite actuar rapido.", "[R:1] [+Juega]"},
    {25, "Iglesia Terminada", FX_SHIELD | FX_HEAL | FX_ATTACK, 2, 4, 2, 0, "Construye todo de golpe.", "Su obra maestra.", "[E:4] [C:2] [D:2]"},
    {26, "Pacto Enganoso", FX_STEAL_HAND | FX_HEAL, 0, 0, 3, 0, "El diablo cobra", "su deuda en el rival.", "[C: 3] [Roba de mano]"},
    {27, "Cimiento Solido", FX_STEAL_DISCARD | FX_SHIELD, 0, 4, 0, 0, "Usa los restos para", "blindarse por completo.", "[E: 4] [Roba descarte]"},
};
const int CANTUNA_DECK_SIZE = 28;

// MAZO DE El Tin Tin
const CardData CARTAS_TINTIN[] = {
    {0, "Travesura", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Tira de tu cabello", "y sigue molestando.", "[D:1] [+Juega]"},
    {1, "Travesura", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Tira de tu cabello", "y sigue molestando.", "[D:1] [+Juega]"},
    {2, "Travesura", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Tira de tu cabello", "y sigue molestando.", "[D:1] [+Juega]"},
    {3, "Travesura", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Tira de tu cabello", "y sigue molestando.", "[D:1] [+Juega]"},
    {4, "Emboscada", FX_ATTACK, 3, 0, 0, 0, "Cae desde las ramas", "directo sobre su presa.", "[D:3]"},
    {5, "Emboscada", FX_ATTACK, 3, 0, 0, 0, "Cae desde las ramas", "directo sobre su presa.", "[D:3]"},
    {6, "Emboscada", FX_ATTACK, 3, 0, 0, 0, "Cae desde las ramas", "directo sobre su presa.", "[D:3]"},
    {7, "Emboscada", FX_ATTACK, 3, 0, 0, 0, "Cae desde las ramas", "directo sobre su presa.", "[D:3]"},
    {8, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se oculta rapidamente", "en la maleza.", "[E:1] [+Juega]"},
    {9, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se oculta rapidamente", "en la maleza.", "[E:1] [+Juega]"},
    {10, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se oculta rapidamente", "en la maleza.", "[E:1] [+Juega]"},
    {11, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se oculta rapidamente", "en la maleza.", "[E:1] [+Juega]"},
    {12, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se oculta rapidamente", "en la maleza.", "[E:1] [+Juega]"},
    {13, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los aires", "burlando toda defensa.", "[R:1] [+Juega]"},
    {14, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los aires", "burlando toda defensa.", "[R:1] [+Juega]"},
    {15, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los aires", "burlando toda defensa.", "[R:1] [+Juega]"},
    {16, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los aires", "burlando toda defensa.", "[R:1] [+Juega]"},
    {17, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Descansa un rato para", "planear otra diablura.", "[C:2]"},
    {18, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Descansa un rato para", "planear otra diablura.", "[C:2]"},
    {19, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Descansa un rato para", "planear otra diablura.", "[C:2]"},
    {20, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Descansa un rato para", "planear otra diablura.", "[C:2]"},
    {21, "Robo de Bolsillos", FX_STEAL_DECK | FX_ATTACK, 1, 0, 0, 2, "Manos tan rapidas que", "ni sientes que te roba.", "[D: 1] [Roba mazo rival]"},
    {22, "Robo de Bolsillos", FX_STEAL_DECK | FX_ATTACK, 1, 0, 0, 2, "Manos tan rapidas que", "ni sientes que te roba.", "[D: 1] [Roba mazo rival]"},
    {23, "Robo de Bolsillos", FX_STEAL_DECK | FX_ATTACK, 1, 0, 0, 2, "Manos tan rapidas que", "ni sientes que te roba.", "[D: 1] [Roba mazo rival]"},
    {24, "Robo de Bolsillos", FX_STEAL_DECK | FX_ATTACK, 1, 0, 0, 2, "Manos tan rapidas que", "ni sientes que te roba.", "[D: 1] [Roba mazo rival]"},
    {25, "Seductor Mitico", FX_ATTACK | FX_DRAW | FX_PLAY_AGAIN, 4, 0, 0, 1, "Te engana y", "te roba el alma.", "[D:4] [R:1] [+Juega]"},
    {26, "Sombrero Magico", FX_STEAL_DECK | FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 2, "Saca sorpresas", "interminables.", "[R: 2] [Roba mazo] [+Juega]"},
    {27, "Asalto Fugaz", FX_STEAL_HAND | FX_ATTACK, 3, 0, 0, 0, "Te golpea y te deja", "sin opciones.", "[D: 3] [Roba de mano]"},
};
const int TINTIN_DECK_SIZE = 28;

// MAZO DE La Tunda
const CardData CARTAS_TUNDA[] = {
    {0, "Zarpazo", FX_ATTACK | FX_HEAL, 1, 0, 1, 0, "Su mano retorcida", "desgarra y absorbe.", "[D:1] [C:1]"},
    {1, "Zarpazo", FX_ATTACK | FX_HEAL, 1, 0, 1, 0, "Su mano retorcida", "desgarra y absorbe.", "[D:1] [C:1]"},
    {2, "Zarpazo", FX_ATTACK | FX_HEAL, 1, 0, 1, 0, "Su mano retorcida", "desgarra y absorbe.", "[D:1] [C:1]"},
    {3, "Zarpazo", FX_ATTACK | FX_HEAL, 1, 0, 1, 0, "Su mano retorcida", "desgarra y absorbe.", "[D:1] [C:1]"},
    {4, "Molinillazo", FX_ATTACK, 3, 0, 0, 0, "Patea con su pesada", "pierna de madera.", "[D:3]"},
    {5, "Molinillazo", FX_ATTACK, 3, 0, 0, 0, "Patea con su pesada", "pierna de madera.", "[D:3]"},
    {6, "Molinillazo", FX_ATTACK, 3, 0, 0, 0, "Patea con su pesada", "pierna de madera.", "[D:3]"},
    {7, "Molinillazo", FX_ATTACK, 3, 0, 0, 0, "Patea con su pesada", "pierna de madera.", "[D:3]"},
    {8, "Niebla Espesa", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "El manglar se cierra,", "ocultandola por completo.", "[E:1] [+Juega]"},
    {9, "Niebla Espesa", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "El manglar se cierra,", "ocultandola por completo.", "[E:1] [+Juega]"},
    {10, "Niebla Espesa", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "El manglar se cierra,", "ocultandola por completo.", "[E:1] [+Juega]"},
    {11, "Niebla Espesa", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "El manglar se cierra,", "ocultandola por completo.", "[E:1] [+Juega]"},
    {12, "Niebla Espesa", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "El manglar se cierra,", "ocultandola por completo.", "[E:1] [+Juega]"},
    {13, "Proteccion Lodo", FX_SHIELD, 0, 3, 0, 0, "Barro del pantano", "amortigua los golpes.", "[E:3]"},
    {14, "Proteccion Lodo", FX_SHIELD, 0, 3, 0, 0, "Barro del pantano", "amortigua los golpes.", "[E:3]"},
    {15, "Proteccion Lodo", FX_SHIELD, 0, 3, 0, 0, "Barro del pantano", "amortigua los golpes.", "[E:3]"},
    {16, "Proteccion Lodo", FX_SHIELD, 0, 3, 0, 0, "Barro del pantano", "amortigua los golpes.", "[E:3]"},
    {17, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado embrujado", "que restaura su vigor.", "[C:2 HP]"},
    {18, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado embrujado", "que restaura su vigor.", "[C:2 HP]"},
    {19, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado embrujado", "que restaura su vigor.", "[C:2 HP]"},
    {20, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado embrujado", "que restaura su vigor.", "[C:2 HP]"},
    {21, "Susurros", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Voces en la niebla que", "revelan secretos oscuros.", "[R:1] [+Juega]"},
    {22, "Susurros", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Voces en la niebla que", "revelan secretos oscuros.", "[R:1] [+Juega]"},
    {23, "Susurros", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Voces en la niebla que", "revelan secretos oscuros.", "[R:1] [+Juega]"},
    {24, "Susurros", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Voces en la niebla que", "revelan secretos oscuros.", "[R:1] [+Juega]"},
    {25, "Entundamiento", FX_HEAL | FX_ATTACK | FX_DRAW, 2, 0, 4, 1, "Hipnotiza a su presa", "en el fondo del bosque.", "[C:4] [D:2] [R:1]"},
    {26, "Maldicion del Manglar", FX_STEAL_HAND | FX_STEAL_DISCARD, 0, 0, 0, 0, "Pierdes todo", "lo que tenias.", "[Roba mano y descarte]"},
    {27, "Ilusion Maternal", FX_STEAL_DECK | FX_HEAL, 0, 0, 3, 0, "Finge ser tu madre", "para robar tu futuro.", "[C: 3] [Roba mazo rival]"},
};
const int TUNDA_DECK_SIZE = 28;

// MAZO DE Padre Almeida
const CardData CARTAS_ALMEIDA[] = {
    {0, "Guitarrazo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Un golpe rapido con", "su vieja guitarra.", "[D:1] [+Juega]"},
    {1, "Guitarrazo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Un golpe rapido con", "su vieja guitarra.", "[D:1] [+Juega]"},
    {2, "Guitarrazo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Un golpe rapido con", "su vieja guitarra.", "[D:1] [+Juega]"},
    {3, "Guitarrazo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Un golpe rapido con", "su vieja guitarra.", "[D:1] [+Juega]"},
    {4, "Botellazo", FX_ATTACK, 3, 0, 0, 0, "Vuela una botella vacia", "directo a la cabeza.", "[D:3]"},
    {5, "Botellazo", FX_ATTACK, 3, 0, 0, 0, "Vuela una botella vacia", "directo a la cabeza.", "[D:3]"},
    {6, "Botellazo", FX_ATTACK, 3, 0, 0, 0, "Vuela una botella vacia", "directo a la cabeza.", "[D:3]"},
    {7, "Botellazo", FX_ATTACK, 3, 0, 0, 0, "Vuela una botella vacia", "directo a la cabeza.", "[D:3]"},
    {8, "Sotana", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "La tela sagrada lo", "cubre mientras huye.", "[E:1] [R:1]"},
    {9, "Sotana", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "La tela sagrada lo", "cubre mientras huye.", "[E:1] [R:1]"},
    {10, "Sotana", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "La tela sagrada lo", "cubre mientras huye.", "[E:1] [R:1]"},
    {11, "Sotana", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "La tela sagrada lo", "cubre mientras huye.", "[E:1] [R:1]"},
    {12, "Sotana", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "La tela sagrada lo", "cubre mientras huye.", "[E:1] [R:1]"},
    {13, "Trago Bendito", FX_HEAL | FX_PLAY_AGAIN, 0, 0, 1, 0, "Un pequeno sorbo", "para seguir la fiesta.", "[C:1] [+Juega]"},
    {14, "Trago Bendito", FX_HEAL | FX_PLAY_AGAIN, 0, 0, 1, 0, "Un pequeno sorbo", "para seguir la fiesta.", "[C:1] [+Juega]"},
    {15, "Trago Bendito", FX_HEAL | FX_PLAY_AGAIN, 0, 0, 1, 0, "Un pequeno sorbo", "para seguir la fiesta.", "[C:1] [+Juega]"},
    {16, "Trago Bendito", FX_HEAL | FX_PLAY_AGAIN, 0, 0, 1, 0, "Un pequeno sorbo", "para seguir la fiesta.", "[C:1] [+Juega]"},
    {17, "Salida Secreta", FX_STEAL_DECK | FX_DRAW, 0, 0, 0, 2, "Conoce todos los atajos", "y descubre sus planes.", "[Roba: 1] [Roba mazo rival]"},
    {18, "Salida Secreta", FX_STEAL_DECK | FX_DRAW, 0, 0, 0, 2, "Conoce todos los atajos", "y descubre sus planes.", "[Roba: 1] [Roba mazo rival]"},
    {19, "Salida Secreta", FX_STEAL_DECK | FX_DRAW, 0, 0, 0, 2, "Conoce todos los atajos", "y descubre sus planes.", "[Roba: 1] [Roba mazo rival]"},
    {20, "Salida Secreta", FX_STEAL_DECK | FX_DRAW, 0, 0, 0, 2, "Conoce todos los atajos", "y descubre sus planes.", "[Roba: 1] [Roba mazo rival]"},
    {21, "Farra", FX_ATTACK | FX_DRAW, 2, 0, 0, 1, "Sigue la fiesta con", "golpes impredecibles.", "[D:2] [R:1]"},
    {22, "Farra", FX_ATTACK | FX_DRAW, 2, 0, 0, 1, "Sigue la fiesta con", "golpes impredecibles.", "[D:2] [R:1]"},
    {23, "Farra", FX_ATTACK | FX_DRAW, 2, 0, 0, 1, "Sigue la fiesta con", "golpes impredecibles.", "[D:2] [R:1]"},
    {24, "Farra", FX_ATTACK | FX_DRAW, 2, 0, 0, 1, "Sigue la fiesta con", "golpes impredecibles.", "[D:2] [R:1]"},
    {25, "Hasta la Vuelta!", FX_DRAW | FX_PLAY_AGAIN | FX_HEAL, 0, 0, 2, 2, "Pisa al Cristo y", "sale corriendo invencible.", "[R:2] [C:2] [+Juega]"},
    {26, "Escape Milagroso", FX_STEAL_HAND | FX_DRAW, 0, 0, 0, 2, "Esquiva tu ataque y", "huye con ventaja.", "[R: 2] [Roba de mano]"},
    {27, "Trago Robado", FX_STEAL_DISCARD | FX_HEAL | FX_PLAY_AGAIN, 0, 0, 2, 0, "Bebe de la botella", "que creias vacia.", "[C: 2] [Roba descarte] [+J]"},
};
const int ALMEIDA_DECK_SIZE = 28;

// MAZO DE Dama Tapada
const CardData CARTAS_DAMATAPADA[] = {
    {0, "Perfume Barato", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Aroma embriagador que", "desorienta al instante.", "[D:1] [+Juega]"},
    {1, "Perfume Barato", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Aroma embriagador que", "desorienta al instante.", "[D:1] [+Juega]"},
    {2, "Perfume Barato", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Aroma embriagador que", "desorienta al instante.", "[D:1] [+Juega]"},
    {3, "Perfume Barato", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Aroma embriagador que", "desorienta al instante.", "[D:1] [+Juega]"},
    {4, "Grito Aterrador", FX_ATTACK, 3, 0, 0, 0, "Un chillido agudo que", "hiela la sangre.", "[D:3]"},
    {5, "Grito Aterrador", FX_ATTACK, 3, 0, 0, 0, "Un chillido agudo que", "hiela la sangre.", "[D:3]"},
    {6, "Grito Aterrador", FX_ATTACK, 3, 0, 0, 0, "Un chillido agudo que", "hiela la sangre.", "[D:3]"},
    {7, "Grito Aterrador", FX_ATTACK, 3, 0, 0, 0, "Un chillido agudo que", "hiela la sangre.", "[D:3]"},
    {8, "Bruma Fria", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Una niebla oscura", "amortigua los golpes.", "[E:1] [R:1]"},
    {9, "Bruma Fria", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Una niebla oscura", "amortigua los golpes.", "[E:1] [R:1]"},
    {10, "Bruma Fria", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Una niebla oscura", "amortigua los golpes.", "[E:1] [R:1]"},
    {11, "Bruma Fria", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Una niebla oscura", "amortigua los golpes.", "[E:1] [R:1]"},
    {12, "Bruma Fria", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Una niebla oscura", "amortigua los golpes.", "[E:1] [R:1]"},
    {13, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil golpearla.", "[E:3]"},
    {14, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil golpearla.", "[E:3]"},
    {15, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil golpearla.", "[E:3]"},
    {16, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil golpearla.", "[E:3]"},
    {17, "Beso Frio", FX_HEAL, 0, 0, 2, 0, "Restaura su energia", "con magia negra.", "[C:2]"},
    {18, "Beso Frio", FX_HEAL, 0, 0, 2, 0, "Restaura su energia", "con magia negra.", "[C:2]"},
    {19, "Beso Frio", FX_HEAL, 0, 0, 2, 0, "Restaura su energia", "con magia negra.", "[C:2]"},
    {20, "Beso Frio", FX_HEAL, 0, 0, 2, 0, "Restaura su energia", "con magia negra.", "[C:2]"},
    {21, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae a incautos", "hacia su perdicion.", "[R:1] [+Juega]"},
    {22, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae a incautos", "hacia su perdicion.", "[R:1] [+Juega]"},
    {23, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae a incautos", "hacia su perdicion.", "[R:1] [+Juega]"},
    {24, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae a incautos", "hacia su perdicion.", "[R:1] [+Juega]"},
    {25, "Rostro Esqueletico", FX_ATTACK | FX_SHIELD, 4, 3, 0, 0, "Se quita el velo;", "el horror absoluto.", "[D:4] [E:3]"},
    {26, "Perfume Letal", FX_STEAL_DECK | FX_ATTACK, 4, 0, 0, 0, "El olor a muerte", "arruina tu destino.", "[D: 4] [Roba mazo rival]"},
    {27, "Mirada al Abismo", FX_STEAL_HAND | FX_STEAL_DECK, 0, 0, 0, 0, "El panico te", "hace perder la cabeza.", "[Roba mano y mazo]"},
};
const int DAMATAPADA_DECK_SIZE = 28;

// MAZO DE Maria Angula
const CardData CARTAS_MARIANGULA[] = {
    {0, "Tijeras", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Corta sin pensar", "en las consecuencias.", "[D:1] [+Juega]"},
    {1, "Tijeras", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Corta sin pensar", "en las consecuencias.", "[D:1] [+Juega]"},
    {2, "Tijeras", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Corta sin pensar", "en las consecuencias.", "[D:1] [+Juega]"},
    {3, "Tijeras", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Corta sin pensar", "en las consecuencias.", "[D:1] [+Juega]"},
    {4, "Olla Caliente", FX_ATTACK, 3, 0, 0, 0, "Lanza caldo hirviendo", "sin pensarlo dos veces.", "[D:3]"},
    {5, "Olla Caliente", FX_ATTACK, 3, 0, 0, 0, "Lanza caldo hirviendo", "sin pensarlo dos veces.", "[D:3]"},
    {6, "Olla Caliente", FX_ATTACK, 3, 0, 0, 0, "Lanza caldo hirviendo", "sin pensarlo dos veces.", "[D:3]"},
    {7, "Olla Caliente", FX_ATTACK, 3, 0, 0, 0, "Lanza caldo hirviendo", "sin pensarlo dos veces.", "[D:3]"},
    {8, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se esconde temblando", "bajo las mantas.", "[E:1] [+Juega]"},
    {9, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se esconde temblando", "bajo las mantas.", "[E:1] [+Juega]"},
    {10, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se esconde temblando", "bajo las mantas.", "[E:1] [+Juega]"},
    {11, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se esconde temblando", "bajo las mantas.", "[E:1] [+Juega]"},
    {12, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se esconde temblando", "bajo las mantas.", "[E:1] [+Juega]"},
    {13, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 1, "El terror la obliga", "a protegerse y pensar.", "[E:2] [R:1]"},
    {14, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 1, "El terror la obliga", "a protegerse y pensar.", "[E:2] [R:1]"},
    {15, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 1, "El terror la obliga", "a protegerse y pensar.", "[E:2] [R:1]"},
    {16, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 1, "El terror la obliga", "a protegerse y pensar.", "[E:2] [R:1]"},
    {17, "Robo de Tripas", FX_STEAL_DISCARD | FX_HEAL, 0, 0, 2, 0, "Saca algo util de", "la tumba del oponente.", "[C: 2] [Roba descarte]"},
    {18, "Robo de Tripas", FX_STEAL_DISCARD | FX_HEAL, 0, 0, 2, 0, "Saca algo util de", "la tumba del oponente.", "[C: 2] [Roba descarte]"},
    {19, "Robo de Tripas", FX_STEAL_DISCARD | FX_HEAL, 0, 0, 2, 0, "Saca algo util de", "la tumba del oponente.", "[C: 2] [Roba descarte]"},
    {20, "Robo de Tripas", FX_STEAL_DISCARD | FX_HEAL, 0, 0, 2, 0, "Saca algo util de", "la tumba del oponente.", "[C: 2] [Roba descarte]"},
    {21, "Grito de Culpa", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Su llanto aterra y", "le da nuevas ideas.", "[R:1] [+Juega]"},
    {22, "Grito de Culpa", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Su llanto aterra y", "le da nuevas ideas.", "[R:1] [+Juega]"},
    {23, "Grito de Culpa", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Su llanto aterra y", "le da nuevas ideas.", "[R:1] [+Juega]"},
    {24, "Grito de Culpa", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Su llanto aterra y", "le da nuevas ideas.", "[R:1] [+Juega]"},
    {25, "Sopa Macabra", FX_ATTACK | FX_HEAL | FX_PLAY_AGAIN, 4, 0, 2, 0, "Cocina el mal y", "se fortalece.", "[D:4] [C:2] [+Juega]"},
    {26, "Sopa de Robos", FX_STEAL_DISCARD | FX_STEAL_HAND, 0, 0, 0, 0, "Saca ingredientes", "de donde sea.", "[Roba mano y descarte]"},
    {27, "Berrinche Mortal", FX_STEAL_DECK | FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Destruye todo", "a su paso.", "[D: 2] [Roba mazo] [+J]"},
};
const int MARIANGULA_DECK_SIZE = 28;

// MAZO DE Gallo Catedral
const CardData CARTAS_GALLO[] = {
    {0, "Picotazo Rapido", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Un golpe veloz", "con su pico de oro.", "[D:1] [+Juega]"},
    {1, "Picotazo Rapido", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Un golpe veloz", "con su pico de oro.", "[D:1] [+Juega]"},
    {2, "Picotazo Rapido", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Un golpe veloz", "con su pico de oro.", "[D:1] [+Juega]"},
    {3, "Picotazo Rapido", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Un golpe veloz", "con su pico de oro.", "[D:1] [+Juega]"},
    {4, "Espolon", FX_ATTACK, 3, 0, 0, 0, "Un corte profundo", "con sus garras afiladas.", "[D:3]"},
    {5, "Espolon", FX_ATTACK, 3, 0, 0, 0, "Un corte profundo", "con sus garras afiladas.", "[D:3]"},
    {6, "Espolon", FX_ATTACK, 3, 0, 0, 0, "Un corte profundo", "con sus garras afiladas.", "[D:3]"},
    {7, "Espolon", FX_ATTACK, 3, 0, 0, 0, "Un corte profundo", "con sus garras afiladas.", "[D:3]"},
    {8, "Vuelo Corto", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aletea rapidamente", "para tomar ventaja.", "[E:1] [+Juega]"},
    {9, "Vuelo Corto", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aletea rapidamente", "para tomar ventaja.", "[E:1] [+Juega]"},
    {10, "Vuelo Corto", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aletea rapidamente", "para tomar ventaja.", "[E:1] [+Juega]"},
    {11, "Vuelo Corto", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aletea rapidamente", "para tomar ventaja.", "[E:1] [+Juega]"},
    {12, "Vuelo Corto", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aletea rapidamente", "para tomar ventaja.", "[E:1] [+Juega]"},
    {13, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de metal", "rechaza los impactos.", "[E:3]"},
    {14, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de metal", "rechaza los impactos.", "[E:3]"},
    {15, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de metal", "rechaza los impactos.", "[E:3]"},
    {16, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de metal", "rechaza los impactos.", "[E:3]"},
    {17, "Pluma Dorada", FX_HEAL, 0, 0, 2, 0, "Brillo sanador que", "restaura su bronce.", "[C:2 HP]"},
    {18, "Pluma Dorada", FX_HEAL, 0, 0, 2, 0, "Brillo sanador que", "restaura su bronce.", "[C:2 HP]"},
    {19, "Pluma Dorada", FX_HEAL, 0, 0, 2, 0, "Brillo sanador que", "restaura su bronce.", "[C:2 HP]"},
    {20, "Pluma Dorada", FX_HEAL, 0, 0, 2, 0, "Brillo sanador que", "restaura su bronce.", "[C:2 HP]"},
    {21, "Canto Matutino", FX_DRAW | FX_HEAL, 0, 0, 1, 2, "Anuncia el amanecer,", "renovando su fuerza.", "[C:1] [R:2]"},
    {22, "Canto Matutino", FX_DRAW | FX_HEAL, 0, 0, 1, 2, "Anuncia el amanecer,", "renovando su fuerza.", "[C:1] [R:2]"},
    {23, "Canto Matutino", FX_DRAW | FX_HEAL, 0, 0, 1, 2, "Anuncia el amanecer,", "renovando su fuerza.", "[C:1] [R:2]"},
    {24, "Canto Matutino", FX_DRAW | FX_HEAL, 0, 0, 1, 2, "Anuncia el amanecer,", "renovando su fuerza.", "[C:1] [R:2]"},
    {25, "Ira de la Catedral", FX_ATTACK | FX_SHIELD | FX_HEAL, 3, 3, 3, 0, "El monumento despierta", "castigando al blasfemo.", "[D:3] [E:3] [C:3]"},
    {26, "Canto Hipnotico", FX_STEAL_HAND | FX_SHIELD, 0, 3, 0, 0, "Te aturde mientras", "se protege.", "[E: 3] [Roba de mano]"},
    {27, "Brillo Cegador", FX_STEAL_DISCARD | FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Resplandece y toma", "la iniciativa.", "[R: 1] [Roba descarte] [+J]"},
};
const int GALLO_DECK_SIZE = 28;

// MAZO DE Cura sin Cabeza
const CardData CARTAS_CURA[] = {
    {0, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Palabras sin voz", "que destruyen la mente.", "[D:1] [+Juega]"},
    {1, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Palabras sin voz", "que destruyen la mente.", "[D:1] [+Juega]"},
    {2, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Palabras sin voz", "que destruyen la mente.", "[D:1] [+Juega]"},
    {3, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Palabras sin voz", "que destruyen la mente.", "[D:1] [+Juega]"},
    {4, "Llama Negra", FX_ATTACK, 3, 0, 0, 0, "Fuego del purgatorio", "que quema el alma.", "[D:3]"},
    {5, "Llama Negra", FX_ATTACK, 3, 0, 0, 0, "Fuego del purgatorio", "que quema el alma.", "[D:3]"},
    {6, "Llama Negra", FX_ATTACK, 3, 0, 0, 0, "Fuego del purgatorio", "que quema el alma.", "[D:3]"},
    {7, "Llama Negra", FX_ATTACK, 3, 0, 0, 0, "Fuego del purgatorio", "que quema el alma.", "[D:3]"},
    {8, "Levitacion", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Flota amenazante", "sobre el empedrado.", "[E:1] [R:1]"},
    {9, "Levitacion", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Flota amenazante", "sobre el empedrado.", "[E:1] [R:1]"},
    {10, "Levitacion", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Flota amenazante", "sobre el empedrado.", "[E:1] [R:1]"},
    {11, "Levitacion", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Flota amenazante", "sobre el empedrado.", "[E:1] [R:1]"},
    {12, "Levitacion", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Flota amenazante", "sobre el empedrado.", "[E:1] [R:1]"},
    {13, "Aparicion", FX_SHIELD, 0, 3, 0, 0, "Se vuelve incorporeo,", "imposible de tocar.", "[E:3]"},
    {14, "Aparicion", FX_SHIELD, 0, 3, 0, 0, "Se vuelve incorporeo,", "imposible de tocar.", "[E:3]"},
    {15, "Aparicion", FX_SHIELD, 0, 3, 0, 0, "Se vuelve incorporeo,", "imposible de tocar.", "[E:3]"},
    {16, "Aparicion", FX_SHIELD, 0, 3, 0, 0, "Se vuelve incorporeo,", "imposible de tocar.", "[E:3]"},
    {17, "Aura Espectral", FX_HEAL, 0, 0, 2, 0, "Un frio de ultratumba", "lo rodea por completo.", "[C:2]"},
    {18, "Aura Espectral", FX_HEAL, 0, 0, 2, 0, "Un frio de ultratumba", "lo rodea por completo.", "[C:2]"},
    {19, "Aura Espectral", FX_HEAL, 0, 0, 2, 0, "Un frio de ultratumba", "lo rodea por completo.", "[C:2]"},
    {20, "Aura Espectral", FX_HEAL, 0, 0, 2, 0, "Un frio de ultratumba", "lo rodea por completo.", "[C:2]"},
    {21, "Busqueda de Cabeza", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Vaga buscando partes", "de su cuerpo perdido.", "[R:1] [+Juega]"},
    {22, "Busqueda de Cabeza", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Vaga buscando partes", "de su cuerpo perdido.", "[R:1] [+Juega]"},
    {23, "Busqueda de Cabeza", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Vaga buscando partes", "de su cuerpo perdido.", "[R:1] [+Juega]"},
    {24, "Busqueda de Cabeza", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Vaga buscando partes", "de su cuerpo perdido.", "[R:1] [+Juega]"},
    {25, "Misa de Medianoche", FX_ATTACK | FX_DRAW | FX_PLAY_AGAIN, 4, 0, 0, 2, "Un ritual profano", "que condena al enemigo.", "[D:4] [R:2] [+Juega]"},
    {26, "Fuego del Purgatorio", FX_STEAL_DECK | FX_ATTACK, 5, 0, 0, 0, "Quema tu esperanza.", "", "[D: 5] [Roba mazo rival]"},
    {27, "Exorcismo Inverso", FX_STEAL_HAND | FX_HEAL, 0, 0, 4, 0, "Te drena el alma.", "", "[C: 4] [Roba de mano]"},
};
const int CURA_DECK_SIZE = 28;

// MAZO DE El Chuzalongo
const CardData CARTAS_CHUZALONGO[] = {
    {0, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Ataca a todos lados", "sin mirar a quien.", "[D:1] [+Juega]"},
    {1, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Ataca a todos lados", "sin mirar a quien.", "[D:1] [+Juega]"},
    {2, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Ataca a todos lados", "sin mirar a quien.", "[D:1] [+Juega]"},
    {3, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Ataca a todos lados", "sin mirar a quien.", "[D:1] [+Juega]"},
    {4, "Garras Paramo", FX_ATTACK, 3, 0, 0, 0, "Zarpazos sangrientos", "tejidos de rencor.", "[D:3]"},
    {5, "Garras Paramo", FX_ATTACK, 3, 0, 0, 0, "Zarpazos sangrientos", "tejidos de rencor.", "[D:3]"},
    {6, "Garras Paramo", FX_ATTACK, 3, 0, 0, 0, "Zarpazos sangrientos", "tejidos de rencor.", "[D:3]"},
    {7, "Garras Paramo", FX_ATTACK, 3, 0, 0, 0, "Zarpazos sangrientos", "tejidos de rencor.", "[D:3]"},
    {8, "Instinto Animal", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Olfatea la sangre", "y actua sin dudar.", "[E:1] [+Juega]"},
    {9, "Instinto Animal", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Olfatea la sangre", "y actua sin dudar.", "[E:1] [+Juega]"},
    {10, "Instinto Animal", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Olfatea la sangre", "y actua sin dudar.", "[E:1] [+Juega]"},
    {11, "Instinto Animal", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Olfatea la sangre", "y actua sin dudar.", "[E:1] [+Juega]"},
    {12, "Instinto Animal", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Olfatea la sangre", "y actua sin dudar.", "[E:1] [+Juega]"},
    {13, "Piel Gruesa", FX_SHIELD, 0, 2, 0, 1, "El lodo y musgo", "amortiguan un poco.", "[E:2] [R:1]"},
    {14, "Piel Gruesa", FX_SHIELD, 0, 2, 0, 1, "El lodo y musgo", "amortiguan un poco.", "[E:2] [R:1]"},
    {15, "Piel Gruesa", FX_SHIELD, 0, 2, 0, 1, "El lodo y musgo", "amortiguan un poco.", "[E:2] [R:1]"},
    {16, "Piel Gruesa", FX_SHIELD, 0, 2, 0, 1, "El lodo y musgo", "amortiguan un poco.", "[E:2] [R:1]"},
    {17, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta de lo que", "encuentra en la montana.", "[C:2 HP]"},
    {18, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta de lo que", "encuentra en la montana.", "[C:2 HP]"},
    {19, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta de lo que", "encuentra en la montana.", "[C:2 HP]"},
    {20, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta de lo que", "encuentra en la montana.", "[C:2 HP]"},
    {21, "Aullido", FX_DRAW | FX_ATTACK, 2, 0, 0, 1, "Un grito desgarrador", "que paraliza al enemigo.", "[D:2] [R:1]"},
    {22, "Aullido", FX_DRAW | FX_ATTACK, 2, 0, 0, 1, "Un grito desgarrador", "que paraliza al enemigo.", "[D:2] [R:1]"},
    {23, "Aullido", FX_DRAW | FX_ATTACK, 2, 0, 0, 1, "Un grito desgarrador", "que paraliza al enemigo.", "[D:2] [R:1]"},
    {24, "Aullido", FX_DRAW | FX_ATTACK, 2, 0, 0, 1, "Un grito desgarrador", "que paraliza al enemigo.", "[D:2] [R:1]"},
    {25, "Mordida Salvaje", FX_ATTACK | FX_HEAL | FX_PLAY_AGAIN, 4, 0, 2, 0, "Muerde la yugular", "con furia animal.", "[D:4] [C:2] [+Juega]"},
    {26, "Ataque Furtivo", FX_STEAL_HAND | FX_ATTACK, 4, 0, 0, 0, "Muerde y se roba", "lo que caiga.", "[D: 4] [Roba de mano]"},
    {27, "Carrona", FX_STEAL_DISCARD | FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Se alimenta de tus", "restos.", "[C: 2] [R: 1] [Roba desc]"},
};
const int CHUZALONGO_DECK_SIZE = 28;

// MAZO DE La Llorona
const CardData CARTAS_LLORONA[] = {
    {0, "Lagrimas", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "El dolor le ensena", "nuevas formas de sufrir.", "[D:1] [+Juega]"},
    {1, "Lagrimas", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "El dolor le ensena", "nuevas formas de sufrir.", "[D:1] [+Juega]"},
    {2, "Lagrimas", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "El dolor le ensena", "nuevas formas de sufrir.", "[D:1] [+Juega]"},
    {3, "Lagrimas", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "El dolor le ensena", "nuevas formas de sufrir.", "[D:1] [+Juega]"},
    {4, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Un grito de lamento", "que te rompe los timpanos.", "[D:3]"},
    {5, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Un grito de lamento", "que te rompe los timpanos.", "[D:3]"},
    {6, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Un grito de lamento", "que te rompe los timpanos.", "[D:3]"},
    {7, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Un grito de lamento", "que te rompe los timpanos.", "[D:3]"},
    {8, "Manto Blanco", FX_SHIELD | FX_HEAL, 0, 1, 1, 0, "Su tunica espectral", "rechaza los ataques.", "[E:1] [C:1]"},
    {9, "Manto Blanco", FX_SHIELD | FX_HEAL, 0, 1, 1, 0, "Su tunica espectral", "rechaza los ataques.", "[E:1] [C:1]"},
    {10, "Manto Blanco", FX_SHIELD | FX_HEAL, 0, 1, 1, 0, "Su tunica espectral", "rechaza los ataques.", "[E:1] [C:1]"},
    {11, "Manto Blanco", FX_SHIELD | FX_HEAL, 0, 1, 1, 0, "Su tunica espectral", "rechaza los ataques.", "[E:1] [C:1]"},
    {12, "Manto Blanco", FX_SHIELD | FX_HEAL, 0, 1, 1, 0, "Su tunica espectral", "rechaza los ataques.", "[E:1] [C:1]"},
    {13, "Rio Desbordado", FX_SHIELD, 0, 3, 0, 0, "Aguas violentas te", "arrastran lejos de ella.", "[E:3]"},
    {14, "Rio Desbordado", FX_SHIELD, 0, 3, 0, 0, "Aguas violentas te", "arrastran lejos de ella.", "[E:3]"},
    {15, "Rio Desbordado", FX_SHIELD, 0, 3, 0, 0, "Aguas violentas te", "arrastran lejos de ella.", "[E:3]"},
    {16, "Rio Desbordado", FX_SHIELD, 0, 3, 0, 0, "Aguas violentas te", "arrastran lejos de ella.", "[E:3]"},
    {17, "Consuelo Vano", FX_HEAL, 0, 0, 2, 0, "Se engana pensando", "que aun estan vivos.", "[C:2]"},
    {18, "Consuelo Vano", FX_HEAL, 0, 0, 2, 0, "Se engana pensando", "que aun estan vivos.", "[C:2]"},
    {19, "Consuelo Vano", FX_HEAL, 0, 0, 2, 0, "Se engana pensando", "que aun estan vivos.", "[C:2]"},
    {20, "Consuelo Vano", FX_HEAL, 0, 0, 2, 0, "Se engana pensando", "que aun estan vivos.", "[C:2]"},
    {21, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[R:1] [+Juega]"},
    {22, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[R:1] [+Juega]"},
    {23, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[R:1] [+Juega]"},
    {24, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[R:1] [+Juega]"},
    {25, "Ahogo Profundo", FX_HEAL | FX_SHIELD | FX_ATTACK, 2, 4, 4, 0, "Te sumerge en su", "eterno sufrimiento.", "[C:4] [E:4] [D:2]"},
    {26, "Llanto Ahogado", FX_STEAL_DECK | FX_SHIELD, 0, 4, 0, 0, "Sus lagrimas forman", "una barrera.", "[E: 4] [Roba mazo rival]"},
    {27, "Arrastrar al Fondo", FX_STEAL_DISCARD | FX_ATTACK | FX_HEAL, 2, 0, 2, 0, "Te hunde con ella.", "", "[D: 2] [C: 2] [Roba desc]"},
};
const int LLORONA_DECK_SIZE = 28;

// MAZO DE Guagua Auca
const CardData CARTAS_GUAGUAAUCA[] = {
    {0, "Lloriqueo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Finge estar indefenso", "para atacarte de pronto.", "[D:1] [+Juega]"},
    {1, "Lloriqueo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Finge estar indefenso", "para atacarte de pronto.", "[D:1] [+Juega]"},
    {2, "Lloriqueo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Finge estar indefenso", "para atacarte de pronto.", "[D:1] [+Juega]"},
    {3, "Lloriqueo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Finge estar indefenso", "para atacarte de pronto.", "[D:1] [+Juega]"},
    {4, "Sorpresa Maligna", FX_ATTACK, 3, 0, 0, 0, "Revela su verdadera", "forma aterradora.", "[D:3]"},
    {5, "Sorpresa Maligna", FX_ATTACK, 3, 0, 0, 0, "Revela su verdadera", "forma aterradora.", "[D:3]"},
    {6, "Sorpresa Maligna", FX_ATTACK, 3, 0, 0, 0, "Revela su verdadera", "forma aterradora.", "[D:3]"},
    {7, "Sorpresa Maligna", FX_ATTACK, 3, 0, 0, 0, "Revela su verdadera", "forma aterradora.", "[D:3]"},
    {8, "Panales", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Usa su apariencia", "inocente como defensa.", "[E:1] [+Juega]"},
    {9, "Panales", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Usa su apariencia", "inocente como defensa.", "[E:1] [+Juega]"},
    {10, "Panales", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Usa su apariencia", "inocente como defensa.", "[E:1] [+Juega]"},
    {11, "Panales", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Usa su apariencia", "inocente como defensa.", "[E:1] [+Juega]"},
    {12, "Panales", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Usa su apariencia", "inocente como defensa.", "[E:1] [+Juega]"},
    {13, "Inocencia Fingida", FX_STEAL_HAND | FX_SHIELD, 0, 2, 0, 1, "Te da compasion y", "te roba lo que tienes.", "[E: 2] [Roba de mano]"},
    {14, "Inocencia Fingida", FX_STEAL_HAND | FX_SHIELD, 0, 2, 0, 1, "Te da compasion y", "te roba lo que tienes.", "[E: 2] [Roba de mano]"},
    {15, "Inocencia Fingida", FX_STEAL_HAND | FX_SHIELD, 0, 2, 0, 1, "Te da compasion y", "te roba lo que tienes.", "[E: 2] [Roba de mano]"},
    {16, "Inocencia Fingida", FX_STEAL_HAND | FX_SHIELD, 0, 2, 0, 1, "Te da compasion y", "te roba lo que tienes.", "[E: 2] [Roba de mano]"},
    {17, "Biberon de Sangre", FX_HEAL, 0, 0, 2, 0, "Se alimenta de tu", "piedad.", "[C:2]"},
    {18, "Biberon de Sangre", FX_HEAL, 0, 0, 2, 0, "Se alimenta de tu", "piedad.", "[C:2]"},
    {19, "Biberon de Sangre", FX_HEAL, 0, 0, 2, 0, "Se alimenta de tu", "piedad.", "[C:2]"},
    {20, "Biberon de Sangre", FX_HEAL, 0, 0, 2, 0, "Se alimenta de tu", "piedad.", "[C:2]"},
    {21, "Risa Macabra", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Se burla de ti", "mientras toma ventaja.", "[R:1] [+Juega]"},
    {22, "Risa Macabra", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Se burla de ti", "mientras toma ventaja.", "[R:1] [+Juega]"},
    {23, "Risa Macabra", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Se burla de ti", "mientras toma ventaja.", "[R:1] [+Juega]"},
    {24, "Risa Macabra", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Se burla de ti", "mientras toma ventaja.", "[R:1] [+Juega]"},
    {25, "Dientes de Diablo", FX_ATTACK | FX_DRAW | FX_PLAY_AGAIN, 4, 0, 0, 2, "Muerde el cuello de", "quien lo carga.", "[D:4] [R:2] [+Juega]"},
    {26, "Berrinche Infernal", FX_STEAL_DECK | FX_STEAL_DISCARD, 0, 0, 0, 0, "Un demonio desatado", "robando por doquier.", "[Roba mazo y descarte]"},
    {27, "Muerde Dedos", FX_STEAL_HAND | FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Engana y ataca", "muy rapido.", "[D: 2] [Roba mano] [+J]"},
};
const int GUAGUAAUCA_DECK_SIZE = 28;

// MAZO DE Viuda Tamarindo
const CardData CARTAS_VIUDA[] = {
    {0, "Ilusion", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Crees ver a alguien mas", "y bajas la guardia.", "[D:1] [+Juega]"},
    {1, "Ilusion", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Crees ver a alguien mas", "y bajas la guardia.", "[D:1] [+Juega]"},
    {2, "Ilusion", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Crees ver a alguien mas", "y bajas la guardia.", "[D:1] [+Juega]"},
    {3, "Ilusion", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Crees ver a alguien mas", "y bajas la guardia.", "[D:1] [+Juega]"},
    {4, "Borracho Perdido", FX_ATTACK, 3, 0, 0, 0, "Engana a sus victimas", "hasta dejarlas vacias.", "[D:3]"},
    {5, "Borracho Perdido", FX_ATTACK, 3, 0, 0, 0, "Engana a sus victimas", "hasta dejarlas vacias.", "[D:3]"},
    {6, "Borracho Perdido", FX_ATTACK, 3, 0, 0, 0, "Engana a sus victimas", "hasta dejarlas vacias.", "[D:3]"},
    {7, "Borracho Perdido", FX_ATTACK, 3, 0, 0, 0, "Engana a sus victimas", "hasta dejarlas vacias.", "[D:3]"},
    {8, "Aroma Dulce", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Atrae a incautos", "hacia su trampa mortal.", "[E:1] [+Juega]"},
    {9, "Aroma Dulce", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Atrae a incautos", "hacia su trampa mortal.", "[E:1] [+Juega]"},
    {10, "Aroma Dulce", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Atrae a incautos", "hacia su trampa mortal.", "[E:1] [+Juega]"},
    {11, "Aroma Dulce", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Atrae a incautos", "hacia su trampa mortal.", "[E:1] [+Juega]"},
    {12, "Aroma Dulce", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Atrae a incautos", "hacia su trampa mortal.", "[E:1] [+Juega]"},
    {13, "Sombra del Arbol", FX_SHIELD, 0, 3, 0, 0, "Las ramas del viejo", "tamarindo la protegen.", "[E:3]"},
    {14, "Sombra del Arbol", FX_SHIELD, 0, 3, 0, 0, "Las ramas del viejo", "tamarindo la protegen.", "[E:3]"},
    {15, "Sombra del Arbol", FX_SHIELD, 0, 3, 0, 0, "Las ramas del viejo", "tamarindo la protegen.", "[E:3]"},
    {16, "Sombra del Arbol", FX_SHIELD, 0, 3, 0, 0, "Las ramas del viejo", "tamarindo la protegen.", "[E:3]"},
    {17, "Pasion Falsa", FX_HEAL, 0, 0, 2, 0, "Un beso embrujado", "que sana a la viuda.", "[C:2 HP]"},
    {18, "Pasion Falsa", FX_HEAL, 0, 0, 2, 0, "Un beso embrujado", "que sana a la viuda.", "[C:2 HP]"},
    {19, "Pasion Falsa", FX_HEAL, 0, 0, 2, 0, "Un beso embrujado", "que sana a la viuda.", "[C:2 HP]"},
    {20, "Pasion Falsa", FX_HEAL, 0, 0, 2, 0, "Un beso embrujado", "que sana a la viuda.", "[C:2 HP]"},
    {21, "Velo Negro", FX_STEAL_HAND | FX_PLAY_AGAIN, 0, 0, 0, 1, "Te nubla la mente y", "pierdes tu mejor carta.", "[Roba de mano] [+Juega]"},
    {22, "Velo Negro", FX_STEAL_HAND | FX_PLAY_AGAIN, 0, 0, 0, 1, "Te nubla la mente y", "pierdes tu mejor carta.", "[Roba de mano] [+Juega]"},
    {23, "Velo Negro", FX_STEAL_HAND | FX_PLAY_AGAIN, 0, 0, 0, 1, "Te nubla la mente y", "pierdes tu mejor carta.", "[Roba de mano] [+Juega]"},
    {24, "Velo Negro", FX_STEAL_HAND | FX_PLAY_AGAIN, 0, 0, 0, 1, "Te nubla la mente y", "pierdes tu mejor carta.", "[Roba de mano] [+Juega]"},
    {25, "Abrazo de Muerte", FX_ATTACK | FX_HEAL | FX_SHIELD, 4, 2, 3, 0, "Te abraza fuerte", "hasta asfixiarte.", "[D:4] [C:3] [E:2]"},
    {26, "Seduccion Oscura", FX_STEAL_DECK | FX_STEAL_HAND, 0, 0, 0, 0, "El engano perfecto.", "", "[Roba mazo y mano]"},
    {27, "Asfixia", FX_STEAL_DISCARD | FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Te roba el aire y", "tus recuerdos.", "[D: 3] [Roba desc] [+J]"},
};
const int VIUDA_DECK_SIZE = 28;

