#include "card.h"

// =====================================================
// MAZO DE CANTUNA (28 cartas)
// Estilo: Tanque/Constructor - Muchos escudos y golpes fuertes
// =====================================================
const CardData CARTAS_CANTUNA[] = {
    // Ataques puros (8 cartas)
    {0, "Ladrillazo", FX_ATTACK, 3, 0, 0, 0,
     "Cantuna arroja un ladrillo",
     "de la iglesia inconclusa.",
     "Dano: 3"},
    {0, "Ladrillazo", FX_ATTACK, 3, 0, 0, 0,
     "Cantuna arroja un ladrillo",
     "de la iglesia inconclusa.",
     "Dano: 3"},
    {0, "Ladrillazo", FX_ATTACK, 3, 0, 0, 0,
     "Cantuna arroja un ladrillo",
     "de la iglesia inconclusa.",
     "Dano: 3"},
    {1, "Golpe de Piedra", FX_ATTACK, 2, 0, 0, 0,
     "Una piedra tallada a mano",
     "por el legendario constructor.",
     "Dano: 2"},
    {1, "Golpe de Piedra", FX_ATTACK, 2, 0, 0, 0,
     "Una piedra tallada a mano",
     "por el legendario constructor.",
     "Dano: 2"},
    {1, "Golpe de Piedra", FX_ATTACK, 2, 0, 0, 0,
     "Una piedra tallada a mano",
     "por el legendario constructor.",
     "Dano: 2"},
    {2, "Avalancha", FX_ATTACK, 5, 0, 0, 0,
     "La montana entera cae sobre",
     "el enemigo. El poder del",
     "Pichincha. Dano: 5"},
    {2, "Avalancha", FX_ATTACK, 5, 0, 0, 0,
     "La montana entera cae sobre",
     "el enemigo. El poder del",
     "Pichincha. Dano: 5"},

    // Escudos (6 cartas)
    {3, "Muro de Piedra", FX_SHIELD, 0, 2, 0, 0,
     "Los muros de San Francisco",
     "protegen a su constructor.",
     "Escudo: 2"},
    {3, "Muro de Piedra", FX_SHIELD, 0, 2, 0, 0,
     "Los muros de San Francisco",
     "protegen a su constructor.",
     "Escudo: 2"},
    {3, "Muro de Piedra", FX_SHIELD, 0, 2, 0, 0,
     "Los muros de San Francisco",
     "protegen a su constructor.",
     "Escudo: 2"},
    {4, "Fortaleza", FX_SHIELD, 0, 3, 0, 0,
     "Cantuna levanta una fortaleza",
     "en un solo turno. Ni el",
     "diablo la derriba. Escudo: 3"},
    {4, "Fortaleza", FX_SHIELD, 0, 3, 0, 0,
     "Cantuna levanta una fortaleza",
     "en un solo turno. Ni el",
     "diablo la derriba. Escudo: 3"},
    {4, "Fortaleza", FX_SHIELD, 0, 3, 0, 0,
     "Cantuna levanta una fortaleza",
     "en un solo turno. Ni el",
     "diablo la derriba. Escudo: 3"},

    // Curacion (4 cartas)
    {5, "Descanso", FX_HEAL, 0, 0, 2, 0,
     "Cantuna descansa tras horas",
     "de construir sin parar.",
     "Cura: 2 HP"},
    {5, "Descanso", FX_HEAL, 0, 0, 2, 0,
     "Cantuna descansa tras horas",
     "de construir sin parar.",
     "Cura: 2 HP"},
    {6, "Pacto Diabolico", FX_HEAL, 0, 0, 4, 0,
     "El diablo le dio poder a",
     "cambio de su alma... pero",
     "Cantuna es mas listo. Cura: 4"},
    {6, "Pacto Diabolico", FX_HEAL, 0, 0, 4, 0,
     "El diablo le dio poder a",
     "cambio de su alma... pero",
     "Cantuna es mas listo. Cura: 4"},

    // Robo de cartas (4 cartas)
    {7, "Planos Secretos", FX_DRAW, 0, 0, 0, 2,
     "Los planos originales de la",
     "iglesia revelan nuevas",
     "estrategias. Roba: 2"},
    {7, "Planos Secretos", FX_DRAW, 0, 0, 0, 2,
     "Los planos originales de la",
     "iglesia revelan nuevas",
     "estrategias. Roba: 2"},
    {8, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1,
     "La genialidad del constructor",
     "no para. Roba 1 carta y",
     "juega otra vez!"},
    {8, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1,
     "La genialidad del constructor",
     "no para. Roba 1 carta y",
     "juega otra vez!"},

    // Combos (6 cartas)
    {9, "Contraataque", FX_ATTACK | FX_SHIELD, 2, 1, 0, 0,
     "Cantuna golpea y levanta un",
     "muro en el mismo movimiento.",
     "Dano: 2 + Escudo: 1"},
    {9, "Contraataque", FX_ATTACK | FX_SHIELD, 2, 1, 0, 0,
     "Cantuna golpea y levanta un",
     "muro en el mismo movimiento.",
     "Dano: 2 + Escudo: 1"},
    {10, "Furia Constructor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0,
     "La furia de construir contra",
     "reloj lo hace imparable.",
     "Dano: 2 + Juega otra vez!"},
    {10, "Furia Constructor", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0,
     "La furia de construir contra",
     "reloj lo hace imparable.",
     "Dano: 2 + Juega otra vez!"},
    {11, "Bendicion Oscura", FX_HEAL | FX_DRAW, 0, 0, 2, 1,
     "El diablo cumple su parte",
     "del trato... por ahora.",
     "Cura: 2 + Roba: 1"},
    {11, "Bendicion Oscura", FX_HEAL | FX_DRAW, 0, 0, 2, 1,
     "El diablo cumple su parte",
     "del trato... por ahora.",
     "Cura: 2 + Roba: 1"},
};
const int CANTUNA_DECK_SIZE = 28;

// =====================================================
// MAZO DE EL TIN TIN (28 cartas)
// Estilo: Agresor/Rapido - Muchos ataques y combos
// =====================================================
const CardData CARTAS_TINTIN[] = {
    // Ataques (10 cartas)
    {20, "Travesura", FX_ATTACK, 2, 0, 0, 0,
     "El duende esconde tus cosas",
     "y te da un golpe mientras",
     "las buscas. Dano: 2"},
    {20, "Travesura", FX_ATTACK, 2, 0, 0, 0,
     "El duende esconde tus cosas",
     "y te da un golpe mientras",
     "las buscas. Dano: 2"},
    {20, "Travesura", FX_ATTACK, 2, 0, 0, 0,
     "El duende esconde tus cosas",
     "y te da un golpe mientras",
     "las buscas. Dano: 2"},
    {20, "Travesura", FX_ATTACK, 2, 0, 0, 0,
     "El duende esconde tus cosas",
     "y te da un golpe mientras",
     "las buscas. Dano: 2"},
    {21, "Sombrerazo", FX_ATTACK, 3, 0, 0, 0,
     "El sombrero gigante del Tin",
     "Tin golpea como un martillo.",
     "Dano: 3"},
    {21, "Sombrerazo", FX_ATTACK, 3, 0, 0, 0,
     "El sombrero gigante del Tin",
     "Tin golpea como un martillo.",
     "Dano: 3"},
    {21, "Sombrerazo", FX_ATTACK, 3, 0, 0, 0,
     "El sombrero gigante del Tin",
     "Tin golpea como un martillo.",
     "Dano: 3"},
    {22, "Emboscada", FX_ATTACK, 4, 0, 0, 0,
     "Aparece de la nada en los",
     "caminos oscuros de la sierra.",
     "Dano: 4"},
    {22, "Emboscada", FX_ATTACK, 4, 0, 0, 0,
     "Aparece de la nada en los",
     "caminos oscuros de la sierra.",
     "Dano: 4"},
    {22, "Emboscada", FX_ATTACK, 4, 0, 0, 0,
     "Aparece de la nada en los",
     "caminos oscuros de la sierra.",
     "Dano: 4"},

    // Escudos (3 cartas)
    {23, "Escondite", FX_SHIELD, 0, 1, 0, 0,
     "Se esconde bajo su enorme",
     "sombrero. Dificil de golpear.",
     "Escudo: 1"},
    {23, "Escondite", FX_SHIELD, 0, 1, 0, 0,
     "Se esconde bajo su enorme",
     "sombrero. Dificil de golpear.",
     "Escudo: 1"},
    {23, "Escondite", FX_SHIELD, 0, 1, 0, 0,
     "Se esconde bajo su enorme",
     "sombrero. Dificil de golpear.",
     "Escudo: 1"},

    // Curacion (2 cartas)
    {24, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0,
     "Descansa un momento para",
     "planear su proxima travesura.",
     "Cura: 2 HP"},
    {24, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0,
     "Descansa un momento para",
     "planear su proxima travesura.",
     "Cura: 2 HP"},

    // Robo y velocidad (7 cartas)
    {25, "Robo de Bolsillos", FX_DRAW, 0, 0, 0, 2,
     "Sus manos rapidas le quitan",
     "los recursos al enemigo.",
     "Roba: 2 cartas"},
    {25, "Robo de Bolsillos", FX_DRAW, 0, 0, 0, 2,
     "Sus manos rapidas le quitan",
     "los recursos al enemigo.",
     "Roba: 2 cartas"},
    {25, "Robo de Bolsillos", FX_DRAW, 0, 0, 0, 2,
     "Sus manos rapidas le quitan",
     "los recursos al enemigo.",
     "Roba: 2 cartas"},
    {26, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1,
     "Tan rapido que puede actuar",
     "dos veces en un instante.",
     "Roba: 1 + Juega otra vez!"},
    {26, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1,
     "Tan rapido que puede actuar",
     "dos veces en un instante.",
     "Roba: 1 + Juega otra vez!"},
    {26, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1,
     "Tan rapido que puede actuar",
     "dos veces en un instante.",
     "Roba: 1 + Juega otra vez!"},
    {26, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1,
     "Tan rapido que puede actuar",
     "dos veces en un instante.",
     "Roba: 1 + Juega otra vez!"},

    // Combos (6 cartas)
    {27, "Golpe Fugaz", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0,
     "Golpea y desaparece antes",
     "de que lo veas. Imparable.",
     "Dano: 2 + Juega otra vez!"},
    {27, "Golpe Fugaz", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0,
     "Golpea y desaparece antes",
     "de que lo veas. Imparable.",
     "Dano: 2 + Juega otra vez!"},
    {27, "Golpe Fugaz", FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0,
     "Golpea y desaparece antes",
     "de que lo veas. Imparable.",
     "Dano: 2 + Juega otra vez!"},
    {28, "Ataque Sorpresa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1,
     "Ataca por la espalda y roba",
     "un secreto en el proceso.",
     "Dano: 3 + Roba: 1"},
    {28, "Ataque Sorpresa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1,
     "Ataca por la espalda y roba",
     "un secreto en el proceso.",
     "Dano: 3 + Roba: 1"},
    {28, "Ataque Sorpresa", FX_ATTACK | FX_DRAW, 3, 0, 0, 1,
     "Ataca por la espalda y roba",
     "un secreto en el proceso.",
     "Dano: 3 + Roba: 1"},
};
const int TINTIN_DECK_SIZE = 28;

// =====================================================
// MAZO DE LA TUNDA (28 cartas)
// Estilo: Control/Bruja - Curacion y drenaje
// =====================================================
const CardData CARTAS_TUNDA[] = {
    // Ataques (6 cartas)
    {40, "Zarpazo", FX_ATTACK, 3, 0, 0, 0,
     "La Tunda golpea con su mano",
     "transformada en garra.",
     "Dano: 3"},
    {40, "Zarpazo", FX_ATTACK, 3, 0, 0, 0,
     "La Tunda golpea con su mano",
     "transformada en garra.",
     "Dano: 3"},
    {40, "Zarpazo", FX_ATTACK, 3, 0, 0, 0,
     "La Tunda golpea con su mano",
     "transformada en garra.",
     "Dano: 3"},
    {41, "Molinillazo", FX_ATTACK, 4, 0, 0, 0,
     "Su pierna de molinillo gira",
     "como un trompo mortal.",
     "Dano: 4"},
    {41, "Molinillazo", FX_ATTACK, 4, 0, 0, 0,
     "Su pierna de molinillo gira",
     "como un trompo mortal.",
     "Dano: 4"},
    {41, "Molinillazo", FX_ATTACK, 4, 0, 0, 0,
     "Su pierna de molinillo gira",
     "como un trompo mortal.",
     "Dano: 4"},

    // Escudos (4 cartas)
    {42, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0,
     "Una niebla sobrenatural la",
     "protege de todo ataque.",
     "Escudo: 2"},
    {42, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0,
     "Una niebla sobrenatural la",
     "protege de todo ataque.",
     "Escudo: 2"},
    {42, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0,
     "Una niebla sobrenatural la",
     "protege de todo ataque.",
     "Escudo: 2"},
    {42, "Niebla Espesa", FX_SHIELD, 0, 2, 0, 0,
     "Una niebla sobrenatural la",
     "protege de todo ataque.",
     "Escudo: 2"},

    // Curacion (8 cartas)
    {43, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0,
     "Los camarones de La Tunda",
     "restauran la salud de quien",
     "los come. Cura: 2 HP"},
    {43, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0,
     "Los camarones de La Tunda",
     "restauran la salud de quien",
     "los come. Cura: 2 HP"},
    {43, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0,
     "Los camarones de La Tunda",
     "restauran la salud de quien",
     "los come. Cura: 2 HP"},
    {43, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0,
     "Los camarones de La Tunda",
     "restauran la salud de quien",
     "los come. Cura: 2 HP"},
    {44, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0,
     "Antiguos canticos esmeraldenos",
     "que sanan cualquier herida.",
     "Cura: 4 HP"},
    {44, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0,
     "Antiguos canticos esmeraldenos",
     "que sanan cualquier herida.",
     "Cura: 4 HP"},
    {44, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0,
     "Antiguos canticos esmeraldenos",
     "que sanan cualquier herida.",
     "Cura: 4 HP"},
    {44, "Ritual Sanacion", FX_HEAL, 0, 0, 4, 0,
     "Antiguos canticos esmeraldenos",
     "que sanan cualquier herida.",
     "Cura: 4 HP"},

    // Robo (4 cartas)
    {45, "Susurros", FX_DRAW, 0, 0, 0, 2,
     "Susurra secretos al viento",
     "que le revelan mas opciones.",
     "Roba: 2 cartas"},
    {45, "Susurros", FX_DRAW, 0, 0, 0, 2,
     "Susurra secretos al viento",
     "que le revelan mas opciones.",
     "Roba: 2 cartas"},
    {46, "Encantamiento", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1,
     "Hipnotiza a su victima con",
     "cantos ancestrales.",
     "Roba: 1 + Juega otra vez!"},
    {46, "Encantamiento", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1,
     "Hipnotiza a su victima con",
     "cantos ancestrales.",
     "Roba: 1 + Juega otra vez!"},

    // Combos (6 cartas)
    {47, "Drenar Vida", FX_ATTACK | FX_HEAL, 2, 0, 2, 0,
     "Absorbe la energia vital del",
     "enemigo para sanar sus",
     "heridas. Dano: 2 + Cura: 2"},
    {47, "Drenar Vida", FX_ATTACK | FX_HEAL, 2, 0, 2, 0,
     "Absorbe la energia vital del",
     "enemigo para sanar sus",
     "heridas. Dano: 2 + Cura: 2"},
    {47, "Drenar Vida", FX_ATTACK | FX_HEAL, 2, 0, 2, 0,
     "Absorbe la energia vital del",
     "enemigo para sanar sus",
     "heridas. Dano: 2 + Cura: 2"},
    {48, "Maldicion", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0,
     "Una maldicion ancestral que",
     "dana y protege al mismo",
     "tiempo. Dano: 3 + Escudo: 1"},
    {48, "Maldicion", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0,
     "Una maldicion ancestral que",
     "dana y protege al mismo",
     "tiempo. Dano: 3 + Escudo: 1"},
    {48, "Maldicion", FX_ATTACK | FX_SHIELD, 3, 1, 0, 0,
     "Una maldicion ancestral que",
     "dana y protege al mismo",
     "tiempo. Dano: 3 + Escudo: 1"},
};
const int TUNDA_DECK_SIZE = 28;
