#include "card.h"

// MAZO DE Cantuna
const CardData CARTAS_CANTUNA[] = {
    {0, "Ladrillo Rapido", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Arroja un", "ladrillo con gran", "velocidad. [D:1]", "[+Juega]", NULL, NULL, NULL},
    {1, "Golpe de Mazo", FX_ATTACK, 3, 0, 0, 0, "Un bloque tallado", "a mano, pesado", "como sus pecados.", "[D:3]", NULL, NULL, NULL},
    {2, "Golpe de Mazo", FX_ATTACK, 3, 0, 0, 0, "Un bloque tallado", "a mano, pesado", "como sus pecados.", "[D:3]", NULL, NULL, NULL},
    {3, "Golpe de Mazo", FX_ATTACK, 3, 0, 0, 0, "Un bloque tallado", "a mano, pesado", "como sus pecados.", "[D:3]", NULL, NULL, NULL},
    {4, "Muro Base", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Alza una pared", "mientras planea.", "[E:1] [R:1]", NULL, NULL, NULL, NULL},
    {5, "Muro Base", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Alza una pared", "mientras planea.", "[E:1] [R:1]", NULL, NULL, NULL, NULL},
    {6, "Muro Base", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Alza una pared", "mientras planea.", "[E:1] [R:1]", NULL, NULL, NULL, NULL},
    {7, "Muro Base", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Alza una pared", "mientras planea.", "[E:1] [R:1]", NULL, NULL, NULL, NULL},
    {8, "Muro Base", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Alza una pared", "mientras planea.", "[E:1] [R:1]", NULL, NULL, NULL, NULL},
    {9, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Un pilar", "indestructible;", "ni el diablo", "puede pasar.", "[E:3]", NULL, NULL},
    {10, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Un pilar", "indestructible;", "ni el diablo", "puede pasar.", "[E:3]", NULL, NULL},
    {11, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Un pilar", "indestructible;", "ni el diablo", "puede pasar.", "[E:3]", NULL, NULL},
    {12, "Fortaleza", FX_SHIELD, 0, 3, 0, 0, "Un pilar", "indestructible;", "ni el diablo", "puede pasar.", "[E:3]", NULL, NULL},
    {13, "Descanso", FX_HEAL, 0, 0, 2, 0, "Cierra los ojos", "un momento antes", "del amanecer.", "[C:2 HP]", NULL, NULL, NULL},
    {14, "Descanso", FX_HEAL, 0, 0, 2, 0, "Cierra los ojos", "un momento antes", "del amanecer.", "[C:2 HP]", NULL, NULL, NULL},
    {15, "Descanso", FX_HEAL, 0, 0, 2, 0, "Cierra los ojos", "un momento antes", "del amanecer.", "[C:2 HP]", NULL, NULL, NULL},
    {16, "Descanso", FX_HEAL, 0, 0, 2, 0, "Cierra los ojos", "un momento antes", "del amanecer.", "[C:2 HP]", NULL, NULL, NULL},
    {17, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Una chispa de", "ingenio le", "permite actuar", "rapido. [R:1]", "[+Juega]", NULL, NULL},
    {18, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Una chispa de", "ingenio le", "permite actuar", "rapido. [R:1]", "[+Juega]", NULL, NULL},
    {19, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Una chispa de", "ingenio le", "permite actuar", "rapido. [R:1]", "[+Juega]", NULL, NULL},
    {20, "Inspiracion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Una chispa de", "ingenio le", "permite actuar", "rapido. [R:1]", "[+Juega]", NULL, NULL},
    {21, "Iglesia Terminada", FX_SHIELD | FX_HEAL | FX_ATTACK, 2, 4, 2, 0, "Construye todo de", "golpe. Su obra", "maestra. [E:4]", "[C:2] [D:2]", NULL, NULL, NULL},
    {22, "Pacto Enganoso", FX_STEAL_HAND | FX_HEAL, 0, 0, 3, 0, "El diablo cobra", "su deuda en el", "rival. [C: 3]", "[Roba de mano]", NULL, NULL, NULL},
    {23, "Cimiento Solido", FX_STEAL_DISCARD | FX_SHIELD, 0, 4, 0, 0, "Usa los restos", "para blindarse", "por completo. [E:", "4] [Roba", "descarte]", NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int CANTUNA_DECK_SIZE = 28;

// MAZO DE El Tin Tin
const CardData CARTAS_TINTIN[] = {
    {0, "Travesura", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Tira de tu", "cabello y sigue", "molestando. [D:1]", "[+Juega]", NULL, NULL, NULL},
    {1, "Emboscada", FX_ATTACK, 3, 0, 0, 0, "Cae desde las", "ramas directo", "sobre su presa.", "[D:3]", NULL, NULL, NULL},
    {2, "Emboscada", FX_ATTACK, 3, 0, 0, 0, "Cae desde las", "ramas directo", "sobre su presa.", "[D:3]", NULL, NULL, NULL},
    {3, "Emboscada", FX_ATTACK, 3, 0, 0, 0, "Cae desde las", "ramas directo", "sobre su presa.", "[D:3]", NULL, NULL, NULL},
    {4, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se oculta", "rapidamente en la", "maleza. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {5, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se oculta", "rapidamente en la", "maleza. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {6, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se oculta", "rapidamente en la", "maleza. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {7, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se oculta", "rapidamente en la", "maleza. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {8, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se oculta", "rapidamente en la", "maleza. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {9, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los", "aires burlando", "toda defensa.", "[R:1] [+Juega]", NULL, NULL, NULL},
    {10, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los", "aires burlando", "toda defensa.", "[R:1] [+Juega]", NULL, NULL, NULL},
    {11, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los", "aires burlando", "toda defensa.", "[R:1] [+Juega]", NULL, NULL, NULL},
    {12, "Agilidad", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Salta por los", "aires burlando", "toda defensa.", "[R:1] [+Juega]", NULL, NULL, NULL},
    {13, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Descansa un rato", "para planear otra", "diablura. [C:2]", NULL, NULL, NULL, NULL},
    {14, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Descansa un rato", "para planear otra", "diablura. [C:2]", NULL, NULL, NULL, NULL},
    {15, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Descansa un rato", "para planear otra", "diablura. [C:2]", NULL, NULL, NULL, NULL},
    {16, "Siesta Maliciosa", FX_HEAL, 0, 0, 2, 0, "Descansa un rato", "para planear otra", "diablura. [C:2]", NULL, NULL, NULL, NULL},
    {17, "Robo de Bolsillos", FX_STEAL_DECK | FX_ATTACK, 1, 0, 0, 2, "Manos tan rapidas", "que ni sientes", "que te roba. [D:", "1] [Roba mazo", "rival]", NULL, NULL},
    {18, "Robo de Bolsillos", FX_STEAL_DECK | FX_ATTACK, 1, 0, 0, 2, "Manos tan rapidas", "que ni sientes", "que te roba. [D:", "1] [Roba mazo", "rival]", NULL, NULL},
    {19, "Robo de Bolsillos", FX_STEAL_DECK | FX_ATTACK, 1, 0, 0, 2, "Manos tan rapidas", "que ni sientes", "que te roba. [D:", "1] [Roba mazo", "rival]", NULL, NULL},
    {20, "Robo de Bolsillos", FX_STEAL_DECK | FX_ATTACK, 1, 0, 0, 2, "Manos tan rapidas", "que ni sientes", "que te roba. [D:", "1] [Roba mazo", "rival]", NULL, NULL},
    {21, "Seductor Mitico", FX_ATTACK | FX_DRAW | FX_PLAY_AGAIN, 4, 0, 0, 1, "Te engana y te", "roba el alma.", "[D:4] [R:1]", "[+Juega]", NULL, NULL, NULL},
    {22, "Sombrero Magico", FX_STEAL_DECK | FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 2, "Saca sorpresas", "interminables.", "[R: 2] [Roba", "mazo] [+Juega]", NULL, NULL, NULL},
    {23, "Asalto Fugaz", FX_STEAL_HAND | FX_ATTACK, 3, 0, 0, 0, "Te golpea y te", "deja sin", "opciones. [D: 3]", "[Roba de mano]", NULL, NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int TINTIN_DECK_SIZE = 28;

// MAZO DE La Tunda
const CardData CARTAS_TUNDA[] = {
    {0, "Zarpazo", FX_ATTACK | FX_HEAL, 1, 0, 1, 0, "Su mano retorcida", "desgarra y", "absorbe. [D:1]", "[C:1]", NULL, NULL, NULL},
    {1, "Molinillazo", FX_ATTACK, 3, 0, 0, 0, "Patea con su", "pesada pierna de", "madera. [D:3]", NULL, NULL, NULL, NULL},
    {2, "Molinillazo", FX_ATTACK, 3, 0, 0, 0, "Patea con su", "pesada pierna de", "madera. [D:3]", NULL, NULL, NULL, NULL},
    {3, "Molinillazo", FX_ATTACK, 3, 0, 0, 0, "Patea con su", "pesada pierna de", "madera. [D:3]", NULL, NULL, NULL, NULL},
    {4, "Niebla Espesa", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "El manglar se", "cierra,", "ocultandola por", "completo. [E:1]", "[+Juega]", NULL, NULL},
    {5, "Niebla Espesa", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "El manglar se", "cierra,", "ocultandola por", "completo. [E:1]", "[+Juega]", NULL, NULL},
    {6, "Niebla Espesa", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "El manglar se", "cierra,", "ocultandola por", "completo. [E:1]", "[+Juega]", NULL, NULL},
    {7, "Niebla Espesa", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "El manglar se", "cierra,", "ocultandola por", "completo. [E:1]", "[+Juega]", NULL, NULL},
    {8, "Niebla Espesa", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "El manglar se", "cierra,", "ocultandola por", "completo. [E:1]", "[+Juega]", NULL, NULL},
    {9, "Proteccion Lodo", FX_SHIELD, 0, 3, 0, 0, "Barro del pantano", "amortigua los", "golpes. [E:3]", NULL, NULL, NULL, NULL},
    {10, "Proteccion Lodo", FX_SHIELD, 0, 3, 0, 0, "Barro del pantano", "amortigua los", "golpes. [E:3]", NULL, NULL, NULL, NULL},
    {11, "Proteccion Lodo", FX_SHIELD, 0, 3, 0, 0, "Barro del pantano", "amortigua los", "golpes. [E:3]", NULL, NULL, NULL, NULL},
    {12, "Proteccion Lodo", FX_SHIELD, 0, 3, 0, 0, "Barro del pantano", "amortigua los", "golpes. [E:3]", NULL, NULL, NULL, NULL},
    {13, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado", "embrujado que", "restaura su", "vigor. [C:2 HP]", NULL, NULL, NULL},
    {14, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado", "embrujado que", "restaura su", "vigor. [C:2 HP]", NULL, NULL, NULL},
    {15, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado", "embrujado que", "restaura su", "vigor. [C:2 HP]", NULL, NULL, NULL},
    {16, "Camarones Magicos", FX_HEAL, 0, 0, 2, 0, "Un bocado", "embrujado que", "restaura su", "vigor. [C:2 HP]", NULL, NULL, NULL},
    {17, "Susurros", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Voces en la", "niebla que", "revelan secretos", "oscuros. [R:1]", "[+Juega]", NULL, NULL},
    {18, "Susurros", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Voces en la", "niebla que", "revelan secretos", "oscuros. [R:1]", "[+Juega]", NULL, NULL},
    {19, "Susurros", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Voces en la", "niebla que", "revelan secretos", "oscuros. [R:1]", "[+Juega]", NULL, NULL},
    {20, "Susurros", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Voces en la", "niebla que", "revelan secretos", "oscuros. [R:1]", "[+Juega]", NULL, NULL},
    {21, "Entundamiento", FX_HEAL | FX_ATTACK | FX_DRAW, 2, 0, 4, 1, "Hipnotiza a su", "presa en el fondo", "del bosque. [C:4]", "[D:2] [R:1]", NULL, NULL, NULL},
    {22, "Maldicion del Manglar", FX_STEAL_HAND | FX_STEAL_DISCARD, 0, 0, 0, 0, "Pierdes todo lo", "que tenias. [Roba", "mano y descarte]", NULL, NULL, NULL, NULL},
    {23, "Ilusion Maternal", FX_STEAL_DECK | FX_HEAL, 0, 0, 3, 0, "Finge ser tu", "madre para robar", "tu futuro. [C: 3]", "[Roba mazo rival]", NULL, NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int TUNDA_DECK_SIZE = 28;

// MAZO DE Padre Almeida
const CardData CARTAS_ALMEIDA[] = {
    {0, "Guitarrazo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Un golpe rapido", "con su vieja", "guitarra. [D:1]", "[+Juega]", NULL, NULL, NULL},
    {1, "Botellazo", FX_ATTACK, 3, 0, 0, 0, "Vuela una botella", "vacia directo a", "la cabeza. [D:3]", NULL, NULL, NULL, NULL},
    {2, "Botellazo", FX_ATTACK, 3, 0, 0, 0, "Vuela una botella", "vacia directo a", "la cabeza. [D:3]", NULL, NULL, NULL, NULL},
    {3, "Botellazo", FX_ATTACK, 3, 0, 0, 0, "Vuela una botella", "vacia directo a", "la cabeza. [D:3]", NULL, NULL, NULL, NULL},
    {4, "Sotana", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "La tela sagrada", "lo cubre mientras", "huye. [E:1] [R:1]", NULL, NULL, NULL, NULL},
    {5, "Sotana", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "La tela sagrada", "lo cubre mientras", "huye. [E:1] [R:1]", NULL, NULL, NULL, NULL},
    {6, "Sotana", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "La tela sagrada", "lo cubre mientras", "huye. [E:1] [R:1]", NULL, NULL, NULL, NULL},
    {7, "Sotana", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "La tela sagrada", "lo cubre mientras", "huye. [E:1] [R:1]", NULL, NULL, NULL, NULL},
    {8, "Sotana", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "La tela sagrada", "lo cubre mientras", "huye. [E:1] [R:1]", NULL, NULL, NULL, NULL},
    {9, "Trago Bendito", FX_HEAL | FX_PLAY_AGAIN, 0, 0, 1, 0, "Un pequeno sorbo", "para seguir la", "fiesta. [C:1]", "[+Juega]", NULL, NULL, NULL},
    {10, "Trago Bendito", FX_HEAL | FX_PLAY_AGAIN, 0, 0, 1, 0, "Un pequeno sorbo", "para seguir la", "fiesta. [C:1]", "[+Juega]", NULL, NULL, NULL},
    {11, "Trago Bendito", FX_HEAL | FX_PLAY_AGAIN, 0, 0, 1, 0, "Un pequeno sorbo", "para seguir la", "fiesta. [C:1]", "[+Juega]", NULL, NULL, NULL},
    {12, "Trago Bendito", FX_HEAL | FX_PLAY_AGAIN, 0, 0, 1, 0, "Un pequeno sorbo", "para seguir la", "fiesta. [C:1]", "[+Juega]", NULL, NULL, NULL},
    {13, "Salida Secreta", FX_STEAL_DECK | FX_DRAW, 0, 0, 0, 2, "Conoce todos los", "atajos y descubre", "sus planes.", "[Roba: 1] [Roba", "mazo rival]", NULL, NULL},
    {14, "Salida Secreta", FX_STEAL_DECK | FX_DRAW, 0, 0, 0, 2, "Conoce todos los", "atajos y descubre", "sus planes.", "[Roba: 1] [Roba", "mazo rival]", NULL, NULL},
    {15, "Salida Secreta", FX_STEAL_DECK | FX_DRAW, 0, 0, 0, 2, "Conoce todos los", "atajos y descubre", "sus planes.", "[Roba: 1] [Roba", "mazo rival]", NULL, NULL},
    {16, "Salida Secreta", FX_STEAL_DECK | FX_DRAW, 0, 0, 0, 2, "Conoce todos los", "atajos y descubre", "sus planes.", "[Roba: 1] [Roba", "mazo rival]", NULL, NULL},
    {17, "Farra", FX_ATTACK | FX_DRAW, 2, 0, 0, 1, "Sigue la fiesta", "con golpes", "impredecibles.", "[D:2] [R:1]", NULL, NULL, NULL},
    {18, "Farra", FX_ATTACK | FX_DRAW, 2, 0, 0, 1, "Sigue la fiesta", "con golpes", "impredecibles.", "[D:2] [R:1]", NULL, NULL, NULL},
    {19, "Farra", FX_ATTACK | FX_DRAW, 2, 0, 0, 1, "Sigue la fiesta", "con golpes", "impredecibles.", "[D:2] [R:1]", NULL, NULL, NULL},
    {20, "Farra", FX_ATTACK | FX_DRAW, 2, 0, 0, 1, "Sigue la fiesta", "con golpes", "impredecibles.", "[D:2] [R:1]", NULL, NULL, NULL},
    {21, "Hasta la Vuelta!", FX_DRAW | FX_PLAY_AGAIN | FX_HEAL, 0, 0, 2, 2, "Pisa al Cristo y", "sale corriendo", "invencible. [R:2]", "[C:2] [+Juega]", NULL, NULL, NULL},
    {22, "Escape Milagroso", FX_STEAL_HAND | FX_DRAW, 0, 0, 0, 2, "Esquiva tu ataque", "y huye con", "ventaja. [R: 2]", "[Roba de mano]", NULL, NULL, NULL},
    {23, "Trago Robado", FX_STEAL_DISCARD | FX_HEAL | FX_PLAY_AGAIN, 0, 0, 2, 0, "Bebe de la", "botella que", "creias vacia. [C:", "2] [Roba", "descarte] [+J]", NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int ALMEIDA_DECK_SIZE = 28;

// MAZO DE Dama Tapada
const CardData CARTAS_DAMATAPADA[] = {
    {0, "Perfume Barato", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Aroma embriagador", "que desorienta al", "instante. [D:1]", "[+Juega]", NULL, NULL, NULL},
    {1, "Grito Aterrador", FX_ATTACK, 3, 0, 0, 0, "Un chillido agudo", "que hiela la", "sangre. [D:3]", NULL, NULL, NULL, NULL},
    {2, "Grito Aterrador", FX_ATTACK, 3, 0, 0, 0, "Un chillido agudo", "que hiela la", "sangre. [D:3]", NULL, NULL, NULL, NULL},
    {3, "Grito Aterrador", FX_ATTACK, 3, 0, 0, 0, "Un chillido agudo", "que hiela la", "sangre. [D:3]", NULL, NULL, NULL, NULL},
    {4, "Bruma Fria", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Una niebla oscura", "amortigua los", "golpes. [E:1]", "[R:1]", NULL, NULL, NULL},
    {5, "Bruma Fria", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Una niebla oscura", "amortigua los", "golpes. [E:1]", "[R:1]", NULL, NULL, NULL},
    {6, "Bruma Fria", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Una niebla oscura", "amortigua los", "golpes. [E:1]", "[R:1]", NULL, NULL, NULL},
    {7, "Bruma Fria", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Una niebla oscura", "amortigua los", "golpes. [E:1]", "[R:1]", NULL, NULL, NULL},
    {8, "Bruma Fria", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Una niebla oscura", "amortigua los", "golpes. [E:1]", "[R:1]", NULL, NULL, NULL},
    {9, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil", "golpearla. [E:3]", NULL, NULL, NULL, NULL},
    {10, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil", "golpearla. [E:3]", NULL, NULL, NULL, NULL},
    {11, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil", "golpearla. [E:3]", NULL, NULL, NULL, NULL},
    {12, "Paseo Nocturno", FX_SHIELD, 0, 3, 0, 0, "Camina flotando;", "es dificil", "golpearla. [E:3]", NULL, NULL, NULL, NULL},
    {13, "Beso Frio", FX_HEAL, 0, 0, 2, 0, "Restaura su", "energia con magia", "negra. [C:2]", NULL, NULL, NULL, NULL},
    {14, "Beso Frio", FX_HEAL, 0, 0, 2, 0, "Restaura su", "energia con magia", "negra. [C:2]", NULL, NULL, NULL, NULL},
    {15, "Beso Frio", FX_HEAL, 0, 0, 2, 0, "Restaura su", "energia con magia", "negra. [C:2]", NULL, NULL, NULL, NULL},
    {16, "Beso Frio", FX_HEAL, 0, 0, 2, 0, "Restaura su", "energia con magia", "negra. [C:2]", NULL, NULL, NULL, NULL},
    {17, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae a incautos", "hacia su", "perdicion. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {18, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae a incautos", "hacia su", "perdicion. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {19, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae a incautos", "hacia su", "perdicion. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {20, "Seduccion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Atrae a incautos", "hacia su", "perdicion. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {21, "Rostro Esqueletico", FX_ATTACK | FX_SHIELD, 4, 3, 0, 0, "Se quita el velo;", "el horror", "absoluto. [D:4]", "[E:3]", NULL, NULL, NULL},
    {22, "Perfume Letal", FX_STEAL_DECK | FX_ATTACK, 4, 0, 0, 0, "El olor a muerte", "arruina tu", "destino. [D: 4]", "[Roba mazo rival]", NULL, NULL, NULL},
    {23, "Mirada al Abismo", FX_STEAL_HAND | FX_STEAL_DECK, 0, 0, 0, 0, "El panico te hace", "perder la cabeza.", "[Roba mano y", "mazo]", NULL, NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int DAMATAPADA_DECK_SIZE = 28;

// MAZO DE Maria Angula
const CardData CARTAS_MARIANGULA[] = {
    {0, "Tijeras", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Corta sin pensar", "en las", "consecuencias.", "[D:1] [+Juega]", NULL, NULL, NULL},
    {1, "Olla Caliente", FX_ATTACK, 3, 0, 0, 0, "Lanza caldo", "hirviendo sin", "pensarlo dos", "veces. [D:3]", NULL, NULL, NULL},
    {2, "Olla Caliente", FX_ATTACK, 3, 0, 0, 0, "Lanza caldo", "hirviendo sin", "pensarlo dos", "veces. [D:3]", NULL, NULL, NULL},
    {3, "Olla Caliente", FX_ATTACK, 3, 0, 0, 0, "Lanza caldo", "hirviendo sin", "pensarlo dos", "veces. [D:3]", NULL, NULL, NULL},
    {4, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se esconde", "temblando bajo", "las mantas. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {5, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se esconde", "temblando bajo", "las mantas. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {6, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se esconde", "temblando bajo", "las mantas. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {7, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se esconde", "temblando bajo", "las mantas. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {8, "Escondite", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Se esconde", "temblando bajo", "las mantas. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {9, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 1, "El terror la", "obliga a", "protegerse y", "pensar. [E:2]", "[R:1]", NULL, NULL},
    {10, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 1, "El terror la", "obliga a", "protegerse y", "pensar. [E:2]", "[R:1]", NULL, NULL},
    {11, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 1, "El terror la", "obliga a", "protegerse y", "pensar. [E:2]", "[R:1]", NULL, NULL},
    {12, "Miedo a la Noche", FX_SHIELD, 0, 2, 0, 1, "El terror la", "obliga a", "protegerse y", "pensar. [E:2]", "[R:1]", NULL, NULL},
    {13, "Robo de Tripas", FX_STEAL_DISCARD | FX_HEAL, 0, 0, 2, 0, "Saca algo util de", "la tumba del", "oponente. [C: 2]", "[Roba descarte]", NULL, NULL, NULL},
    {14, "Robo de Tripas", FX_STEAL_DISCARD | FX_HEAL, 0, 0, 2, 0, "Saca algo util de", "la tumba del", "oponente. [C: 2]", "[Roba descarte]", NULL, NULL, NULL},
    {15, "Robo de Tripas", FX_STEAL_DISCARD | FX_HEAL, 0, 0, 2, 0, "Saca algo util de", "la tumba del", "oponente. [C: 2]", "[Roba descarte]", NULL, NULL, NULL},
    {16, "Robo de Tripas", FX_STEAL_DISCARD | FX_HEAL, 0, 0, 2, 0, "Saca algo util de", "la tumba del", "oponente. [C: 2]", "[Roba descarte]", NULL, NULL, NULL},
    {17, "Grito de Culpa", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Su llanto aterra", "y le da nuevas", "ideas. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {18, "Grito de Culpa", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Su llanto aterra", "y le da nuevas", "ideas. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {19, "Grito de Culpa", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Su llanto aterra", "y le da nuevas", "ideas. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {20, "Grito de Culpa", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Su llanto aterra", "y le da nuevas", "ideas. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {21, "Sopa Macabra", FX_ATTACK | FX_HEAL | FX_PLAY_AGAIN, 4, 0, 2, 0, "Cocina el mal y", "se fortalece.", "[D:4] [C:2]", "[+Juega]", NULL, NULL, NULL},
    {22, "Sopa de Robos", FX_STEAL_DISCARD | FX_STEAL_HAND, 0, 0, 0, 0, "Saca ingredientes", "de donde sea.", "[Roba mano y", "descarte]", NULL, NULL, NULL},
    {23, "Berrinche Mortal", FX_STEAL_DECK | FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Destruye todo a", "su paso. [D: 2]", "[Roba mazo] [+J]", NULL, NULL, NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int MARIANGULA_DECK_SIZE = 28;

// MAZO DE Gallo Catedral
const CardData CARTAS_GALLO[] = {
    {0, "Picotazo Rapido", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Un golpe veloz", "con su pico de", "oro. [D:1]", "[+Juega]", NULL, NULL, NULL},
    {1, "Espolon", FX_ATTACK, 3, 0, 0, 0, "Un corte profundo", "con sus garras", "afiladas. [D:3]", NULL, NULL, NULL, NULL},
    {2, "Espolon", FX_ATTACK, 3, 0, 0, 0, "Un corte profundo", "con sus garras", "afiladas. [D:3]", NULL, NULL, NULL, NULL},
    {3, "Espolon", FX_ATTACK, 3, 0, 0, 0, "Un corte profundo", "con sus garras", "afiladas. [D:3]", NULL, NULL, NULL, NULL},
    {4, "Vuelo Corto", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aletea", "rapidamente para", "tomar ventaja.", "[E:1] [+Juega]", NULL, NULL, NULL},
    {5, "Vuelo Corto", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aletea", "rapidamente para", "tomar ventaja.", "[E:1] [+Juega]", NULL, NULL, NULL},
    {6, "Vuelo Corto", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aletea", "rapidamente para", "tomar ventaja.", "[E:1] [+Juega]", NULL, NULL, NULL},
    {7, "Vuelo Corto", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aletea", "rapidamente para", "tomar ventaja.", "[E:1] [+Juega]", NULL, NULL, NULL},
    {8, "Vuelo Corto", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Aletea", "rapidamente para", "tomar ventaja.", "[E:1] [+Juega]", NULL, NULL, NULL},
    {9, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de", "metal rechaza los", "impactos. [E:3]", NULL, NULL, NULL, NULL},
    {10, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de", "metal rechaza los", "impactos. [E:3]", NULL, NULL, NULL, NULL},
    {11, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de", "metal rechaza los", "impactos. [E:3]", NULL, NULL, NULL, NULL},
    {12, "Alas de Bronce", FX_SHIELD, 0, 3, 0, 0, "Su cuerpo de", "metal rechaza los", "impactos. [E:3]", NULL, NULL, NULL, NULL},
    {13, "Pluma Dorada", FX_HEAL, 0, 0, 2, 0, "Brillo sanador", "que restaura su", "bronce. [C:2 HP]", NULL, NULL, NULL, NULL},
    {14, "Pluma Dorada", FX_HEAL, 0, 0, 2, 0, "Brillo sanador", "que restaura su", "bronce. [C:2 HP]", NULL, NULL, NULL, NULL},
    {15, "Pluma Dorada", FX_HEAL, 0, 0, 2, 0, "Brillo sanador", "que restaura su", "bronce. [C:2 HP]", NULL, NULL, NULL, NULL},
    {16, "Pluma Dorada", FX_HEAL, 0, 0, 2, 0, "Brillo sanador", "que restaura su", "bronce. [C:2 HP]", NULL, NULL, NULL, NULL},
    {17, "Canto Matutino", FX_DRAW | FX_HEAL, 0, 0, 1, 2, "Anuncia el", "amanecer,", "renovando su", "fuerza. [C:1]", "[R:2]", NULL, NULL},
    {18, "Canto Matutino", FX_DRAW | FX_HEAL, 0, 0, 1, 2, "Anuncia el", "amanecer,", "renovando su", "fuerza. [C:1]", "[R:2]", NULL, NULL},
    {19, "Canto Matutino", FX_DRAW | FX_HEAL, 0, 0, 1, 2, "Anuncia el", "amanecer,", "renovando su", "fuerza. [C:1]", "[R:2]", NULL, NULL},
    {20, "Canto Matutino", FX_DRAW | FX_HEAL, 0, 0, 1, 2, "Anuncia el", "amanecer,", "renovando su", "fuerza. [C:1]", "[R:2]", NULL, NULL},
    {21, "Ira de la Catedral", FX_ATTACK | FX_SHIELD | FX_HEAL, 3, 3, 3, 0, "El monumento", "despierta", "castigando al", "blasfemo. [D:3]", "[E:3] [C:3]", NULL, NULL},
    {22, "Canto Hipnotico", FX_STEAL_HAND | FX_SHIELD, 0, 3, 0, 0, "Te aturde", "mientras se", "protege. [E: 3]", "[Roba de mano]", NULL, NULL, NULL},
    {23, "Brillo Cegador", FX_STEAL_DISCARD | FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Resplandece y", "toma la", "iniciativa. [R:", "1] [Roba", "descarte] [+J]", NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int GALLO_DECK_SIZE = 28;

// MAZO DE Cura sin Cabeza
const CardData CARTAS_CURA[] = {
    {0, "Sermon Mudo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Palabras sin voz", "que destruyen la", "mente. [D:1]", "[+Juega]", NULL, NULL, NULL},
    {1, "Llama Negra", FX_ATTACK, 3, 0, 0, 0, "Fuego del", "purgatorio que", "quema el alma.", "[D:3]", NULL, NULL, NULL},
    {2, "Llama Negra", FX_ATTACK, 3, 0, 0, 0, "Fuego del", "purgatorio que", "quema el alma.", "[D:3]", NULL, NULL, NULL},
    {3, "Llama Negra", FX_ATTACK, 3, 0, 0, 0, "Fuego del", "purgatorio que", "quema el alma.", "[D:3]", NULL, NULL, NULL},
    {4, "Levitacion", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Flota amenazante", "sobre el", "empedrado. [E:1]", "[R:1]", NULL, NULL, NULL},
    {5, "Levitacion", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Flota amenazante", "sobre el", "empedrado. [E:1]", "[R:1]", NULL, NULL, NULL},
    {6, "Levitacion", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Flota amenazante", "sobre el", "empedrado. [E:1]", "[R:1]", NULL, NULL, NULL},
    {7, "Levitacion", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Flota amenazante", "sobre el", "empedrado. [E:1]", "[R:1]", NULL, NULL, NULL},
    {8, "Levitacion", FX_SHIELD | FX_DRAW, 0, 1, 0, 1, "Flota amenazante", "sobre el", "empedrado. [E:1]", "[R:1]", NULL, NULL, NULL},
    {9, "Aparicion", FX_SHIELD, 0, 3, 0, 0, "Se vuelve", "incorporeo,", "imposible de", "tocar. [E:3]", NULL, NULL, NULL},
    {10, "Aparicion", FX_SHIELD, 0, 3, 0, 0, "Se vuelve", "incorporeo,", "imposible de", "tocar. [E:3]", NULL, NULL, NULL},
    {11, "Aparicion", FX_SHIELD, 0, 3, 0, 0, "Se vuelve", "incorporeo,", "imposible de", "tocar. [E:3]", NULL, NULL, NULL},
    {12, "Aparicion", FX_SHIELD, 0, 3, 0, 0, "Se vuelve", "incorporeo,", "imposible de", "tocar. [E:3]", NULL, NULL, NULL},
    {13, "Aura Espectral", FX_HEAL, 0, 0, 2, 0, "Un frio de", "ultratumba lo", "rodea por", "completo. [C:2]", NULL, NULL, NULL},
    {14, "Aura Espectral", FX_HEAL, 0, 0, 2, 0, "Un frio de", "ultratumba lo", "rodea por", "completo. [C:2]", NULL, NULL, NULL},
    {15, "Aura Espectral", FX_HEAL, 0, 0, 2, 0, "Un frio de", "ultratumba lo", "rodea por", "completo. [C:2]", NULL, NULL, NULL},
    {16, "Aura Espectral", FX_HEAL, 0, 0, 2, 0, "Un frio de", "ultratumba lo", "rodea por", "completo. [C:2]", NULL, NULL, NULL},
    {17, "Busqueda de Cabeza", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Vaga buscando", "partes de su", "cuerpo perdido.", "[R:1] [+Juega]", NULL, NULL, NULL},
    {18, "Busqueda de Cabeza", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Vaga buscando", "partes de su", "cuerpo perdido.", "[R:1] [+Juega]", NULL, NULL, NULL},
    {19, "Busqueda de Cabeza", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Vaga buscando", "partes de su", "cuerpo perdido.", "[R:1] [+Juega]", NULL, NULL, NULL},
    {20, "Busqueda de Cabeza", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Vaga buscando", "partes de su", "cuerpo perdido.", "[R:1] [+Juega]", NULL, NULL, NULL},
    {21, "Misa de Medianoche", FX_ATTACK | FX_DRAW | FX_PLAY_AGAIN, 4, 0, 0, 2, "Un ritual profano", "que condena al", "enemigo. [D:4]", "[R:2] [+Juega]", NULL, NULL, NULL},
    {22, "Fuego del Purgatorio", FX_STEAL_DECK | FX_ATTACK, 5, 0, 0, 0, "Quema tu", "esperanza.  [D:", "5] [Roba mazo", "rival]", NULL, NULL, NULL},
    {23, "Exorcismo Inverso", FX_STEAL_HAND | FX_HEAL, 0, 0, 4, 0, "Te drena el alma.", "[C: 4] [Roba de", "mano]", NULL, NULL, NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int CURA_DECK_SIZE = 28;

// MAZO DE El Chuzalongo
const CardData CARTAS_CHUZALONGO[] = {
    {0, "Furia Ciega", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Ataca a todos", "lados sin mirar a", "quien. [D:1]", "[+Juega]", NULL, NULL, NULL},
    {1, "Garras Paramo", FX_ATTACK, 3, 0, 0, 0, "Zarpazos", "sangrientos", "tejidos de", "rencor. [D:3]", NULL, NULL, NULL},
    {2, "Garras Paramo", FX_ATTACK, 3, 0, 0, 0, "Zarpazos", "sangrientos", "tejidos de", "rencor. [D:3]", NULL, NULL, NULL},
    {3, "Garras Paramo", FX_ATTACK, 3, 0, 0, 0, "Zarpazos", "sangrientos", "tejidos de", "rencor. [D:3]", NULL, NULL, NULL},
    {4, "Instinto Animal", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Olfatea la sangre", "y actua sin", "dudar. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {5, "Instinto Animal", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Olfatea la sangre", "y actua sin", "dudar. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {6, "Instinto Animal", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Olfatea la sangre", "y actua sin", "dudar. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {7, "Instinto Animal", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Olfatea la sangre", "y actua sin", "dudar. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {8, "Instinto Animal", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Olfatea la sangre", "y actua sin", "dudar. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {9, "Piel Gruesa", FX_SHIELD, 0, 2, 0, 1, "El lodo y musgo", "amortiguan un", "poco. [E:2] [R:1]", NULL, NULL, NULL, NULL},
    {10, "Piel Gruesa", FX_SHIELD, 0, 2, 0, 1, "El lodo y musgo", "amortiguan un", "poco. [E:2] [R:1]", NULL, NULL, NULL, NULL},
    {11, "Piel Gruesa", FX_SHIELD, 0, 2, 0, 1, "El lodo y musgo", "amortiguan un", "poco. [E:2] [R:1]", NULL, NULL, NULL, NULL},
    {12, "Piel Gruesa", FX_SHIELD, 0, 2, 0, 1, "El lodo y musgo", "amortiguan un", "poco. [E:2] [R:1]", NULL, NULL, NULL, NULL},
    {13, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta de lo", "que encuentra en", "la montana. [C:2", "HP]", NULL, NULL, NULL},
    {14, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta de lo", "que encuentra en", "la montana. [C:2", "HP]", NULL, NULL, NULL},
    {15, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta de lo", "que encuentra en", "la montana. [C:2", "HP]", NULL, NULL, NULL},
    {16, "Carne Cruda", FX_HEAL, 0, 0, 2, 0, "Se alimenta de lo", "que encuentra en", "la montana. [C:2", "HP]", NULL, NULL, NULL},
    {17, "Aullido", FX_DRAW | FX_ATTACK, 2, 0, 0, 1, "Un grito", "desgarrador que", "paraliza al", "enemigo. [D:2]", "[R:1]", NULL, NULL},
    {18, "Aullido", FX_DRAW | FX_ATTACK, 2, 0, 0, 1, "Un grito", "desgarrador que", "paraliza al", "enemigo. [D:2]", "[R:1]", NULL, NULL},
    {19, "Aullido", FX_DRAW | FX_ATTACK, 2, 0, 0, 1, "Un grito", "desgarrador que", "paraliza al", "enemigo. [D:2]", "[R:1]", NULL, NULL},
    {20, "Aullido", FX_DRAW | FX_ATTACK, 2, 0, 0, 1, "Un grito", "desgarrador que", "paraliza al", "enemigo. [D:2]", "[R:1]", NULL, NULL},
    {21, "Mordida Salvaje", FX_ATTACK | FX_HEAL | FX_PLAY_AGAIN, 4, 0, 2, 0, "Muerde la yugular", "con furia animal.", "[D:4] [C:2]", "[+Juega]", NULL, NULL, NULL},
    {22, "Ataque Furtivo", FX_STEAL_HAND | FX_ATTACK, 4, 0, 0, 0, "Muerde y se roba", "lo que caiga. [D:", "4] [Roba de mano]", NULL, NULL, NULL, NULL},
    {23, "Carrona", FX_STEAL_DISCARD | FX_HEAL | FX_DRAW, 0, 0, 2, 1, "Se alimenta de", "tus restos. [C:", "2] [R: 1] [Roba", "desc]", NULL, NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int CHUZALONGO_DECK_SIZE = 28;

// MAZO DE La Llorona
const CardData CARTAS_LLORONA[] = {
    {0, "Lagrimas", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "El dolor le", "ensena nuevas", "formas de sufrir.", "[D:1] [+Juega]", NULL, NULL, NULL},
    {1, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Un grito de", "lamento que te", "rompe los", "timpanos. [D:3]", NULL, NULL, NULL},
    {2, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Un grito de", "lamento que te", "rompe los", "timpanos. [D:3]", NULL, NULL, NULL},
    {3, "Mis Hijos!", FX_ATTACK, 3, 0, 0, 0, "Un grito de", "lamento que te", "rompe los", "timpanos. [D:3]", NULL, NULL, NULL},
    {4, "Manto Blanco", FX_SHIELD | FX_HEAL, 0, 1, 1, 0, "Su tunica", "espectral rechaza", "los ataques.", "[E:1] [C:1]", NULL, NULL, NULL},
    {5, "Manto Blanco", FX_SHIELD | FX_HEAL, 0, 1, 1, 0, "Su tunica", "espectral rechaza", "los ataques.", "[E:1] [C:1]", NULL, NULL, NULL},
    {6, "Manto Blanco", FX_SHIELD | FX_HEAL, 0, 1, 1, 0, "Su tunica", "espectral rechaza", "los ataques.", "[E:1] [C:1]", NULL, NULL, NULL},
    {7, "Manto Blanco", FX_SHIELD | FX_HEAL, 0, 1, 1, 0, "Su tunica", "espectral rechaza", "los ataques.", "[E:1] [C:1]", NULL, NULL, NULL},
    {8, "Manto Blanco", FX_SHIELD | FX_HEAL, 0, 1, 1, 0, "Su tunica", "espectral rechaza", "los ataques.", "[E:1] [C:1]", NULL, NULL, NULL},
    {9, "Rio Desbordado", FX_SHIELD, 0, 3, 0, 0, "Aguas violentas", "te arrastran", "lejos de ella.", "[E:3]", NULL, NULL, NULL},
    {10, "Rio Desbordado", FX_SHIELD, 0, 3, 0, 0, "Aguas violentas", "te arrastran", "lejos de ella.", "[E:3]", NULL, NULL, NULL},
    {11, "Rio Desbordado", FX_SHIELD, 0, 3, 0, 0, "Aguas violentas", "te arrastran", "lejos de ella.", "[E:3]", NULL, NULL, NULL},
    {12, "Rio Desbordado", FX_SHIELD, 0, 3, 0, 0, "Aguas violentas", "te arrastran", "lejos de ella.", "[E:3]", NULL, NULL, NULL},
    {13, "Consuelo Vano", FX_HEAL, 0, 0, 2, 0, "Se engana", "pensando que aun", "estan vivos.", "[C:2]", NULL, NULL, NULL},
    {14, "Consuelo Vano", FX_HEAL, 0, 0, 2, 0, "Se engana", "pensando que aun", "estan vivos.", "[C:2]", NULL, NULL, NULL},
    {15, "Consuelo Vano", FX_HEAL, 0, 0, 2, 0, "Se engana", "pensando que aun", "estan vivos.", "[C:2]", NULL, NULL, NULL},
    {16, "Consuelo Vano", FX_HEAL, 0, 0, 2, 0, "Se engana", "pensando que aun", "estan vivos.", "[C:2]", NULL, NULL, NULL},
    {17, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[R:1] [+Juega]", NULL, NULL, NULL, NULL},
    {18, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[R:1] [+Juega]", NULL, NULL, NULL, NULL},
    {19, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[R:1] [+Juega]", NULL, NULL, NULL, NULL},
    {20, "Desesperacion", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Busca frenetica", "por las orillas.", "[R:1] [+Juega]", NULL, NULL, NULL, NULL},
    {21, "Ahogo Profundo", FX_HEAL | FX_SHIELD | FX_ATTACK, 2, 4, 4, 0, "Te sumerge en su", "eterno", "sufrimiento.", "[C:4] [E:4] [D:2]", NULL, NULL, NULL},
    {22, "Llanto Ahogado", FX_STEAL_DECK | FX_SHIELD, 0, 4, 0, 0, "Sus lagrimas", "forman una", "barrera. [E: 4]", "[Roba mazo rival]", NULL, NULL, NULL},
    {23, "Arrastrar al Fondo", FX_STEAL_DISCARD | FX_ATTACK | FX_HEAL, 2, 0, 2, 0, "Te hunde con", "ella.  [D: 2] [C:", "2] [Roba desc]", NULL, NULL, NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int LLORONA_DECK_SIZE = 28;

// MAZO DE Guagua Auca
const CardData CARTAS_GUAGUAAUCA[] = {
    {0, "Lloriqueo", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Finge estar", "indefenso para", "atacarte de", "pronto. [D:1]", "[+Juega]", NULL, NULL},
    {1, "Sorpresa Maligna", FX_ATTACK, 3, 0, 0, 0, "Revela su", "verdadera forma", "aterradora. [D:3]", NULL, NULL, NULL, NULL},
    {2, "Sorpresa Maligna", FX_ATTACK, 3, 0, 0, 0, "Revela su", "verdadera forma", "aterradora. [D:3]", NULL, NULL, NULL, NULL},
    {3, "Sorpresa Maligna", FX_ATTACK, 3, 0, 0, 0, "Revela su", "verdadera forma", "aterradora. [D:3]", NULL, NULL, NULL, NULL},
    {4, "Panales", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Usa su apariencia", "inocente como", "defensa. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {5, "Panales", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Usa su apariencia", "inocente como", "defensa. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {6, "Panales", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Usa su apariencia", "inocente como", "defensa. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {7, "Panales", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Usa su apariencia", "inocente como", "defensa. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {8, "Panales", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Usa su apariencia", "inocente como", "defensa. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {9, "Inocencia Fingida", FX_STEAL_HAND | FX_SHIELD, 0, 2, 0, 1, "Te da compasion y", "te roba lo que", "tienes. [E: 2]", "[Roba de mano]", NULL, NULL, NULL},
    {10, "Inocencia Fingida", FX_STEAL_HAND | FX_SHIELD, 0, 2, 0, 1, "Te da compasion y", "te roba lo que", "tienes. [E: 2]", "[Roba de mano]", NULL, NULL, NULL},
    {11, "Inocencia Fingida", FX_STEAL_HAND | FX_SHIELD, 0, 2, 0, 1, "Te da compasion y", "te roba lo que", "tienes. [E: 2]", "[Roba de mano]", NULL, NULL, NULL},
    {12, "Inocencia Fingida", FX_STEAL_HAND | FX_SHIELD, 0, 2, 0, 1, "Te da compasion y", "te roba lo que", "tienes. [E: 2]", "[Roba de mano]", NULL, NULL, NULL},
    {13, "Biberon de Sangre", FX_HEAL, 0, 0, 2, 0, "Se alimenta de tu", "piedad. [C:2]", NULL, NULL, NULL, NULL, NULL},
    {14, "Biberon de Sangre", FX_HEAL, 0, 0, 2, 0, "Se alimenta de tu", "piedad. [C:2]", NULL, NULL, NULL, NULL, NULL},
    {15, "Biberon de Sangre", FX_HEAL, 0, 0, 2, 0, "Se alimenta de tu", "piedad. [C:2]", NULL, NULL, NULL, NULL, NULL},
    {16, "Biberon de Sangre", FX_HEAL, 0, 0, 2, 0, "Se alimenta de tu", "piedad. [C:2]", NULL, NULL, NULL, NULL, NULL},
    {17, "Risa Macabra", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Se burla de ti", "mientras toma", "ventaja. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {18, "Risa Macabra", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Se burla de ti", "mientras toma", "ventaja. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {19, "Risa Macabra", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Se burla de ti", "mientras toma", "ventaja. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {20, "Risa Macabra", FX_DRAW | FX_PLAY_AGAIN, 0, 0, 0, 1, "Se burla de ti", "mientras toma", "ventaja. [R:1]", "[+Juega]", NULL, NULL, NULL},
    {21, "Dientes de Diablo", FX_ATTACK | FX_DRAW | FX_PLAY_AGAIN, 4, 0, 0, 2, "Muerde el cuello", "de quien lo", "carga. [D:4]", "[R:2] [+Juega]", NULL, NULL, NULL},
    {22, "Berrinche Infernal", FX_STEAL_DECK | FX_STEAL_DISCARD, 0, 0, 0, 0, "Un demonio", "desatado robando", "por doquier.", "[Roba mazo y", "descarte]", NULL, NULL},
    {23, "Muerde Dedos", FX_STEAL_HAND | FX_ATTACK | FX_PLAY_AGAIN, 2, 0, 0, 0, "Engana y ataca", "muy rapido. [D:", "2] [Roba mano]", "[+J]", NULL, NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int GUAGUAAUCA_DECK_SIZE = 28;

// MAZO DE Viuda Tamarindo
const CardData CARTAS_VIUDA[] = {
    {0, "Ilusion", FX_ATTACK | FX_PLAY_AGAIN, 1, 0, 0, 0, "Crees ver a", "alguien mas y", "bajas la guardia.", "[D:1] [+Juega]", NULL, NULL, NULL},
    {1, "Borracho Perdido", FX_ATTACK, 3, 0, 0, 0, "Engana a sus", "victimas hasta", "dejarlas vacias.", "[D:3]", NULL, NULL, NULL},
    {2, "Borracho Perdido", FX_ATTACK, 3, 0, 0, 0, "Engana a sus", "victimas hasta", "dejarlas vacias.", "[D:3]", NULL, NULL, NULL},
    {3, "Borracho Perdido", FX_ATTACK, 3, 0, 0, 0, "Engana a sus", "victimas hasta", "dejarlas vacias.", "[D:3]", NULL, NULL, NULL},
    {4, "Aroma Dulce", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Atrae a incautos", "hacia su trampa", "mortal. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {5, "Aroma Dulce", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Atrae a incautos", "hacia su trampa", "mortal. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {6, "Aroma Dulce", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Atrae a incautos", "hacia su trampa", "mortal. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {7, "Aroma Dulce", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Atrae a incautos", "hacia su trampa", "mortal. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {8, "Aroma Dulce", FX_SHIELD | FX_PLAY_AGAIN, 0, 1, 0, 0, "Atrae a incautos", "hacia su trampa", "mortal. [E:1]", "[+Juega]", NULL, NULL, NULL},
    {9, "Sombra del Arbol", FX_SHIELD, 0, 3, 0, 0, "Las ramas del", "viejo tamarindo", "la protegen.", "[E:3]", NULL, NULL, NULL},
    {10, "Sombra del Arbol", FX_SHIELD, 0, 3, 0, 0, "Las ramas del", "viejo tamarindo", "la protegen.", "[E:3]", NULL, NULL, NULL},
    {11, "Sombra del Arbol", FX_SHIELD, 0, 3, 0, 0, "Las ramas del", "viejo tamarindo", "la protegen.", "[E:3]", NULL, NULL, NULL},
    {12, "Sombra del Arbol", FX_SHIELD, 0, 3, 0, 0, "Las ramas del", "viejo tamarindo", "la protegen.", "[E:3]", NULL, NULL, NULL},
    {13, "Pasion Falsa", FX_HEAL, 0, 0, 2, 0, "Un beso embrujado", "que sana a la", "viuda. [C:2 HP]", NULL, NULL, NULL, NULL},
    {14, "Pasion Falsa", FX_HEAL, 0, 0, 2, 0, "Un beso embrujado", "que sana a la", "viuda. [C:2 HP]", NULL, NULL, NULL, NULL},
    {15, "Pasion Falsa", FX_HEAL, 0, 0, 2, 0, "Un beso embrujado", "que sana a la", "viuda. [C:2 HP]", NULL, NULL, NULL, NULL},
    {16, "Pasion Falsa", FX_HEAL, 0, 0, 2, 0, "Un beso embrujado", "que sana a la", "viuda. [C:2 HP]", NULL, NULL, NULL, NULL},
    {17, "Velo Negro", FX_STEAL_HAND | FX_PLAY_AGAIN, 0, 0, 0, 1, "Te nubla la mente", "y pierdes tu", "mejor carta.", "[Roba de mano]", "[+Juega]", NULL, NULL},
    {18, "Velo Negro", FX_STEAL_HAND | FX_PLAY_AGAIN, 0, 0, 0, 1, "Te nubla la mente", "y pierdes tu", "mejor carta.", "[Roba de mano]", "[+Juega]", NULL, NULL},
    {19, "Velo Negro", FX_STEAL_HAND | FX_PLAY_AGAIN, 0, 0, 0, 1, "Te nubla la mente", "y pierdes tu", "mejor carta.", "[Roba de mano]", "[+Juega]", NULL, NULL},
    {20, "Velo Negro", FX_STEAL_HAND | FX_PLAY_AGAIN, 0, 0, 0, 1, "Te nubla la mente", "y pierdes tu", "mejor carta.", "[Roba de mano]", "[+Juega]", NULL, NULL},
    {21, "Abrazo de Muerte", FX_ATTACK | FX_HEAL | FX_SHIELD, 4, 2, 3, 0, "Te abraza fuerte", "hasta asfixiarte.", "[D:4] [C:3] [E:2]", NULL, NULL, NULL, NULL},
    {22, "Seduccion Oscura", FX_STEAL_DECK | FX_STEAL_HAND, 0, 0, 0, 0, "El engano", "perfecto.  [Roba", "mazo y mano]", NULL, NULL, NULL, NULL},
    {23, "Asfixia", FX_STEAL_DISCARD | FX_ATTACK | FX_PLAY_AGAIN, 3, 0, 0, 0, "Te roba el aire y", "tus recuerdos.", "[D: 3] [Roba", "desc] [+J]", NULL, NULL, NULL},
    {24, "Maldicion Paramo", FX_AURA, 1, 0, 0, 0, "Aura venenosa.", "Dano 1 al rival", "cada turno.", NULL, NULL, NULL, NULL},
    {25, "Robo de Cueva", FX_AURA, 0, 0, 0, 1, "Aura ladrona.", "Roba 1 carta", "extra al inicio", "de tu turno.", NULL, NULL, NULL},
    {26, "Bendicion Sol", FX_AURA, 0, 0, 1, 0, "Aura curativa.", "Cura 1 HP", "pasivamente cada", "turno.", NULL, NULL, NULL},
    {27, "Santuario Oscuro", FX_AURA, 0, 0, 2, 0, "Aura divina. Cura", "2 HP cada turno", "pasivamente.", NULL, NULL, NULL, NULL},
};
const int VIUDA_DECK_SIZE = 28;

